### ISSUE TITLE
Write the "Next Steps" docs page

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#2626]
It was just pointed out to me that the Redux docs have a TOC entry labeled "Next Steps", but that page has never actually been written, so the link doesn't work.  This would be an excellent topic to add.

This HN comment subthread describes some of the topics that would be helpful to have in a "Next Steps" doc:https://news.ycombinator.com/item?id=15343001 , and this tweet is relevant as well: https://twitter.com/Will_Faurot/status/936792737680048128 .

In general, we ought to:

- Provide suggestions for things to do after going through the tutorial sections
- Give advice on how to handle situations that a user may be dealing with trying to build their first "real" app
- Cover that gap between writing a TodoMVC app and building something "real-world"

**Comment by ktrysmt** [comment]
How about practicing DDD with redux and some libraries (such as immutablejs). 
I'm personally interested in it.

**Comment by markerikson** [comment]
@ktrysmt : that sounds like it might be an interesting blog post, but I'm not sure it's something we'd want to add to the docs directly.

**Comment by nbarray** [comment]
It may contains a section on how to use Redux with server-side project? It is often shown as part of a front-side, react-based, application. I professionally use Redux a the model of node apps (apis, microservices, etc.) and had to come up with ways to structure the project around Redux.

**Comment by markerikson** [comment]
@nbarray : also not exactly what I'm thinking of for this topic.  We do have an existing docs page for [server rendering with Redux](http://redux.js.org/docs/recipes/ServerRendering.html), and my React/Redux links list's section on [React and Server Rendering](https://github.com/markerikson/react-redux-links/blob/master/react-server-rendering.md) has several articles that deal with Redux as well.

Hmm.  Re-reading your comment, are you actually talking about using Redux inside a longer-lived server app, rather than just for server-rendering HTML?

**Comment by nbarray** [comment]
@markerikson yes exactly :) No server-side rendering stuff. Just as the "model" for, let's say, a worker or api that needs to handle some kind of state. I just think it is somewhat sad that the excellent redux/flux philosophy is not applied (or not that much talked about) to a node app too.

**Comment by ishankbahl** [comment]
@markerikson , can I give it a shot?

**Comment by markerikson** [comment]
@ishankbahl : sure!

**Comment by ishankbahl** [comment]
@markerikson , can you point me to the articles in your [React/Redux links list](https://github.com/markerikson/react-redux-links) which would be helpful in giving advice about issues involving real world apps?

**Comment by markerikson** [comment]
@ishankbahl : Perhaps some of the info from the [Redux Architecture](https://github.com/markerikson/react-redux-links/blob/master/redux-architecture.md) section?

See the couple links in my original comment for this issue for discussion on the kind of information that would be helpful to have.

**Comment by codedavinci** [comment]
@markerikson, 

What about presenting a real use case where we have an app with components that share of the same data /state , but they're not close (even not related at all), and **Reduxify** it?  avoid Props-drilling..

To show the real need of having a State Management lib like Redux.

**Comment by markerikson** [comment]
@codedavinci : Hmm. That might be a useful addition, although it's not quite what I'm picturing for this page.

**Comment by codedavinci** [comment]
@markerikson Can I draft up something based on the roadmap above ?

**Comment by markerikson** [comment]
@codedavinci : please do!
