### ISSUE TITLE
todos-flow example is broken

### ISSUE THREAD

**Issue by maxsalven** [reduxjs/redux#2717]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

In `examples/todos-flow`, the Flow typings are not working correctly.

Just to be clear, this bug isn't about Flow features which don't exist or aren't possible. They used to work perfectly fine, but are currently broken. **The typings work correctly on Flow 0.54, however they do not work on Flow 0.55 and above. The current version is 0.59.**

`TodoList` has a [required prop](https://github.com/reactjs/redux/blob/master/examples/todos-flow/src/components/TodoList.js#L10) `todos` with type `Todos`, with the [following definition](https://github.com/reactjs/redux/blob/master/examples/todos-flow/src/types/todos.js):

```
export type Todo = {
  +id: Id,
  +text: Text,
  +completed: boolean
};

export type Todos = Array<Todo>;
```

However, if you change [`mapStateToProps`](https://github.com/reactjs/redux/blob/master/examples/todos-flow/src/containers/VisibleTodoList.js#L14) in `src/containers/VisibleTodoList.js` to either not provide the `todos` prop, or provide an invalid type, `yarn flow` will incorrectly report `No errors!`.

This incorrectly reports no errors, even though `TodoList` is not receiving a `todos` prop and will result in a runtime error:
```
const mapStateToProps = (state: State) => {
  return {
    NOTtodos: visibleTodosSelector(state)
  };
};
```

This incorrectly reports no errors, even though `TodoList` is receiving a `todos` prop that does not match the `Todos` type, and will result in a runtime error:
```
const mapStateToProps = (state: State) => {
  return {
    todos: "this is a string, not a an array of Todos, but Flow doesn't care"
  };
};
```

To reiterate, both these examples **correctly report errors** on an older version of Flow, 0.54.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Simply change `mapStateToProps` in `src/containers/VisibleTodoList.js` to either of the two examples above, and run `yarn flow`.

**What is the expected behavior?**

Both examples above should result in Flow reporting an error.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

This became broken in Flow 0.55. Both `mapStateToProps` examples above **correctly report errors in Flow 0.54**.

I have reported this issue to both Flow and flow-typed, however I wanted to raise awareness on the main Redux repo that Flow typings are currently broken in what is a canonical example in this repo.

I personally think Flow's strengths really shine on a large Redux driven codebase, and Redux support in Flow would ideally be treated almost as much as a first class citizen as React is itself. It's a shame to see this broken for nearly three months now.

https://github.com/facebook/flow/issues/5343

**Comment by timdorr** [comment]
None of the core team here uses Flow, so it's not surprising this hasn't been fixed. If someone can give the example some love via PR, I'd love to get it updated!
