### ISSUE TITLE
Doc should mention immer

### ISSUE THREAD

**Issue by AjaxSolutions** [reduxjs/redux#2794]
The Redux doc should mention the immer utility library just as it mentions the Reselect lib.  Both libraries are very useful when working with Redux.

https://github.com/mweststrate/immer

https://redux.js.org/docs/recipes/ComputingDerivedData.html

**Comment by markerikson** [comment]
Immer only came out a couple weeks ago :)  Normally we don't mention tools unless they have a broad following in the community.

That said.... yes, I have been watching Immer closely, and have started recommending it to a number of people.  I'll probably add a mention of it to the "Immutable Update Patterns" page.

**Comment by kapilgorve** [comment]
I would like to work on this.

**Comment by markerikson** [comment]
Cool.  Go ahead and file a PR when you've got something ready and we can look it over.

**Comment by kapilgorve** [comment]
@markerikson I have filed a PR here -  https://github.com/reduxjs/redux/pull/3197. Since this is my first time with redux docs I have tried to be consistent with other examples.

**Comment by markerikson** [comment]
Fixed - thanks!

We might actually want to expand the Immer writeup down the road, but this will do for now.
