### ISSUE TITLE
Move to reduxjs org

### ISSUE THREAD

**Issue by timdorr** [reduxjs/redux#2948]
As per gaearon/redux-devtools#394, Dan owns the https://github.com/reduxjs org. Given that Redux isn't specifically a "React" project and has a fair amount of clout in the frontend world, I think it makes sense to live in its own org.  

We could do things like separating out the examples and docs into their own repos. Or we can consider making #2859 its own repo as well. 

Thoughts? Anything we would need to do to prepare for this move?

**Comment by timdorr** [comment]
Also, do we want to move in any other popular libraries? Reselect would seem likely (@ellbee?). Here's some candidates:

- https://github.com/reactjs/reselect
- https://github.com/gaearon/redux-thunk
- https://github.com/evgenyrodionov/redux-logger
- https://github.com/erikras/redux-form
- https://github.com/paularmstrong/normalizr
- https://github.com/redux-utilities (an org)

Dev Tools are already on their way over. Anyone else want to hop aboard? Feel free to DM me if you want to be included and we'll see if it makes sense.

**Comment by ellbee** [comment]
I think it makes sense to move reselect. It is definitely more closely tied to redux than React, and as I don't have much time to maintain it personally anymore it would be better being in an org where there are plenty of people with commit access if things need doing and I'm not about. Although as part of a move I will make some time to clear up the old issues that are hanging around.

**Comment by timdorr** [comment]
Cool. I'll create a team and invite you in. Let me know if you want to bring in anyone else.

**Comment by timdorr** [comment]
BTW, you can request a transfer into the org from your repo settings page here:

![screen shot 2018-04-20 at 11 49 49 am](https://user-images.githubusercontent.com/17882/39061052-15abd888-4491-11e8-89ec-f18c55eb582e.png)

![screen shot 2018-04-20 at 11 50 03 am](https://user-images.githubusercontent.com/17882/39061053-15ba503e-4491-11e8-90a4-f34bf91ecc51.png)

**Comment by timdorr** [comment]
By the way, I'm planning on moving things over the weekend (unless there's some objection). I'll take care of re-linking the Gitbook account. Luckily redirects stick around forever (@rackt's mostly still work!), so it should be pretty low impact.

**Comment by markerikson** [comment]
I don't have any specific objections to the move, but I'm still not sure I exactly understand what's prompting it in the first place.  As I understand it, the "reactjs" org was originally intended as a "general community-owned-ish" org, and nothing about that has changed.

**Comment by timdorr** [comment]
redux-devtools was still under Dan's personal account, so they were looking to move it to a redux-devtools org. I suggested we roll all things "redux" into one place, rather than get too specific with the org structure. GitHub's team system in orgs has gotten some major improvements over the past year, so it's really well-suited to things like this now.

**Comment by nickmccurdy** [comment]
I also like how it would promote Redux being used outside React as far as the repo URLs go.

**Comment by timdorr** [comment]
Sorry, I had an out-of-town wedding last weekend and I think I just plain forgot the weekend before, but this will happen tonight!


###### (probably...)

**Comment by timdorr** [comment]
![](https://media.giphy.com/media/jVStxzak9yk2Q/giphy.gif)
