### ISSUE TITLE
TypeScript definition issues

### ISSUE THREAD

**Issue by andriy-kudrya** [reduxjs/redux#2982]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Middleware related typings are inaccurate

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
```typescript
interface Dispatch<A extends Action = AnyAction> {
  <T extends A>(action: T): T;
}

interface MiddlewareAPI<D extends Dispatch = Dispatch, S = any> {
  dispatch: D;
  getState(): S;
}

interface Middleware<DispatchExt = {}, S = any, D extends Dispatch = Dispatch> {
  (api: MiddlewareAPI<D, S>): (next: Dispatch<AnyAction>) => (action: any) => any;
}
```
- DispatchExt type is not used
- MiddlewareAPI's dispatch method and next function is restricted to return either Action or AnyAction, while in fact they might return any result from other middlewares in chain (e.g. promise) like this middleware itself. Also redux-thunk dispatches function instead of an action.

```typescript
export interface Action<T = any> {
  type: T;
}

export interface AnyAction extends Action {
  // Allows any extra properties to be defined in an action.
  [extraProps: string]: any;
}
```
- While Action allows to restrict type of field 'type' AnyAction lefts it to be any

**What is the expected behavior?**
Type definitions reflect real redux behaviour

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
4.0.0

**Comment by aikoven** [comment]
> DispatchExt type is not used

It [is used](https://github.com/reactjs/redux/blob/v4.0.0/index.d.ts#L326) by `applyMiddleware` function.

> MiddlewareAPI's dispatch method and next function is restricted to return either Action or AnyAction

There's a type parameter to control the type of `dispatch` of `MiddlewareAPI`. It works with `promise` and `thunk` middleware, see examples [in tests](https://github.com/reactjs/redux/blob/v4.0.0/test/typescript/middleware.ts#L42).

Regarding `next`: I think you might be right, though I doubt that a middleware can make any assumption on what `next` accepts and returns. I guess the most correct type for `next` is `(action: any) => any`.

> While Action allows to restrict type of field 'type' AnyAction lefts it to be any

What's a use case for restricting the type of `type`? `AnyAction` is meant to represent **any** action, not a subset of possible actions.
