### ISSUE TITLE
Should I be storing intermediate results in redux?

### ISSUE THREAD

**Issue by prabuw** [reduxjs/redux#2989]
Hi all,

I'm looking for some guidance on this topic, after looking around and can't seem to find any best practices for this.  I have an example of the title question.

### Search results from autocomplete/typeahead components.

I have used downshift (an autocomplete component) and intergrated it with redux. The flow is as follows:

- On keydown (with some debounce), I raise an action and an api call is made to get the results. 
- The results are stored in an array in the store
- This results array is referenced in the autocomplete component as a prop and the list is rendered. 
- When a selection is made, another action is raised.
- The selected item is used to update the variable representing the selected item in store and the results list is cleared.

The advantage as I see it doing this way is the ability to extract the api call/network request from the component and centralise it at the action creator level. This will make testing my component easier as it's alot dumber.

I have arrived here after doing the api calls inside the component and after reading the myriad of patterns on the web. To me this pattern seems like the state that should be internal to the component is leaking out, but I'm new to this.

Is this an accepted pattern? Am I off base? Are there some practices to keep this tidy?

Thanks,
Prabu

**Comment by timdorr** [comment]
Since they're so ephemeral and generally have no impact on other areas of the application, I generally don't put typeahead results into the store. I treat them like form elements: it's a temporary value that will be committed later, at which point I will put that in the store.

**Comment by markerikson** [comment]
It's always up to you what data you put into the Redux store, and how often you update it.  There's nothing wrong with putting stuff like typeahead data into the store, but as Tim said, there may not be a lot of actual benefit for doing so.

**Comment by prabuw** [comment]
Thanks for the input @timdorr @markerikson.
