### ISSUE TITLE
The recent typings change made me difficult to define Reducers in Typescript.

### ISSUE THREAD

**Issue by PMExtra** [reduxjs/redux#2993]
I open this issue because I don't think this is a normal **Usage Question**, I want to talk why do we change it.

I found we have a typings change recently: (https://github.com/reduxjs/redux/pull/2291 TypeScript typings: reducer state can be undefined)

According to the above issue, I think the point is that we don't need to check the undefined with state, but why do we change the typings at the end?

In the past, I would write a Reducer like:

```Typescript
export const loginRequest: Reducer<ImmutableAuthenticationState> =
  (state: ImmutableAuthenticationState, {payload}: AnyAction & { payload?: LoginRequestParams }) =>
    payload ? state.merge({ /* something */ }) : state);
```

But for now, I have to make it very redundant and complex:

```Typescript
export const loginRequest: Reducer<ImmutableAuthenticationState> =
  (state: ImmutableAuthenticationState | undefined, {payload}: AnyAction & { payload?: LoginRequestParams }) =>
    state ? (payload ? state.merge({ /* something */ }) : state) : INITIAL_STATE;
```

What's wrong?

**Comment by timdorr** [comment]
You need to be providing a default value to the state. That's why the `undefined` was introduced.
