### ISSUE TITLE
[documenation] why do you say subscribers are snapshoted?

### ISSUE THREAD

**Issue by bochen2014** [reduxjs/redux#2999]
I am not sure if it's an error in documentation or if it's because me lack of understanding how redux works.

here is the link
https://stackoverflow.com/questions/50440706/how-do-i-understand-subscriptions-are-snaphostted-before-dispatch

feel free to close it if the it's the latter case.

**Comment by markerikson** [comment]
Yeah, looks like the phrasing in the docs might be slightly out of date.  The snapshotting looks like it happens in `subscribe()` and `unsubscribe()`.

That said, it's an internal implementation detail, and shouldn't generally be a concern for you as an end user.

**Comment by bochen2014** [comment]
If it is internal implementation, it shouldn’t appear in documentation. Can you please take a look? Or remove it if you don’t want user to know about it
