### ISSUE TITLE
Module not found - can't resolve "symbol-observable" 

### ISSUE THREAD

**Issue by Stanko** [reduxjs/redux#3001]
Hello,
I'm sorry to open issue similar to the one closed two years ago, but I'm getting "can't resolve" error for `symbol-observable`:

```
ERROR in /Users/stanko/Projects/marvin/node_modules/redux/es/redux.js
Module not found: Error: Can't resolve 'symbol-observable' in '/Users/stanko/Projects/marvin/node_modules/redux/es'
 @ /Users/stanko/Projects/marvin/node_modules/redux/es/redux.js 1:0-45 280:12-24 295:11-23
```
installing `symbol-observable` independently solves the problem. 

I can see that it exists in my `package-lock.json` and redux's `package.json`, so I'm confused why is it happening.

It is happening with node v10.1.0 and v9.11.1, tried both npm v5 and v6. MacOS 10.13.4

Other packages:
```
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "webpack": "^4.8.3",
    "webpack-cli": "^2.1.3",
    "webpack-dev-server": "^3.1.4"
```

Thank you very much for the great library!

EDIT: this all happened in process of updating our react-redux boilerplate [Marvin](https://github.com/workco/marvin) to the latest stable versions. You can replicate it by using [webpack4](https://github.com/workco/marvin/tree/webpack4) branch (but be sure you removed `symbol-observable` from package.json).

**Comment by Stanko** [comment]
That seems to work, thank you! Weird thing is that I already had `path.join(__dirname, '../node_modules')` there. Adding plain 'node_modules' solved it.

**Comment by msudgh** [comment]
Also this error will occur while the `redux` package is corrupted by installing and updating package.
