### ISSUE TITLE
Middleware is broken

### ISSUE THREAD

**Issue by benoneal** [reduxjs/redux#3019]
### Bug

An important middleware pattern has been broken. IMO the majority of middleware solutions encapsulate their own concerns and are independent of the existence of other middleware. A change was made recently to break a pattern that only caused a minor issue for a specific subset of middleware: those that exhibit different behaviour when interacting with other middleware during the `applyMiddleware` initialisation path. 

Here are some examples: 

```ts
// Make state aware of browser media queries
const mediaQueries = (mediaQueries = defaultMediaQueries): Middleware => store => {
  if (typeof window !== 'undefined') {
    const reverseMap = createReverseMap(mediaQueries)

    const handleMediaChange = ({media, matches}: MediaChangedActionPayload) =>
      store.dispatch(mediaChanged(reverseMap[media], matches))
  
    const addMatchListener = (media: string) => {
      const match = window.matchMedia(media)
      match.addListener(handleMediaChange)
      return match.matches
    }
  
    values(mediaQueries).forEach(media => 
      handleMediaChange({media, matches: addMatchListener(media)}))
  }

  return next => (action: any) => next(action)
}
```
Another example: 

```ts
// Make state aware of user adblockers
const adBlockDetection: Middleware = store => {
  if (typeof document !== 'undefined' && !document.getElementById('XMpADSwgbPUC')) {
    store.dispatch({type: AD_BLOCKER_DETECTED, payload: true})
  }
  return next => (action: any) => next(action)
}
```

Another example:

```js
// Make state aware of socket connectivity and allow synchronisation of actions
const socketMiddleware = ({actionCreator, url, dataSync}) => store => {
  const socket = new WebSocket(url.replace(/(http|https)/, 'ws'))

  socket.addEventListener('message', ({data}) => {
    store.dispatch(JSON.parse(data))
  })

  socket.addEventListener('open', () => {
    socket.send(syncCreator(CONNECT_TO_DOMAIN, store.getState(), null, socket))
    store.dispatch(actionCreator({connected: true}))
  })

  socket.addEventListener('close', reason => {
    store.dispatch(actionCreator({connected: false}))
  })

  return next => action => {
    if (dataSync.hasOwnProperty(action.type)) {
      socket.send(syncCreator(action.type, store.getState(), action.payload, socket))
    }
    return next(action)
  }
}
```

**What is the current behaviour?**

The following error is thrown during `applyMiddleware`, essentially breaking the application:
 
`Uncaught Error: Dispatching while constructing your middleware is not allowed. Other middleware would not be applied to this dispatch`

Refactoring the above middleware to be closed over by the `next =>` function (like below) makes no difference (but is obviously not a viable solution either).

```ts
// Still broken:
const mediaQueries = (mediaQueries = defaultMediaQueries): Middleware => store => next => {
  // ...middlewareCodeGoesHere...
  return (action: any) => next(action)
}
```

**What is the expected behavior?**

Do not break the app. Log a warning if you want, so I can ignore it, because in 100% of my use cases _I do not care if other middleware can handle that dispatch_. I strongly suspect that there are (or should be) very few legitimate reasons why any dispatch from within a middleware context should ever interact with any other middleware in the stack, and if it did, I would consider that a code smell (it would place implicit order dependencies on middleware at the very least).  

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Worked until [this PR](https://github.com/reduxjs/redux/pull/1485).

**Comment by markerikson** [comment]
The middleware init process was explicitly changed in 4.0 in the PR you linked.  This was a deliberate design decision, and intended to resolve #1240.  

I'm not sure I have an immediate suggestion for your use case, other than to try changing your middleware's logic to wait for some manually-dispatched "store is ready" action.

**Comment by timdorr** [comment]
It's still possible to make every one of your examples work. Just dispatch after applyMiddleware. Perhaps in some sort of `setupMiddleware(store)` function or a store enhancer. 

The Error was intentionally introduced as the alternative is to allow users to hit an edge case that has a very non-obvious cause (unless you're familiar with the internals of `applyMiddleware`). Redux takes the stance of preventing user error whenever possible, so this isn't going away.

One alternative might be some sort of callback the middleware can register as a sort of `afterApply` event. Then you would be guaranteed to be dispatching at the correct time, after everything is applied and in order. That would be interesting to think through.

**Comment by anthonyjoeseph** [comment]
For middleware developers encountering this issue, `setupMiddleware(store)` is now done with an `enhancer`

From the [redux docs](https://redux.js.org/recipes/configuring-your-store/)

`Middleware adds extra functionality to the Redux dispatch function; enhancers add extra functionality to the Redux store.`
