### ISSUE TITLE
Redux docs site consuming excessive cpu resources in Chromium browser.

### ISSUE THREAD

**Issue by hypercodex** [reduxjs/redux#3022]
There appears to be a bug in the redux documentation site. All browser tabs that are at the redux documentation consume a disproportionate amount of cpu system resources. Screen shot of Chromium task manager below. 

<img width="669" alt="screen shot 2018-06-09 at 12 30 05 pm" src="https://user-images.githubusercontent.com/14825762/41195392-4d8cae9a-6be1-11e8-9b56-f80c926a74fe.png">

Chromium Version 67.0.3396.62 (Developer Build) (64-bit)
Mac OS 10.13.4

To reproduce: I found it consistently occurs when just having a single redux window open, but will also consume ~90%+ of a cpu core per tab being open.

Loading the documentation SPA found here: https://redux.js.org/

 Profiling the runtime in Devtools results in this console message (which may be unrelated): `DevTools: CPU profile parser is fixing 0 missing samples.`

Also site generates these types of console warnings on first load:
```
[Violation] 'DOMContentLoaded' handler took 504ms
space-part-24.e6ac57f4.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ space-part-24.e6ac57f4.js:1
....
space-part-24.e6ac57f4.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ space-part-24.e6ac57f4.js:1
...
space-part-36.718a5178.js:1 [Violation] 'message' handler took 301ms
```

This problem has persisted for the course of a month and is problematic because it would be nice to be able to browse the documentation without system resources being stepped on.  

Any recommendations? Or perhaps just a heads up to pass along... 

ps. System is modern large workstation spec: 8 core i7, etc.

**Comment by markerikson** [comment]
@SamyPesse : any thoughts?

**Comment by timdorr** [comment]
This isn't an issue on the stable or beta channels for Chrome. Chromium and the dev channel are not supported browsers and are intended for testing only. Any serious problems like this are likely to be resolved as the build moves up the channels. I don't think this is something Gitbook should have to solve.
