### ISSUE TITLE
Mixing dispatch style is throwing error

### ISSUE THREAD

**Issue by isaaclem** [reduxjs/redux#3024]
**Do you want to request a *feature* or report a *bug*?**  
Not sure if it's a bug or a feature request

**What is the current behavior?**
Style1:
this.props.dispatch(functionInAction(someParam));
export default connect(mapStateToProps)(Component);

Style2:
this.props.functionInAction(someParam);
export default connect(mapStateToProps, { functionInAction })(Home);

Mixed Style:
this.props.functionInAction(someParam);
this.props.dispatch(functionInAction2(someParam))

export default connect(mapStateToProps, { functionInAction })(Home);

Throwing warning that this.props.dispatch is not a function and it doesn't dispatch

**What is the expected behavior?**
Since both style 1 and 2 are working fine, mixing style should too, no?

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

"react-redux": "^5.0.7",
"redux": "^4.0.0",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",

**Comment by timdorr** [comment]
[`this.props.dispatch` is provided as a default when `matchDispatchToProps` is missing](https://github.com/reduxjs/react-redux/blob/master/src/connect/mapDispatchToProps.js#L12). So, you have to provide it yourself (in mDTP) to make it available to your connected component's props.
