### ISSUE TITLE
Use `console.warn` to log warnings instead of `console.error`

### ISSUE THREAD

**Issue by baibhavx** [reduxjs/redux#3029]
**Do you want to request a *feature* or report a *bug*?**  
* Feature(Improvement)

**What is the current behavior?**
 * We are using `console.error` instead of `console.warn` to log warnings

**What is the expected behavior?**
* We should use `console.warn` to log warnings unless `console.error` is being used for a good reason.

* There is a brief discussion/suggestion to use `console.warn` to log warnings in this thread: https://github.com/reduxjs/redux/pull/2279

* Incase we decide to go with this, here is the PR with proposed changes: #3030

**Comment by timdorr** [comment]
This is inherited from fbjs's `warning`, which was previously used. It's explained here: https://github.com/facebook/fbjs/pull/94#issuecomment-168332326
