### ISSUE TITLE
Add comparison / alternatives libraries section in doc

### ISSUE THREAD

**Issue by exced** [reduxjs/redux#3034]
It would be nice to have a section in doc about how Redux compare to other state management solutions (Mobx / Mobx-state-tree for instance). There are already many blogs / talks about this topic but there are not centralized.

This would help newcomers understand what are the possible alternatives and if Redux is (or not) more suitable for their team and their project.

**Comment by grantlouisherman** [comment]
Hey @markerikson can I take a stab at this?

**Comment by exced** [comment]
Hi @grantlouisherman, sorry I've written this a while ago and totally forgot it was still pending, I don't think it's still relevant, do you want me to close it ?

**Comment by grantlouisherman** [comment]
@exced you should at least assign it to yourself so people.know it's a claimed issue.

**Comment by exced** [comment]
I closed the issue and the related PR, it's pretty outdated :)
