### ISSUE TITLE
Default import of 'symbol-observable' in redux/es/redux.js is not ESNext...

### ISSUE THREAD

**Issue by Dom-HMH-MTL** [reduxjs/redux#3036]
The translation of an node-like import such as `import $$observable from 'symbol-observable';` which relies on the `main` declaration located in the package.json will produce:

```
import $$observable from '/node_modules/redux/node_modules/symbol-observable/lib/index.js';
import $$observable from '/node_modules/symbol-observable/lib/index.js'; // if dedup-ed...
```

The import of `symbol-observable` in `redux/es/redux.js` fails because the default index.js does not export any symbol...

A temporary fix is to alter the import in `redux/es/redux.js` with `import $$observable from 'symbol-observable/es/index.js';`...

Do you see another approach?

I use redux@^4.0.0 which relies on symbol-observable@^1.2.0.
The application uses Web component based on LitElement (Polymer 3) and we developed an on-the-fly translator for the node-like import definitions in the ESNext modules.

**Comment by timdorr** [comment]
symbol-observable uses a `module` export for ES modules: https://github.com/benlesh/symbol-observable/blob/master/package.json#L29

That file does in fact export a default: https://github.com/benlesh/symbol-observable/blob/master/es/index.js#L19

**Comment by Dom-HMH-MTL** [comment]
My bad! I only looked at the `main` entry in the package.json!
Thanks for pointing me the `module` one.
