### ISSUE TITLE
[Typescript] v4 connect infers incomplete type when using OwnProps

### ISSUE THREAD

**Issue by vincaslt** [reduxjs/redux#3051]
**Do you want to request a *feature* or report a *bug*?**  

There is likely a bug with typescript definitions for connect. Here is the code example:

```typescript
import * as React from 'react';

import { connect } from 'react-redux';
import { deleteUser } from '@app/actions/profileActions';
import { ReduxState } from '@app/reducers';
import { emailSelector } from '@app/selectors/profile';

interface StateProps {
  email: string;
}

interface DispatchProps {
  deleteUser: typeof deleteUser;
}

interface OwnProps {
  enteredPassword: string;
}

type Props = StateProps & DispatchProps & OwnProps;

const DeleteUser = (props: Props) => (
  <div>
    {props.email}
    <button onClick={() => props.deleteUser(props.enteredPassword)}>Delete</button>
  </div>
);

const mapStateToProps = (state: ReduxState): StateProps => ({
  email: emailSelector(state),
});

const mapDispatchToProps: DispatchProps = {
  deleteUser,
};

connect(
  mapStateToProps,
  mapDispatchToProps,
)(DeleteUser);

```

**What is the current behavior?**

This is what connect type is inferred:

> connect<StateProps, DispatchProps, {}, {}, ReduxState>(mapStateToProps: MapStateToPropsParam<StateProps, {}, ReduxState>, mapDispatchToProps: MapDispatchToPropsParam<DispatchProps, {}>, mergeProps: MergeProps<StateProps, DispatchProps, {}, {}>): InferableComponentEnhancerWithProps<{}, {}> (+11 overloads)

OwnProps is not being inferred: `<StateProps, DispatchProps, {}, {}, ReduxState>`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

I expect the types to be equivalent to: `<StateProps, DispatchProps, OwnProps, ReduxState>`

And I could achieve the expected result by specifying types myself: 

```typescript
connect<StateProps, DispatchProps, OwnProps, ReduxState>(
  mapStateToProps,
  mapDispatchToProps,
)(DeleteUser);
```

However, previous versions used to infer this correctly without assistance.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

I am using TS 2.9.2, but the same effect could be seen in 2.8.3. I can reproduce it with Redux v4, and it was never a problem in redux 3.7.x

**Comment by eps1lon** [comment]
1. Your way of importing `connect` is wrong.
2. This is the `redux ` repo not `@types/react-redux`
3. Why do you need the type of connect?
4. You're not using `ownProps` in `mapStateToProps ` or `mapDispatchToProps ` so why should it infer the type for that parameter.

**Comment by vincaslt** [comment]
1. Just a auto import error on my part - but it doesn't make a difference
2. I know, but since redux seems to care about their types (bump versions because of type updates) I figured it could be a good place to register a bug.
3. I don't need the type explicitly - but I see that it's inferred incorrectly. If I were to use this component:

`<DeleteUser enteredPassword="xxx"  />` it will say enteredPassword does not exist in prop type definition, which is false.

4. Because mapState & mapDispatch only tell which props to inject, but the full props must be taken from DeleteUser component (type `React.ComponentType<StateProps & DispatchProps & OwnProps>`) where in previous versions it used to see that out of all three: `StateProps & DispatchProps & OwnProps` `StateProps & DispatchProps` are already injected, so the only one required to be provided is OwnProps

**Comment by eps1lon** [comment]
Thats why I suggesteded you're in the wrong repo. Your code is working perfectly fine for me. What's most likely the problem is your react-redux typing version. 

If you can't change that try explicitly typing your component as SFC. I also suggest you add returntypes to your mapping functions because ts can cause problems with type widening.
