### ISSUE TITLE
support for code splitting?

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [reduxjs/redux#3060]
I'm using redux with redux-saga. Suppose I have 10 reducers. Users can be logged in, and they can be not logged in. 5 of these 10 reducers are specific for logged in users. I don't need to serve those reducers yet when the user is not logged in, right? Correct me if I'm wrong, I think reducers and sagas are always getting included into one bundle because of the way we configure the reducers and the sagas.

currently we configure redux like so:

- We create the reducers, which are functions that handle state manipulation and return the state.
- We combine these reducers.
- We create the store, passing the reducers and middleware as parameters.
- We wrap our app with the `Provider` which accepts the store.

What I want is to be able to dynamically load reducers to load only what's necessary. For example, if the user is already loggedin via a token saved on the localStorage or cookie, then, there's no need to load the login action, but rather the logout action is more necessary, but since the state (especially the initial states) and state manipulators are essentially one (as a reducer), achieving this would be tricky.

**Comment by sprlwrksAprilmintacpineda** [comment]
On the other hand I saw these:

- https://github.com/randallknutson/redux-injector
- https://github.com/GuillaumeCisco/redux-sagas-injector

I think I'll use them.

**Comment by markerikson** [comment]
Yes, there's many existing libs to help manage dynamically loading reducers, sagas, and other code.  See the [Reducers#Dynamic Reducer Injection](https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md#dynamic-reducer-injection) portion of my Redux addons catalog.
