### ISSUE TITLE
Some links in Documentation doesn't work (Table of Contents in any Sub topics under FAQ section)

### ISSUE THREAD

**Issue by pankaja92** [reduxjs/redux#3061]
**Do you want to request a *feature* or report a *bug*?**  

Documentation issue.

**What is the current behavior?**

None of **Table of Contents** links in _sub topics_ (General, Reducers, Organizing State and etc) under _FAQ_ topic in doesn't work

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

1. Go to any of sub topics under [FAQ](https://redux.js.org/faq/) in documentation.
2. (As an example) In [General](https://redux.js.org/faq/general#general-when-to-learn) sub topic click anything in _Table of Contents_
3. (As an example) ​`Can Redux only be used with React?​` clicked. 
4. URL changes but doesn't redirect or navigate to the particular section.

**What is the expected behavior?**

In 4th step (of above) navigate to the particular selected section.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Documentation error

**Comment by markerikson** [comment]
Yes - when we switched to the newer version of Gitbook, it didn't handle the hand-written short URLs I'd originally put in the FAQ.

@SamyPesse , I'd still really appreciate having this fixed :)

**Comment by pietrofxq** [comment]
The "Actions" section on FAQ is leading to a 404 page not found as well

**Comment by franckboudraa** [comment]
Seems to be fixed!

**Comment by SamyPesse** [comment]
@franckboudraa Yes we've released a fix two weeks ago. GitBook now correctly parse the HTML anchors (`<a id="something"></a>`).

@markerikson Sorry for not updating you before, I've started writing a response to https://github.com/reduxjs/redux/issues/3161 to give a better overview of what we are working on at GitBook and how it could suits Redux, but couldn't find the time to post it yet 😔
