### ISSUE TITLE
Upgrading to the latest redux and react-redux breaks typings for async actions

### ISSUE THREAD

**Issue by mduu** [reduxjs/redux#3066]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

After upgrading to the latest redux and react-readux packages (including their typings) we get type errors where we dispatch async actions. The TypeScript compiler complains about a missing "type" property.

Here is where the TS compiler complains:

```typescript
function mapDispatchToProps(dispatch: Dispatch): TDispatchProps {
    return {
        fetchDetails: (forceFetch?: boolean) => dispatch(fetchDetailsAsync(forceFetch)) // <-- ERROR
    };
}
```
The compiler error we get:

```
Error:(54, 58) TS2345: Argument of type 'TDispatchableReturn<ContractsAction, IState>' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'TDispatchableReturn<ContractsAction, IState>'.
```

**fetchDatailsAsync():**

```typescript
export function fetchDetailsAsync(forceFetch?: boolean): TDispatchableReturn<ContractsAction, IState> {
    return async function (dispatch, getState) {
...
```

We updated our ``IDispatchableReturn`` so it looks like this:

```typescript
import { Action } from 'redux';

export type TDispatchableReturn<TAction extends Action, TState> = (
    dispatch: (args: TAction) => void,
    getState: () => TState
) => Promise<TAction>;
```
...but had no luck.

We researched why this happens after upgrading the typings. For us it looks like in the past ``react-redux`` provided its own typing for ``Dispose`` with lesser type-contrains. Not its doesn't anymore so we have to use the ``Dispose`` typing from ``redux`` itself. These got improved/fixed for Redux 4.0.0. They need a ``Action`` which needs a ``type`` property. But async actions don't have this.

The [Redux documentation still](https://redux.js.org/advanced/async-actions) shows the same pattern how to use async actions but this does not work with the currently Typescript typings of Redux 4.0.0 anymore.

This happens in multiple projects with slightly different code-base after we upgraded @type/react-redux to the latest version.

**What is the expected behavior?**

That we get the above code compile (and work again). Eighter the docs are wrong/outdated or the typings don't address async-actions. ...at least as we see it.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

- redux: 4.0.0
- react-redux: 5.0.7 (typing: 6.0.4)

**Comment by encodotom** [comment]
Also experiencing the same issue.

**Comment by timdorr** [comment]
Unfortunately, we're not going to be of much help here. We don't maintain the react-redux typings, so issues with them belong on the DefinitelyTyped repo.

**Comment by mduu** [comment]
The basic issue is: how should one implement async actions using Redux 4.0.0 and TypeScript (without react-redux) with these new redux typings? Seems not to work from our point of view.

**Comment by mduu** [comment]
Placed the issue over at [react-redux](https://github.com/reduxjs/react-redux/issues/979).

**Comment by timdorr** [comment]
No, I meant over at DT's repo. They are maintained by a 3rd party: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by encodotom** [comment]
@timdorr: I have a feeling that it is this commit https://github.com/reduxjs/redux/pull/2674/files which 'breaks' the typings. The typings introduced in said commit contradict the example shown in https://redux.js.org/advanced/async-actions which describes the ability to dispatch a function without returning an action. Note that the commit I've linked to is in the `reduxjs` repo and not `react-redux`, nor `Definitely-Typed`.

**Comment by timdorr** [comment]
Check out the redux-thunk types. Not async per se, but they deal with extending the Action type under 4.0: https://github.com/reduxjs/redux-thunk/blob/master/index.d.ts

**Comment by timdorr** [comment]
@encodotom That PR only touches the tests, not the typings themselves. I think you have the wrong link.

**Comment by encodotom** [comment]
@timdorr: My bad, wrong PR. The typings from redux-thunk seem to do the trick though. Might be worth consolidating them somehow to avoid confusion? Just a thought.

**Comment by timdorr** [comment]
reduxjs/react-redux#900

**Comment by mduu** [comment]
The following change did get our async actions compiled again with latest versions of `redux`, `types/redux`, `react-redux`, `types/react-redux`, `redux-thunk` and `types/redux-thunk`:

```typescript
function mapDispatchToProps(dispatch: ThunkDispatch<IState, Dispatch, ContractsAction>): TDispatchProps {
    return {
        fetchDetails: (forceFetch?: boolean) => dispatch(fetchDetailsAsync(forceFetch))
    };
}

export const PrepareContractPage = connect<TStateProps, TDispatchProps, TOwnProps>(mapStateToProps, mapDispatchToProps)(PrepareContractPageComponent);
```
The basic documentation on async action can be found on the Redux docs as linked in the initial description.

We (me and @encodotom ) are thinking that some of the typings of ``redux-thunk`` are not alligned with current ``redux`` typings as the duplicate stuff.
