### ISSUE TITLE
Add util function to create reducer instead of big function with switch case

### ISSUE THREAD

**Issue by vkbr** [reduxjs/redux#3072]
[Suggestion/discussion]

Reason
A reducer function easily reaches up to 20 switch cases. If you enable the [complexity](https://eslint.org/docs/rules/complexity) rule, then ESLint throws a warning/error for the reducer.

Proposal
A utility function to create reducer without writing a big switch case which would look something like this:
```JS
const COUNTER_INCR = 'counter/increment';
const COUNTER_DECR = 'counter/decrement';

function incrementCounter(state, action) {
    return {
        ...state,
        count: state.count+1,
    };
}

function decrementCounter(state, action) { // action: only required when you pass some extra info
    return {
        ...state,
        count: state.count-1,
    };
}

const initialState = {
    count: 0,
};

const reducer = reduceFrom(initialState)
    .addSwitch(COUNTER_INCR, incrementCounter)
    .addSwitch(COUNTER_DECR, decrementCounter)
    .getReducer();

export default reducer;
```

I can write something quickly if everyone agrees.

**Comment by markerikson** [comment]
We aren't planning to add something like this to the Redux core.  However, there's many implementations of functions like this already (and we even show how to do it yourself in the "Reducing Boilerplate" page in the docs).

I've created a small [`redux-starter-kit` library](https://github.com/markerikson/redux-starter-kit) that does actually have a function like this, and also uses the Immer library to simplify immutable update logic.  We hope to eventually turn this into an official Redux addon, and recommend that people use it.
