### ISSUE TITLE
issue with the redux doc page on ipad mini

### ISSUE THREAD

**Issue by youhongshen** [reduxjs/redux#3076]
Issue with reading the redux doc on an ipad mini 2 (with retina display) running ios 10

For example, i'm trying to access this page (on safari) - also tested with chrome and having the same problem

https://redux.js.org/introduction

My problem is trying to access the contents section so I can choose which section to read.  In portrait mode on my ipad, i see the icon with the three vertical bars, but when i press on it, it does not display the content list.

In horizontal mode, the left panel shows a blank area w/ no contents, and its also not wide enough to show the contents on the right side.  On an ipad pro 13", when viewing the page in horizontal mode, i see the contents area on the right side.

On an iphone 8 in portrait mode, i see the "three horizontal button" and it works.

**Comment by markerikson** [comment]
Paging @SamyPesse  .

Might also want to file an issue on the GitBook issues page, since that's what we use for our docs.
