### ISSUE TITLE
Hot Module Replacement with Redux only works every other time otherwise the page completely reloads

### ISSUE THREAD

**Issue by NearAutomata** [reduxjs/redux#3079]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Replacing Reducers with Hot Module Replacement works every other time but not all of the time. A more detailed explanation with pictures is [available here](https://stackoverflow.com/q/51594983/796036).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
A stripped down (kinda MWE) version can be found here: https://github.com/NearAutomata/redux-hmr-issue

*I removed almost everything, even the second renderer process and `electron-redux` link and the error is still occuring, so it is an HMR issue.*

Clone and run the following commands:

    yarn
    yarn run build-main
    yarn run build-renderer-hot

And in a second terminal run

    yarn run start-hot

**What is the expected behavior?**
I expect the Reducer to be HMR-ed every time and not experience any page reload at all.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux 4.0.0
Electron 2.0.5 and Electron 3.0.0@beta
Windows 10 Build 1803

**Comment by markerikson** [comment]
The `replaceReducer()` API works correctly.  Anything beyond that, including HMR setup and Electron usage, is outside the scope of the Redux core library, so I'm going to close this.

I do appreciate that you took the time to fill out the bug report form correctly :)

**Comment by NearAutomata** [comment]
@markerikson For testing purposes I have added `module.hot.accept();` without arguments right after the first call to `accept` in [this file](https://github.com/NearAutomata/redux-hmr-issue/blob/master/Source/Index.tsx) to prevent a complete reload. Surprisingly enough I am getting the following error:

![](https://i.imgur.com/sRvUdkD.png)

Is this still something regarding Webpack not picking up the appropriate HMR handling with my Reducer or is Redux behaving weird?

**Comment by markerikson** [comment]
I'd assume it's something about the way your app and HMR setup is structured.  I've never worked with Electron myself, so that may be complicating things.

**Comment by NearAutomata** [comment]
Frankly I don't believe Electron to be the culprit but Webpack acting weird as ever. I have opened an issue in the Webpack repository to have it hopefully resolved anytime soon. Thanks for your input.
