### ISSUE TITLE
Excessive generic arguments in TS StoreCreator signature

### ISSUE THREAD

**Issue by Razenpok** [reduxjs/redux#3081]
### Problem:
Current TypeScript signatures for StoreCreator (https://github.com/reduxjs/redux/blob/master/index.d.ts#L221) have excessive generic type arguments in cases when just a reducer or reducer+preloadedState combination is passed.

### Use case:
I was following https://github.com/Microsoft/TypeScript-React-Starter and apparently, it's out of date for some time. Particularly, this bit of code doesn't compile anymore:
```typescript
const store = createStore<StoreState>(enthusiasm, {
  enthusiasmLevel: 1,
  languageName: 'TypeScript',
});
```
To fix it you need to come up with something like
```typescript
const store = createStore<StoreState, EnthusiasmAction, unknown, unknown>(enthusiasm, {
    enthusiasmLevel: 1,
    languageName: 'TypeScript',
});
```

### Solution:
Add another overload that could look like
```typescript
<S, A extends Action>(reducer: Reducer<S, A>, preloadedState?: DeepPartial<S>): Store<S, A>
```
So the code above could be rewritten as
```typescript
const store = createStore<StoreState, EnthusiasmAction>(enthusiasm, {
    enthusiasmLevel: 1,
    languageName: 'TypeScript',
});
```
This observation is based on assumption that without enhancer createStore(reducer, preloadedState) will result in plain Store<S, A> (sry, haven't got time to dig into code).

**Comment by markerikson** [comment]
*sigh*

Frankly, this is exactly why I'm ready to move the types out of the library and drop them over in DefinitelyTyped.  It's all far too complicated, we maintainers don't have the expertise to tweak them, and we've got other things we need to focus on atm (primarily React-Redux internals).

**Comment by johanneslumpe** [comment]
Moving types out of the library doesn’t seem like a great option. Types can easily get out of sync with the actual code, which will only lead to confusion and less trust in those types IMO.

**Comment by Razenpok** [comment]
I've found a workaround:

You can just go with
```typescript
const store = createStore(enthusiasm, {
    enthusiasmLevel: 1,
    languageName: 'TypeScript',
});
```
as TypeScript will infer type arguments from parameters.

IMO this looks kinda sketchy as there are people out there who are obligated/prefer writing type arguments explicitly.

**Comment by cellog** [comment]
I would argue that because the simplest solution (let typescript infer types) works, this issue should be closed. For those who must explicitly specify types, it can be done, it just requires much more verbosity

**Comment by timdorr** [comment]
Yep, this is closeable.
