### ISSUE TITLE
[Docs] typo in AsyncActions.md?

### ISSUE THREAD

**Issue by sJJdGG** [reduxjs/redux#3083]
Today i started rereading redux advanced section again and something caught my eye:
```javascript
const store = createStore(
  rootReducer,
  applyMiddleware(
    thunkMiddleware, // lets us dispatch() functions
    loggerMiddleware // neat middleware that logs actions
  )
)
```
exactly in line 414.
Shouldn't the second argument of createStore be the preloadedState and the the third argument be the enhancer as mentioned in the docs?
Here i see enhancer as the second argument.
I searched a little and i couldn't find any other example that looks like this.
Is this an issue in the docs or is there something i miss here?

**Comment by markerikson** [comment]
`createStore` is flexible.  You can omit the `preloadeState` argument, and pass an enhancer as the second argument instead.
