### ISSUE TITLE
Code examples on Redux website does not work with eslint/prettier

### ISSUE THREAD

**Issue by paradite** [reduxjs/redux#3088]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

- Copy the code from tutorial page such as this page: https://redux.js.org/basics/reducers
- Paste into editor
- Run the code through eslint/prettier
- eslint/prettier reports error `SyntaxError: Unexpected character '​'`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Copy code from [html page](https://redux.js.org/basics/reducers):

https://github.com/paradite/react-redux-todo/blob/master/from-html.js

Copy code from the [gitlab markdown page](https://github.com/reduxjs/redux/blob/master/docs/basics/Reducers.md):

https://github.com/paradite/react-redux-todo/blob/master/from-source.js

Notice that they have different sizes in terms of bytes despite looking exactly the same. By do a diff, you can also see they are different:

```
$ diff from-html.js from-source.js
2c2
<
---
>
7c7
<
---
>
12c12
<
---
>
```

Running prettier, the console produces error for the one copied from html, not the one from source:

```
$ prettier from-html.js

[error] from-html.js: SyntaxError: Unexpected character '​' (2:1)
[error]   1 | import { VisibilityFilters } from './actions'
[error] > 2 |
[error]     | ^
[error]   3 | const initialState = {
[error]   4 |   visibilityFilter: VisibilityFilters.SHOW_ALL,
[error]   5 |   todos: []

$ prettier from-source.js
import { VisibilityFilters } from './actions';

const initialState = {
  visibilityFilter: VisibilityFilters.SHOW_ALL,
  todos: [],
};

function todoApp(state, action) {
  if (typeof state === 'undefined') {
    return initialState;
  }

  // For now, don't handle any actions
  // and just return the state given to us.
  return state;
}
```

**What is the expected behavior?**

No errors should be produced when running code through prettier or eslint.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Redux: the one from https://redux.js.org/basics/reducers
Browser: Chrome
OS: OS X 10.11.6

**Comment by paradite** [comment]
I guess it is better for the Redux team to decide if this is an issue that needs to be addressed or the expected behaviour, so I will keep this issue open.

**Comment by timdorr** [comment]
That appears to be a bug in PrismJS (the underlying syntax highlighting library). It's got an extra `e2 80 8b` in there, which is a zero width space. Not sure what's putting that in there, since it's impossible to actually see on screen (hence the name).

It doesn't appear to be a bug with Gitbook or our docs. You might try reporting it on PrismJS's repo. Interesting find!
