### ISSUE TITLE
Docs: Exceptions to "Single source of truth" principle

### ISSUE THREAD

**Issue by penx** [reduxjs/redux#3094]
The "three principles" in the documentation [contains](https://redux.js.org/introduction/threeprinciples#single-source-of-truth):

> The state of your whole application is stored in an object tree within a single store.

If you follow this religiously, then you end up with solutions like "redux-form", which the author has moved away from towards [final-form](https://github.com/final-form/final-form).

> both inventors of Redux, say that Redux is not the best place to keep form data.
https://codeburst.io/final-form-the-road-to-the-checkered-flag-cd9b75c25fe

@gaearon's comments in this thread are more practical:
https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978

I don't think it's good to be promoting this as a fundamental principle without the caveats mentioned in #1287.

Could something along these lines of this be added to the documentation below the principle?

> There are [some exceptions](https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978). If state within a component does not have any importance to other parts of the application, it does not have to go in redux state. [Form state](https://codeburst.io/final-form-the-road-to-the-checkered-flag-cd9b75c25fe) is a good example of this.

Happy to do the PR myself, just wanted to get opinion on this and any suggestions for wording first.

**Comment by markerikson** [comment]
I'd agree that people often over-apply that statement, but I think that page is fine as-is for now.
