### ISSUE TITLE
Dispatch works faster after page refresh

### ISSUE THREAD

**Issue by DSpade-r** [reduxjs/redux#3096]
I use React 15.5.4
"redux": "3.6.0"
"react-redux": "5.0.3"

When the form is displayed, dispath() takes at least 60 ms.
After page refresh ~ 8-16ms

This applies to all requests.
Is it related that I'm using obsolete libraries? Or is there a solution?

**Comment by timdorr** [comment]
It's hard to know without seeing your code. But more likely it's caching/optimization by your browser. v8 has a lot of tricks to speed up the same code run/loaded on many pages or refreshes. That's not really something in scope for us to address.
