### ISSUE TITLE
Changes to "compose" to allow composition of reducers

### ISSUE THREAD

**Issue by stylemistake** [reduxjs/redux#3097]
I'm not sure if this is a common pattern, but I really like the idea of composing reducers (in a flat, linear fashion) in addition to combining them (in a nested, domain fashion), and I use this pattern myself a lot.

There is a myriad of non-generic implementations, such as [reduce-reducers](https://github.com/redux-utilities/reduce-reducers), [reducer-chain](https://github.com/bydooweedoo/reducer-chain), and [many others](https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md).

Here's an example of how this might look:

```js
const reducer = compose(
  combineReducers({
    router: routerReducer,
    rulebook: rulebookReducer,
  }),
  characterReducer,
  gameStateReducer,
  relayReducer,
  persistenceReducer,
  initialStateReducer
);
```

Reducers can be generalized as value transforms that have a **context** in form of additional arguments. So, this signature:

```js
(input, ...rest) => output
```

is a generalized version of this signature:

```js
(prevState, action) => nextState
```

**Current Redux implementation:**

```js
function compose(...funcs) {
  if (funcs.length === 0) {
    return arg => arg;
  }
  if (funcs.length === 1) {
    return funcs[0];
  }
  return funcs.reduce((a, b) => (...args) => a(b(...args)))
}
```

**Proposed implementation:**

```js
function compose(...funcs) {
  if (funcs.length === 0) {
    return arg => arg;
  }
  if (funcs.length === 1) {
    return funcs[0];
  }
  return funcs.reduce((a, b) => (value, ...rest) => a(b(value, ...rest), ...rest));
}
```

As of now, compose in Redux works the same way as a composition operator in Haskell, which applies `...rest` to only the right-most function. This is a bit of departure from Haskell, but in return it allows to reuse this pattern with state reducers, and in general with anything that accepts a context as a second argument.

This form is compatible with the current usage of compose (composing store enhancers), as enhancers accept only one argument (redux store):

```js
const store = createStore(
  reducer,
  compose(
    applyMiddleware(thunk),
    DevTools.instrument()
  )
)
```

**Potential foot-gun** is that third-parties might abuse this pattern by requiring some context as a second argument, and different libraries might use a different type of context, rendering them mutually incompatible.

Another foot-gun is that composed functions might not be pure. If they mutate the context, things might randomly break, but you can already do that by just mutating the input value (for example mutating state inside the reducer or store object). Moderate levels of sanity are required to use this form the right way.

Probably, the safest way is to introduce a separate `composeReducers` function, that does just that:

```js
const reducer = composeReducers(
  combineReducers({
    router: routerReducer,
    rulebook: rulebookReducer,
  }),
  characterReducer,
  gameStateReducer,
  relayReducer,
  persistenceReducer,
  initialStateReducer
);
```

But I think that a new form of `compose` will be more beneficial and will bring new usage patterns.

I would like to hear some criticism.

**EDIT**: I've updated the implementation to use functional style, as in the current `compose` implementation.

**Comment by markerikson** [comment]
Yeah, _if_ we were going to add something, I'd probably want a separate `composeReducers` function.  We don't have any particular plans to change the core library API at this time, though.

**Comment by Yurickh** [comment]
My 2 cents in this issue.

I often use redux's `compose` with regular functions (like `sumTen = compose(sumFive, sumFive)`) in projects where I don't want to add a whole functional library just for this particular feature.

In that sense, I'm all with @markerikson for adding a separate function, if it is ever made.

**Comment by stylemistake** [comment]
I'm closing this since nobody really cares at this point, and I roll my own `compose` almost everywhere.

**Comment by maclockard** [comment]
@markerikson I find this particularly confusing since the redux docs even use `compose` to compose reducers in the "Structuring Reducers" section: https://github.com/reduxjs/redux/blame/master/docs/recipes/structuring-reducers/BeyondCombineReducers.md#L109-L123

**Comment by markerikson** [comment]
Hmm.  And _I_ wrote that recipe...

I probably should have written it to be `reduceReducers()` instead.
