### ISSUE TITLE
Async Actions documentation issue

### ISSUE THREAD

**Issue by maddn** [reduxjs/redux#3109]
**Do you want to request a *feature* or report a *bug*?**  

Issue with the Async Actions documentation

**What is the current behavior?**

Apologies if I have misunderstood the documentation, but I see a problem with the use of fetchPostsIfNeeded here:

```
store
  .dispatch(fetchPostsIfNeeded('reactjs'))
  .then(() => console.log(store.getState()))

```
fetchPostsIfNeeded resolves straight away if posts.isFetching, so the state will be logged to the console before it has the posts.

**What is the expected behavior?**

I would expect the posts to always be populated in the state after this resolves.

So in this scenario, where a second fetchPostsIfNeeded is dispatched while the first is still fetching,
shouldn't it wait on the fetchPosts promise from the original dispatch so both resolve when the posts have been fetched?

**Comment by markerikson** [comment]
Hmm.  I think I see what you're getting at, but with a thunk written that way, the second call to `fetchPostsIfNeeded()` doesn't have any access to the promise from the first call.

De-duping multiple requests becomes a complex problem, and it's one that thunks aren't really suited for.  Given that this is intended to still be a relatively simple tutorial page, I don't think it's worth worrying about here.

**Comment by maddn** [comment]
Fair enough, but isn't this example already de-duping the requests by tracking `isFetching`?

It was actually the comment in the code directly above (that talks about using `getState()` to check if there is a cached value), which made me think of this problem. If a second request is made while the cache value is being updated using an asynchronous network request, it will get the old value, instead of waiting for the new one.

Instead of storing a boolean like `isFetching`, what about using the promise? `requestPosts()` could temporarily store a reference to the unresolved promise (perhaps called `pendingPosts` rather than `isFetching`), and `receivePosts()` could set `pendingPosts` back to undefined/false, so the promise result isn't kept in the store.

**Comment by markerikson** [comment]
Promises aren't supposed to be put into the store, [because they're not serializable](https://redux.js.org/faq/organizingstate#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state).

I agree that the code atm is a bit flawed, but I'm not sure it's worth making it "perfect" atm.  But, if you've got some other ideas for fixing it, feel free to suggest them or file a PR.

**Comment by maddn** [comment]
The best idea I can come up with without using the promise, is to use `setTimeout()` inside the thunk to poll the value of `isFetching`, but this is not very good!

I feel like I'm missing something because anyone who has read this tutorial, and then used a similar pattern to check if a backend network request is currently in progress, could potentially encounter this problem. It would only happen when the thunk was dispatched multiple times without completing first. But all those subsequent requests will continue to use the cached value in the store without waiting for it to be updated from the backend. And these are the worst kind of defects, because they happen rarely/intermittantly, they can be hard to debug. In this case could lead to some random error because an out-of-date value has been returned by an action somewhere.

So I guess it's just a very unlikely scenario, but I'm suprised there isn't already a clean way to deal with it. Like some optional semaphore built into `dispatch()` which can stop the same thunk executing in parallel (and make it wait instead).
