### ISSUE TITLE
Feature: Move the Notifications back in the event Queu

### ISSUE THREAD

**Issue by Raising** [reduxjs/redux#3110]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**
When you dispatch an action and the reducer is executed and then it sincronously notify using the listener to every connect element that the state of the store has change.

This may cause some problemns when you have a big / complex enougth view as it can take some time to notificate every node wrapped in "connect"  (I had a 300ms case).

Under this situation If some middleware trigger a moderate amount of Reducers in sucesion ( N = 20 for example) it will Execute in sucesion a "Reduce and notification" N Times. And the render of the page will be paused until all 20 notifications are completed so 20 * 300ms = 6seconds.

**Proposition**

As a solution I propose sending the notifications task to the Javascript queue using setTimeOut with 0 miliseconds delay, this wayal reducers will be executed first and then all the notifications but since the listeners system is smart enought only the first notification cascade will have some CPU cost. (Whe may add a Lock so only the first notification is excuted, a simple "if (requireNotification === true)" )

I just implement this solution and reduced a rendering time from 5 seconds to 1second (with a first render without data at 0.4s making the view way more interactive).

at line 191 of createStore.js

```js
setTimeout(() => {
    const listeners = (currentListeners = nextListeners)
    for (let i = 0; i < listeners.length; i++) {
        const listener = listeners[i]
        listener()
      }
    },0)
```

[createStore.zip](https://github.com/reduxjs/redux/files/2318090/createStore.zip)

**Comment by Raising** [comment]
Adding an image to show better the solution
![image](https://user-images.githubusercontent.com/5429363/44582384-cadf3880-a7a1-11e8-8a09-25163462adb6.png)

**Comment by markerikson** [comment]
Yep, there's a whole bunch of "store enhancers" that do this already!  See the [Store#Store Change Subscriptions](https://github.com/markerikson/redux-ecosystem-links/blob/master/store.md#store-change-subscriptions) section of my Redux addons catalog for a list, as well as the [Redux FAQ entry on reducing/batching change notifications](https://redux.js.org/faq/performance#how-can-i-reduce-the-number-of-store-update-events).

**Comment by Raising** [comment]
Thanks for the information, I'll take a look to those enchancers
