### ISSUE TITLE
Add sanity check for accidentally passing two separate enhancers?

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3114]
I've occasionally seen people passing two separate store enhancers to `createStore()` (as seen in [this SO question](https://stackoverflow.com/q/52046340/62937) ).  This is always an error, and it seems like we could add an additional sanity check to `createStore()` - probably just checking to see if we have 3 args, and if the second and third are both functions.  (I would think we can safely assume that the `preloadedState` argument shouldn't be a function.)  It's a rarer problem, but it's preventable.

Thoughts?

**Comment by selbekk** [comment]
I love it enough to create a PR for it :) Not sure if it's a fix or feat or a breaking change - what do you think?

Thanks for all your work and efforts on Redux @markerikson!
