### ISSUE TITLE
Wrong information about createStore?

### ISSUE THREAD

**Issue by sAs59** [reduxjs/redux#3115]
If you look at [dispatch(action)s](https://redux.js.org/api/store#dispatch-action) **Notes** section:

> † The “vanilla” store implementation you get by calling createStore only supports plain object actions and hands them immediately to the reducer.

Does it mean ```createStore``` can also accept actions?

> However, if you wrap createStore with applyMiddleware, the middleware can interpret actions differently, and provide support for dispatching async actions. Async actions are usually asynchronous primitives like Promises, Observables, or thunks.

Can i really wrap ```createStore``` with ```applyMiddleware``` if middleware only wraps the store's dispatch function?

**Comment by timdorr** [comment]
`createStore` doesn't accept actions, it produces a store instance that can accept actions. By default, that takes just plain objects.

`dispatch` is where actions get accepted. Middleware can redefine it to take other things than just plain objects.
