### ISSUE TITLE
use 'slice' instead of 'state' in reducer examples

### ISSUE THREAD

**Issue by joelstransky** [reduxjs/redux#3116]
Just a small point of contention with the Redux docs.
It's probably mentioned somewhere already in the docs but it was a surprise to learn that the `state` that is passed to a reducer is merely the slice of state that the reducer manages. This is in contrast to the `state` that is passed to `mapStateToProps` which is the entire state.
I propose that when discussing reducers, the examples use `slice` in the signature:
```js
function todoApp(slice, action) {
...
}
```
and use `state` only in `mapStateToProps`
```js
const mapStateToProps = state => ({
...
})

**Comment by timdorr** [comment]
This is only the case when using `combineReducers`. If you're using a plain reducer or something like reduce-reducers, then it's the full state object. 

But we definitely provide the full state to the top-level reducer: https://github.com/reduxjs/redux/blob/e63c36a4185d1a31d8b7abcba974016fc984b306/src/createStore.js#L186

**Comment by markerikson** [comment]
A couple thoughts:

- You can always give a function parameter any name you want in your own code.  If you want to call it `function todoApp(fred, samantha)`, you could.
- Part of the idea behind reducer functions having that standard signature is that you could, if you wanted, reuse them in another context, or even as the "root" reducer themselves.  As far as this function is concerned, whatever's passed in as the first argument is the entire "state", and it doesn't care whether that happens to be the actual entire state value for an app, or just a smaller subset.

That said, I do agree that the term "state" is kind of overloaded in the React+Redux ecosystem, but I'm not sure there's much we can do about it at this point.

**Comment by joelstransky** [comment]
I wouldn't say the term `state` is overused. It's a significant pillar of landscape and deserves top billing. My suggestion to use `slice` instead when discussing reducers is merely a mental queue for those of us who don't yet dream in JSX. I'm good on the topic, just wanted to help future learners. 
While parameter naming is open, if everyone did that... well, yuck. 
@timdorr I'm aware it's only in sub-reducers but having two ways to discuss them would be worse than a single misleading one.

Thanks for the feedback.
