### ISSUE TITLE
https://redux.js.org/ description indexed by Google seems malicious/unintended

### ISSUE THREAD

**Issue by zerkz** [reduxjs/redux#3122]
**What is the current behavior?**
Searching for Redux on Google gives quite a strange, unrelated description.  See screenshot below, particularly `Dating > Бланк почтового конверта формата а4 скачать бесплатно.`

![image](https://user-images.githubusercontent.com/1448099/45062355-234dea00-b06e-11e8-90e5-5032df0cd3c6.png)

Able to reproduce from my own Google Fiber connection via Firefox (61.0.2 (64-bit))
  and from a T-Mobile LTE connection on Android via Firefox.

**What is the expected behavior?**
Other search engines like DuckDuckGo/Yahoo show a relevant description.
``` 
We have a variety of resources available to help you learn Redux, no matter what your background or learning style is. 
```

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Not related to the library, but the hosted https://redux.js.org/

**Comment by markerikson** [comment]
Well, that _is_ bizarre.  I see it myself.  Searching the contents of the served-up main docs HTML page doesn't show any of that text that I can see .

@SamyPesse , any idea what's going on here?

**Comment by zerkz** [comment]
I searched through commits and couldn't find any of the text either. Only thing I could think of that would cause this is that the contents of the hosted server were changed post deploy/compile....

**Comment by michaelgv** [comment]
It could be [someone submitted the URL](https://www.google.com/webmasters/tools/submit-url) as well

**Comment by zerkz** [comment]
@michaelgv wouldn't you need to have verified the domain/url as your property though?

**Comment by zerkz** [comment]
Oddly enough Google seems to have indexed the same website with a different description when you use different search terms? 

![image](https://user-images.githubusercontent.com/1448099/45063627-79259080-b074-11e8-8fa5-a68f28365557.png)

**Comment by captbaritone** [comment]
Maybe something to do with the js.org domain? Do you get this result for other sites on that parent domain?

**Comment by SamyPesse** [comment]
@markerikson That *is* really bizarre.

I'm investigating if it could be related to GitBook. But we've never seen something similar on the platform.
We are always fighting with lot of spam content, but it never affected legit content.

When checking the HTML sources of your pages, these pages have no description (you can add one using the YAML front matter), but Google should default to fragment of your content.

Can you try re-indexing the homepage on Google ?

**Comment by SamyPesse** [comment]
It's now working as expected on our side, Have you changed something ?

<img width="810" alt="screenshot 2018-09-05 at 11 51 54" src="https://user-images.githubusercontent.com/845425/45085944-44f8b100-b102-11e8-81b4-221ca07fd307.png">

**Comment by timdorr** [comment]
It's cleared up for me too. 

I guess it's an alert for you if someone is attempting to game the system somehow. Although, I'm not sure how injecting the text that translates to `The form of postal envelope format A4 download free` does anything for a spammer. Google doesn't index itself :)

But since it's fixed and it's mostly on Google's end, I'm closing this out.
