### ISSUE TITLE
UNI CPO ISSUE with REDUX PRICING

### ISSUE THREAD

**Issue by abeheer** [reduxjs/redux#3125]
Hi Guys

Im running
WordPress 4.9.8 
Thema: Woodmart 
Uni CPO: 3.1.7
Redux Framework: 3.6.11

It becomes a problem after version 3.4

Price calculation doesnt work,
€0,00 (fill in all required fields to calculate the price)

And all available options are shown twice because rexus is including jquery framework two times 
https://ibb.co/c4F89e

Does anyone how to solve this?

And can i order some premium support to help solve this?

**Comment by CorwinCZ** [comment]
Hi, this repository is about Redux JavaScript library, not for ReduxFramework :) You are looking for [this](https://github.com/reduxframework/redux-framework/issues). Or [this](https://reduxframework.com/) section support :)
