### ISSUE TITLE
Documentation (Twitter) link broken

### ISSUE THREAD

**Issue by budmc29** [reduxjs/redux#3130]
The current ["No"](https://twitter.com/andrestaltz/status/616270755605708800) link in the [Prior art](https://redux.js.org/introduction/priorart) is broken.

**Comment by timdorr** [comment]
Knowing André, he probably deleted it to move things over to Mastadon or something decentralized.

Honestly, while historically relevant, we've moved on from Flux at this point. So, perhaps the first lines of of that doc should be cleaned up? I'll put in a PR so we can discuss.

**Comment by markerikson** [comment]
Yup, agreed, merged.

Will be interesting to rethink this section in the docs revamp.
