### ISSUE TITLE
Middleware should be wrapped in try catch so the store dispatch is always called

### ISSUE THREAD

**Issue by bginsburg** [reduxjs/redux#3133]
This is a bug in my opinion but could be categorized as feature.

At the moment when using `applyMiddleware` if one of them throws the cycle will stop and the store dispatch will never be called.

I really think that should be changed and make sure the store dispatch is always called.
The middleware should not prevent the default behavior of the store.

Let me know what you guys think, i don't mind helping with the testing and development.

**Comment by markerikson** [comment]
No, not something we plan to implement.  Normal JS behavior applies here.  Besides, if an error occurs during the dispatching process, things have broken anyway.

**Comment by bginsburg** [comment]
Fair enough just wanted to make sure its documented so people can reference this issue

**Comment by bginsburg** [comment]
> No, not something we plan to implement. Normal JS behavior applies here. Besides, if an error occurs during the dispatching process, things have broken anyway.

And i won't always agree about that say you just log according to actions dispatched and the logger throws no reason for the next middleware not to be called...
But i get what you are saying.

**Comment by timdorr** [comment]
That would be up to the logging middleware to catch the error and continue on. If it's generating errors, it has a bug that needs to be resolved.

**Comment by bginsburg** [comment]
Maybe the logger was a bad example but some libraries throw on purpose
