### ISSUE TITLE
combineReducers with strictNullChecks includes 'undefined' which is not assignable to T

### ISSUE THREAD

**Issue by dmstocking** [reduxjs/redux#3134]
EDIT: Just tried this again after fiddling with my project and can't reproduce it all of a sudden. I might be hallucinating this problem?

Currently, the createReducer method tries to check the types of the state to the reducers first parameter. The problem is that with strictNullChecks `T !== T | undefined`.

```
export interface State {
    readonly chats: Map<number, Chat>;
}

const reduce = (state = Map<number, Chat>(), action: Actions) => {
    return state;
};

const rootReducer = combineReducers<State, Actions>({
    chats: reduce, // ERROR 'undefined' is not assignable to 'Map<number, Chat>'
});
```

To fix this, I think you can just change `ReducersMapObject` to

```
export type ReducersMapObject<S = any, A extends Action = Action> = {
  [K in keyof S]: Reducer<S[K] | undefined, A>;
}
```

The addition is the `| undefined` on `S[K]`.

I haven't been able to figure out a work around besides just ts-ignoring it.

Using Redux 4.0.0, with Typescript 2.9.2 and `strictNullChecks` set to true in the tsconfig.json.

This was also asked on StackOverflow with no resolution https://stackoverflow.com/questions/49942382/createstore-with-strict-typescript

**Comment by dmstocking** [comment]
I am closing this for now because I think I messed up something else that caused typescript to spit out my error. Sorry for the inconvenience.

**Comment by varHarrie** [comment]
Same issue. Could you please provide a solution, or tell me something I have missed.
