### ISSUE TITLE
PATRONS.md is out of date

### ISSUE THREAD

**Issue by turtleallo** [reduxjs/redux#3145]
Hey guys. Looks like PATRONS.md is out of date because [Dan's patreon campaign](https://www.patreon.com/reactdx) seems closed. I think it's time to just delete this file OR delete link to Patreon page and write something like "A long time ago Redux was funded by the community."

**Comment by timdorr** [comment]
I don't know what the promise was for being a patron. Was it in perpetuity, or implicitly temporary?

But yeah, we can at least remove that link.

**Comment by turtleallo** [comment]
This is temporary as far as I know. You're patron only while you pay money to the creator each month

**Comment by timdorr** [comment]
@gaearon Do you remember the details of your Patreon deal?

**Comment by turtleallo** [comment]
oops didn't noticed `was`
простите меня конечно
