### ISSUE TITLE
Release a new version of Redux

### ISSUE THREAD

**Issue by TimvdLippe** [reduxjs/redux#3164]
[Version 4.0.0](https://github.com/reduxjs/redux/releases/tag/v4.0.0) has been released back in April, which is half a year ago at the time of writing. It would be great to have Redux 4.1.0 to be published with all additions since April 2018 😄

**Comment by TimvdLippe** [comment]
@timdorr Could you please comment on the closing of this issue? Was this the appropriate to make this request?

**Comment by timdorr** [comment]
There is no schedule for the releases. It will be done whenever I have time to run through it (I like to take care with releases, as it will mess up a *lot* of people's day if a bad release goes out). Asking doesn't affect this timeline.
