### ISSUE TITLE
Change docs examples to always use two spaces

### ISSUE THREAD

**Issue by gaearon** [reduxjs/redux#3172]
Noticed that some of the docs in the recipes section appear to be using four spaces. This is inconsistent with both the rest of the docs and with prevalent JS style in general.

**Comment by timdorr** [comment]
We should be using Prettier on the docs. It handles Markdown and code blocks within Markdown. Some folks have done this as they have edited the files, due to their local config. But we don't have anything set up in our tooling to enforce this.

**Comment by Muhammedalpaslan** [comment]
### wqsaaaaaaaaaaaaaae

### SDASD

1. 

> `_**DSAD**_`

D
D

DD

- DASD### ###
