### ISSUE TITLE
Expose `notifyListeners` in the store API

### ISSUE THREAD

**Issue by migueloller** [reduxjs/redux#3180]
When creating a store enhancer and reimplementing the `dispatch()` method, one usually has to reimplement `subscribe()` and keep track of listeners. If the store expose `notifyListeners()` in its API, it would greatly simplify some store enhancer implementations.

For example, [`redux-batched-subscribe`](https://github.com/tappleby/redux-batched-subscribe/blob/24efa85565cad8c096ed484c31e529c9450978d8/src/index.js)'s source code almost reimplements all of Redux but loses on the benefits of good error messages and other updates to the Redux codebase. If `notifyListeners()` was exposed, then it would only reimplement `dispatch()` and not `subscribe()`.

Thoughts?

**Comment by markerikson** [comment]
Yeah, there were a couple different ideas back in 2016 of ways to refactor out some of that common enhancer behavior.  Dan Abramov had one suggestion, Jim Bolla had a different one.  They both sat open for a couple years and clearly weren't going anywhere, so we closed them.

See #1702 and #2214 for the PRs and discussion.

We definitely have no plans to modify the store itself to expose that behavior.  If someone wanted to revisit those two "enhancer revamp" PRs and put together a new proposal, I'd at least look at it, but in practice the copy-paste aspect doesn't seem to have actually been enough of a problem to justify changes to how enhancers work.
