### ISSUE TITLE
Add a "Code Splitting" docs page.

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3186]
I would like a new docs page added that describes how to code-split Redux reducers (and possibly other pieces of Redux-related code as well).  We'd add it under the "Recipes" section for now, but move it under the future "Real-World Apps" section described in the docs revamp in #2590 when we get that section up.

This page should explain the general principles and technique for code-splitting reducers (re-running `combineReducers` with the new slice reducers, etc).  It should also point to 2-3 of the best-looking existing userland libraries for handling this more automatically, such as https://redux-dynamic-modules.js.org and https://github.com/ioof-holdings/redux-dynamic-reducer .

For reference on this topic, I have links to a few existing articles on code-splitting reducers in the [Redux Reducers](https://github.com/markerikson/react-redux-links/blob/master/redux-reducers-selectors.md#reducers) page in my links list, and a bunch of links to existing libraries in the [Reducers#Dynamic Reducer Injection](https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md#dynamic-reducer-injection) section of my addons list.

Please comment here if you're interested in writing this page!

**Comment by abettadapur** [comment]
I can help in writing this page. I can get started over this weekend

**Comment by JustFly1984** [comment]
Hello everyone! I think my question could be related:

- How could you split reducers based on immutable.js Map as root?

I have pretty much 4 separate redux stores: 

- static
- account
- manager
- admin

account and manager reducers are growing intensively, so I would like to separate some parts to reduce bundle size

**Comment by markerikson** [comment]
@JustFly1984 : there shouldn't be any difference in how you split a state tree with a plain JS object root and an Immutable.js Map root, other than needing to use a specialized version of `combineReducers()` to generate the root reducer.

**Comment by abettadapur** [comment]
Started work [here](/abettadapur/redux/tree/code-splitting)

**Comment by markerikson** [comment]
Merged in #3190 .
