### ISSUE TITLE
Semicolon usage

### ISSUE THREAD

**Issue by cup** [reduxjs/redux#3204]
Semicolon use is the standard for javascript

some may disagree - but the fact is that "semicolon style" works in all cases while "no semicolon style" does not. it seems we have not learned lessons from history? Douglas Crockford agrees:

- https://github.com/twbs/bootstrap/issues/3057
- https://github.com/tc39/ecma262/pull/1062

**Comment by cup** [comment]
https://github.com/reduxjs/redux/issues/3204
https://github.com/reduxjs/redux/pull/3187
https://github.com/reduxjs/redux/pull/3188

**Comment by timdorr** [comment]
We've already made the transition back and forth on this before. We've landed on no semicolons, so we're not going to bikeshed on this anymore.

**Comment by cup** [comment]
@timdorr not sure how a pending official recommendation by the JavaScript Technical Committee could be considered "bikeshedding" - but suit yourself.

**Comment by timdorr** [comment]
You can make the argument in both directions: https://feross.org/never-use-semicolons/

Also, that ECMA 262 proposal is simply a notice about ASI and its implications. It's not a prescription one way or the other to use them. Notably, they reworded away from negative connotations here: https://github.com/tc39/ecma262/pull/1062/commits/c460fe8ca226f492b95f54537a51c226f0292920

**Comment by markerikson** [comment]
I much prefer 4-spaces and semicolons myself, but yeah - the codebase has a format and there's no reason to change it now just for stylistic reasons.
