### ISSUE TITLE
The list counter on the Redux site is wrong

### ISSUE THREAD

**Issue by deebov** [reduxjs/redux#3206]
I've noticed that the list counter on https://redux.js.org/basics/dataflow is not correct. All the 4 steps of the Redux lifecycle are written as 1 ( should be 1, 2, 3, 4. ).
I've tried to fix that on GitHub but here is okay. I think the problem came from GitBook.

**Comment by timdorr** [comment]
Yeah, it's a Kramdown bug under the hood. Not really something we can fix, though we're looking into moving off Gitbook eventually.
