### ISSUE TITLE
add createReducer for redux

### ISSUE THREAD

**Issue by lidoravitan** [reduxjs/redux#3210]
## Motivation
**as mention in docs:** "since many people don't like switch statements, it's very common to use a function that creates a lookup table of action types to case functions. We'll use the createReducer function described in Reducing Boilerplate." [reference](https://redux.js.org/recipes/structuringreducers/refactoringreducersexample#reducing-boilerplate)

I suggest to add createReducer for redux, it very common usage and it leads developers to implement redux with better good practice. sure we also need to add for documentation.
it pretty same as combineReducer utils that is common usage, and redux expose that helper.

## Benefits
* Reducing Boilerplate
* Leads developers for good practice
* Not need to declare this methods for each project as utils or install another package only for createReducer method.

what are you thinking ?

**Comment by timdorr** [comment]
Reducers are just a pure function that takes state and an account and returns the new state. Many are implemented as switch statements, but they aren't necessary to every implementation. So, making that part of the default library is a bit too prescriptive. 

However, we are looking into boilerplate reduction and other tooling to get users started quickly here: #2859

**Comment by markerikson** [comment]
More specifically, we've already added this to our new https://github.com/reduxjs/redux-starter-kit package.  Our version also uses Immer internally to allow users to simplify their immutable update logic considerably.  Try it out!

**Comment by lidoravitan** [comment]
@markerikson do you know if you are planning to add tests coverage to reduxjs/redux-starter-kit ?
I defiantly excited to contribute and help to improve this package.

**Comment by markerikson** [comment]
Looks like we've got a few tests in there, but there might be some more that could help.  Also see the list of open issues.

**Comment by lidoravitan** [comment]
Cool thanks!
