### ISSUE TITLE
Mixing for loop and forEach

### ISSUE THREAD

**Issue by springuper** [reduxjs/redux#3214]
**What is the current behavior?**

For performance sake, I see Redux prefers for-loop to forEach. But actually there are some forEach statements too, for Example: 
- https://github.com/reduxjs/redux/blob/master/src/combineReducers.js#L49
- https://github.com/reduxjs/redux/blob/master/src/combineReducers.js#L66

**What is the expected behavior?**

Either all for loop, or all forEach, don't mix them.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

redux: 4.0.1

**Comment by timdorr** [comment]
It's not a performance thing. We just prefer not to bikeshed on code that works perfectly fine.
