### ISSUE TITLE
Numbering in documentation is stuck on "1"

### ISSUE THREAD

**Issue by agrimm** [reduxjs/redux#3215]
On the page https://redux.js.org/basics/dataflow , which is based on DataFlow.md, the numbering is stuck on "1":

> 1. You call store.dispatch(action).

> 1. The Redux store calls the reducer function you gave it.

> 1. The root reducer may combine the output of multiple reducers into a single state tree.

> 1. The Redux store saves the complete state tree returned by the root reducer.

By contrast, the numbering on https://github.com/reduxjs/redux/blob/master/docs/basics/DataFlow.md is fine.

Is this a fixable issue, or a defect in markdown?

**Comment by markerikson** [comment]
Interesting.  May just be something about how Gitbook parses it.

We're slowly trying to switch over to Docusaurus instead.  Looks like this is okay on that version of the site: https://redux-docs.netlify.com/docs/basics/data-flow .
