### ISSUE TITLE
TypeError in examples/real-world UserPage.js 

### ISSUE THREAD

**Issue by avioli** [reduxjs/redux#3219]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

While running `examples/real-world` updating the route causes a TypeError to be raised.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Run the `real-world` example dev server via `npm start` and load a username or repo, then click on any of the repos or usernames to change the route - triggering a `UserPage.componentDidUpdate`.

A `TypeError` will be raised at https://github.com/reduxjs/redux/tree/691b9e4f2a4d68ae5f3f4d48b4c944a04877e304/examples/real-world/src/containers/UserPage.js#L35.

**What is the expected behavior?**

Not raise any error and load either the user's repos or a repo's users.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

react: 16.3.1
redux: 3.7.2

Did it work in prev versions? Not tested, but assuming - no.

Suggested change to `real-world/src/containers/UserPage.js`:

```diff

  componentDidUpdate(prevProps) {
    if (prevProps.login !== this.props.login) {
-      loadData(this.props.login)
+      loadData(this.props)
    }
  }

```

**Comment by timdorr** [comment]
Can you submit a PR to fix?

**Comment by avioli** [comment]
@timdorr  https://github.com/reduxjs/redux/pull/3220
