### ISSUE TITLE
Redux documentation is very slow and pages are redrawn some time after the initial page load

### ISSUE THREAD

**Issue by palpha** [reduxjs/redux#3222]
Slow pages: Basics > Reducers, for example, takes something like two seconds to load.

Redraws: Load any page. After a few seconds, everything is redrawn.

Observed in Chrome 70 on Windows and macOS, on fast machines with speedy connections. As I know nothing of the underlying technology, I can't provide any insight into what's wrong.

**Comment by timdorr** [comment]
This is in Gitbook's domain to fix. But see #2590 for the general sentiments.

**Comment by palpha** [comment]
Sorry for the noise, thank you for the pointer.

**Comment by timdorr** [comment]
No worries. More input is helpful for us to determine if we need a better solution or not.
