### ISSUE TITLE
Can't use Redux typescript typings in a d.ts file because no namespace.

### ISSUE THREAD

**Issue by waynebloss** [reduxjs/redux#3231]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

The redux typescript typings are useless for creating other typescript definition files that refer to redux types. This is because there is no namespace declared around the types in the `redux/index.d.ts` file.

**What is the expected behavior?**

The typings would be useful for creating other typescript definition files that refer to Redux types. I would wrap them in a namespace or at least provide a copy of the file that is wrapped in a namespace.

**More information and workarounds**

My personal quest to make this work is fully documented on [stackoverflow.com](https://stackoverflow.com/questions/53550649/how-to-reference-redux-types-in-index-d-ts-typescript-definition-file) and repeated here:

I want to create an `index.d.ts` file that reference some types from the popular NPM package known as `redux`.

**That I have tried already:**

_(at the top of my `index.d.ts` file)_

1. `/// <reference path="../../../node_modules/redux/index.d.ts" />`

This doesn't work. I suspect it's because the `redux/index.d.ts` file doesn't declare a namespace at all. When I edit `redux/index.d.ts` file and wrap everything in there with a `declare namespace Redux { ... }`, everything works fine. I am on `redux@^4.0.0`.

2. `/// <reference types="redux" />`

This doesn't work unless I install the NPM package `@types/redux/@3.6.31`, which has old out of date typings that don't match the ones that are published. The latest version of `@types/redux` package is just a deprecated placeholder that says to use the official `redux` package typings (which don't work).

3. `import { Middleware } from "redux";`

When I put the `import` statement shown above into my `index.d.ts` file, every declaration in the file broke (i.e. every other place where I was depending on my own `index.d.ts` file for types stopped reading any types at all from it.) From what I have read, putting an `import` statement at the type of a `d.ts` file causes Typescript to consider that file a module, not a definition file.

**Bad (IMO) workarounds that kinda work but not really:**

1. Installing NPM package `@types/redux@3.6.31` instead of the latest deprecated placeholder version of `@types/redux`.
2. Editing my copy of `node_modules/redux/index.d.ts` to wrap everything in a namespace, e.g. `declare namespace Redux { ... }`.

**Other information:**

My project was bootstrapped with `create-react-app` v2 as a JavaScript project. I am simply using `d.ts` files to document some interfaces. My editor is VSCode latest/stable.

**Comment by markerikson** [comment]
Unfortunately, neither of us primary maintainers actively use TypeScript, and we're certainly not experts.  the current typings were contributed by the community, and we're actually considering moving them over to DefinitelyTyped because we don't have the expertise to maintain them.

It's possible other TS users in the community might be able to help, but I can't offer any real help here.

**Comment by Kovensky** [comment]
You can't augment modules outside of a module augmentation context. You're trying to augment globals, but the redux types correctly don't use globals.

To augment, the redux types, your `.d.ts` file first must escape from global context into module context; you are then free to augment things.

```ts
import {} from 'redux'

declare module 'redux' {
  // anything you declare in here will merge with the types in 'redux'
}
```

**Comment by timdorr** [comment]
@Kovensky has it right. Declaring a namespace would also be a big breaking change. I'd rather rely on the module system for scoping our types. You can look at redux-thunk's types for an example of extending them this way: https://github.com/reduxjs/redux-thunk/blob/master/index.d.ts

**Comment by waynebloss** [comment]
Thank you for your time and help all.

The previous, non-deprecated version of the DefinitelyTyped typings for redux had encapsulated everything into a namespace called `Redux` and I am guessing that they did that because it just makes the typings simpler to consume on some level, as you can see in my case.

This is probably more of an issue with Typescript or VSCodes JSDoc/TypeScript implementation.

According to [this Typescript issue](https://github.com/Microsoft/TypeScript/issues/5506), you can't put an `import` statement at the top of a `d.ts` file so I don't think the solution given here will work and as you can see below, it doesn't work for me and I had to give up and just mock the Redux types myself locally in order to represent them properly.

@Kovensky I tried using your code but it just doesn't work. So, for now I am just going to give up and create my own local types to represent things that I need out of Redux. It's not a huge deal - mostly I am just trying to understand what is going on here. If you're interested, here is what I had tried:

1. In file `Redux.d.ts`:

```ts
import {
Middleware, // Tried with and without this symbol (and all on one line as per your example).
} from "redux";

declare module "redux" { // I also tried making this a namespace, e.g. declare namespace Redux...
  // In vscode, as soon as I typed "Middleware" on the line below, it auto-imported Middleware on line 1.
  type ReduxMiddleware = Middleware;
}
// The following is exactly how I want to use Redux types.
// However, libMyStuff breaks entirely 
declare namespace libMySuff {
  interface MyThings {
    thing: Middleware // Also tried ReduxMiddleware, redux.ReduxMiddleware and Redux.ReduxMiddleware...
  }
}
```

2. In file `tryit.js`:

```js
/// <reference path="./Redux.d.ts" />

/** @param {ReduxMiddleware} mw **/
export function tryit(mw) {
  // Not working. Vscode detects mw as type "any".
}
/** @param {redux.ReduxMiddleware} mw **/
export function tryit1(mw) {
  // Not working. Vscode detects mw as type "any".
}
// The following attempt was made when Redux.d.ts declared a namespace:
/** @param {Redux.ReduxMiddleware} mw **/
export function tryit2(mw) {
  // Not working. Vscode detects mw as type "any".
}

// When Redux.d.ts contained libMyStuff, I tried things like this:

/** @param {libMyStuff.MyThings} things */
function tryit3(things) {
  // Not working. Vscode detects things.thing as type "any".
}
```

Each attempt above was made separately, not mixed with other code attempts in order to minimize any complexity for vscode/intellisense.

**Comment by waynebloss** [comment]
So, here's what finally worked for me...

In my `index.d.ts` file:

```ts
declare module "myLib" {
  import { Store, Middleware } from "redux";
  interface StoreExtensions {
    extraStoreMethod1(): Promise<void>,
    extraStoreMethod2(): Promise<void>,
  }
  export type ExtendedStore = Store & StoreExtensions;
  export interface ExtendedStoreConfig {
    logger?: Middleware,
    otherOptionsEtc: object,
  }
  export function createExtendedStore(config: ExtendedStoreConfig): ExtendedStore;
}
```

In my internal JavaScript files, which implement the code described by the index.d.ts:

```js
/// <reference path=".../index.d.ts" />

/** @param {import('myLib').ExtendedStoreConfig} config */
export function createExtendedStore(config) {
  // yada, yada, yada...
}
```

Now my `index.d.ts` file finally does all the things I wanted:

1. Extends redux types.
2. Serves as a source of intellisense inside the NPM package I'm creating.
3. Serves as typings for dependents of the published NPM package.

**NOTE: ** The `/// <reference /> ` at the top of the javascript file is completely optional. I noticed it makes VSCode pick up types a bit quicker when including it.
