### ISSUE TITLE
Typings dont work for redux version 4

### ISSUE THREAD

**Issue by vidhyeshpatil** [reduxjs/redux#3239]
ERROR in [at-loader] ./node-modules/@types/redux/index.d.ts:120:18
TS2428: All declarations of Dispatch must have identical type parameters

ERROR in [at-loader] ./node-modules/@types/redux/index.d.ts:166:13, 302:42, 302:53 ......so on
TS2314: Generic type Dispatch<A, D, S> requires 3 type argument(s)

**Comment by timdorr** [comment]
They do. We specifically test them too. I'd recommend looking through the test suite for example usages here: https://github.com/reduxjs/redux/tree/master/test/typescript

We're also working on docs for TS usage in #3201.

**Comment by eps1lon** [comment]
@vidhyeshpatil Looks like you have multiple redux typings in your node_modules. Specifically redux now bundles their own types so you don't need `@types/redux` anymore

**Comment by vidhyeshpatil** [comment]
> @vidhyeshpatil Looks like you have multiple redux typings in your node_modules. Specifically redux now bundles their own types so you don't need `@types/redux` anymore

@eps1lon - I use react 15.6.2 version with redux 3.6.2 & react-redux 5.0.7. 

In the current version, Reducer only take 1 arguments. I need to type safe the reducer also.

Can you help me with some example of simple counter, best practice to use TS with react, redux.

**Comment by timdorr** [comment]
@vidhyeshpatil See my comment above. Our test suite and the WIP docs will have what you're looking for.
