### ISSUE TITLE
Docs about immutable.js - can use spread operator

### ISSUE THREAD

**Issue by cktang88** [reduxjs/redux#3280]
According to https://github.com/reduxjs/redux/blob/master/docs/recipes/UsingImmutableJS.md#no-destructuring-or-spread-operators, 
> Because you must access your data via Immutable.JS’s own get() and getIn() methods, you can no longer use JavaScript’s destructuring operator (or the proposed Object spread operator), making your code more verbose.` 

but in the following example, spread operator seems to work just fine?

```
const baseState = List([
    {
        todo: "Learn typescript",
        done: true
    },
    {
        todo: "Try immutable",
        done: false
    }
])
console.log(...baseState) // works as expected
```

**Comment by markerikson** [comment]
The example you're showing is for a List.  I don't know the details of the Immutable.js API, but I imagine it has some support for iterating over lists.

The paragraph you quoted, though, is specifically talking about fields in Maps.  In other words, I can't write:

```js
const {todo, done} = baseState[0];
```

I'd have to write:
```js
const item = baseState[0];
const todo = item.get("todo");
const done = item.get("done");
```

**Comment by lpeliberty** [comment]
When will we be able to destruct props from an immutable object ? It would be a really REALLY nice feature...

**Comment by markerikson** [comment]
Uh... that's an Immutable.js question, not a Redux question.  And as far as I know, the answer is "never", because that's not how Immutable.js works.
