### ISSUE TITLE
Inline links, blockquote links, general page links need improved a11y support

### ISSUE THREAD

**Issue by resource11** [reduxjs/redux#3283]
The links in the blocks of text within the Redux docs need more distinction than a simple color differentiation, to pass WCAG 2.1 SC [1.4.1](https://www.w3.org/TR/WCAG21/#use-of-color) and [1.4.3](https://www.w3.org/TR/WCAG21/#contrast-minimum). Suggested adds are underlining hyperlinks within blocks of text, and improving the hover/focus/active states.

**Comment by markerikson** [comment]
I believe this has been resolved for now.  If you see any other a11y-related concerns, please go ahead and open up new issues/PRs.

Thanks!
