### ISSUE TITLE
Redux documentation is down - SSL certificate issue

### ISSUE THREAD

**Issue by MrJohz** [reduxjs/redux#3287]
**Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**What is the current behavior?**

Navigating to https://redux.js.org/ returns a privacy error.

Specifically, in Chrome at least, the error is NET::ERR_CERT_COMMON_NAME_INVALID, and in Firefox the error is SSL_ERROR_BAD_CERT_DOMAIN.  The certificate served by https://redux.js.org/ is valid for `*.netlify.com` and `netlify.com`, and not for anything under the `js.org` domain.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

1. Navigate to https://redux.js.org/
2. There is an error.

**What is the expected behavior?**

I should be able to browse to the Redux documentation and read it.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

I was using the documentation yesterday, about 16 hours previously to this post.  I noticed it this morning about fifteen, twenty minutes ago, when I first navigated to the Redux documentation today.

I experience this issue using Chrome (Version 70.0.3538.110 (Official Build) (64-bit)) and Firefox (63.0.3 (64-bit)), although I imagine the same issue will show up in every browser version released in the last five or ten years... ;)

**Comment by markerikson** [comment]
Yep, we just switched over to the new docs site hosted on Netlify, and it took a bit for Netlify to deploy a new SSL certificate for us.  Should be fixed now.  If it persists, let us know!
