### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by web2033** [reduxjs/redux#3288]
Recipes: Index
https://redux.js.org/recipes/index

![2018-12-11_112643](https://user-images.githubusercontent.com/11320080/49790753-aa7ac000-fd37-11e8-8fda-61c1e2d5b78f.jpg)

**Comment by markerikson** [comment]
Yeah, bad path with the rebuilt docs site.  Should be fixed now.  Let us know if you find any other broken links!
