### ISSUE TITLE
Add a "Testimonials" docs page

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3294]
I'd love to have a page with actual testimonials from real end users who are using Redux to do nifty stuff, especially things that really show the benefits of Redux (middleware that manipulate actions, apps that persist or sync state, scaled-up codebases, etc).

If you're using Redux, I'd love to have you leave a comment here with a quote that talks about:

- Who you are and where you're using Redux
- How it's helping your development
- _Why_ you're using Redux
- Some of the scale of your application in terms of SLOC, reducers, number of users, etc

Quotes from developers with any size of app are welcome :)

**Comment by EfstathiadisD** [comment]
I would love to have that, as well as CodeSandbox examples, and webinars that allow us to learn from others. Blogs are fun but, they have limited interactivity. We need another medium for cool technologies, especially the ones that start to mature.

JS, needs to stop inventing and replacing framework after framework, but built upon and around 4-5-6 existing ones, in order to really help people create amazing stuff.

If you need help or volunteers, reach out. I know a few people.

**Comment by theproactivedev** [comment]
Hi! It's my first time to open source projects. Is this open for contribution? I've created one design for this if this is open. Let me know. Thank you! :D

![redux_testimonials_edited](https://user-images.githubusercontent.com/9198365/55686234-396bb200-5991-11e9-91a2-15f193cbd282.png)

**Comment by markerikson** [comment]
Hiya.  Yeah, this is open in general, although to be honest I haven't really given it any thought since I created the issue.

I guess the biggest thing that needs to be done is actually getting folks who use Redux to contribute quotes and blurbs that we can post :)  Once we've got some actual testimonials to put up there, then yeah, some good formatting would be helpful.

Lemme see if I can maybe tweet a request tomorrow for folks who would like to be featured here or something.

**Comment by theproactivedev** [comment]
Yeah, I agree. Just mention me anytime when you get folks willing to get their blurbs posted and when you will give this issue a go. Thanks :D

**Comment by kapilgorve** [comment]
I would be also interested to contribute to this. I can collect the quotes from response thread. Posting on reddit might generate a better response.

**Comment by markerikson** [comment]
Slightly belated, but just tweeted that request: https://twitter.com/acemarke/status/1120535529936891905

**Comment by alexreardon** [comment]
👋 big fan. I am happy to contribute

**Comment by alexreardon** [comment]
Where you after a general comment on the library itself, or more of a why and how we are using it?

**Comment by markerikson** [comment]
more of the "why and how", with the intended usage being including it in that eventual docs page attributed to you.

**Comment by alexreardon** [comment]
Here we go:

> `redux` is a simple, yet fantastically powerful and fast state management solution. We chose `redux` for `react-beautiful-dnd` in order to facilitate fast deep tree updates in `react` (with `react-redux`), and for middleware which allows for complex data flow logic. Developing with `redux` is a pleasure thanks to it's extensive documentation, tests, passionate maintainers, and large community.

**Comment by mpeyper** [comment]
Wow, I could write multiple quotable comments on how and why we use redux at IOOF. I stand by that tweet, but could also talk about testability, predictability, the strange things we do with middleware (e.g. auth, analytics), the amazing docs, the incredible Dev tools, and probably more if I put my mind to it.

Too much for one testimonial, so let me know which one(s) you're most interested in.

**Comment by kumar303** [comment]
>     * Who you are and where you're using Redux

[Kumar McMillan](http://farmdev.com/), Staff Software Engineer at Mozilla.

My team uses React and Redux on https://addons.mozilla.org (code: https://github.com/mozilla/addons-frontend/)

> 
>     * How it's helping your development

What if you could stop an infinite loop by pressing a pause button? With Redux you can! I can't imagine building a UI without Redux and its developer tools. Debugging is easy. Testing is easy. Bouncing between states while designing screens is easy. Everything is just easy.

> 
>     * _Why_ you're using Redux
> 

It makes development fun and easy.

>     * Some of the scale of your application in terms of SLOC, reducers, number of users, etc

* 11 million monthly users
* 96K SLOC
* 29 reducers

**Comment by timdorr** [comment]
Closing in favor of #3602
