### ISSUE TITLE
Landing page UI improvements

### ISSUE THREAD

**Issue by tranhl** [reduxjs/redux#3296]
Looking at the landing page for all Redux projects, I noticed a few style changes that could be made to improve the overall look and feel of the landing pages, so I went ahead and made the following adjustments to the site:

- Increased the size of the search field to give it more breathing room and bring a little more attention to it.
- Equalized the spacing between the three sections of the page ("Getting Started", "Key Features", and "Related Projects").
- Applied text centering to the "Key Features" grids so that the text is more aligned and easy to scan.

I'd be more than happy to make a few PRs across the different Redux projects and apply these styles to the website. Also open to feedback on the changes as well. Thanks!

# Before

![Before](https://user-images.githubusercontent.com/24240419/49860445-eb64f880-fe4d-11e8-9369-665e4d7ca0d3.png)

# After

![After](https://user-images.githubusercontent.com/24240419/49860454-edc75280-fe4d-11e8-84bd-302844eab2c5.png)

**Comment by timdorr** [comment]
Please do make a PR. I'm more than happy to give it a look. As a bonus, Netlify gives us a working preview of the site. I'll close this out to avoid some duplication. Thanks in advance!

**Comment by markerikson** [comment]
I originally had the "features" paragraphs justified, but folks complained on Twitter that that was hard to read, so I changed it to left-aligned.  I'd rather not keeping fiddling with that :(

**Comment by markerikson** [comment]
I do want to see what the rest of the style changes were.  Could you file a PR or let us know what you changed?

**Comment by markerikson** [comment]
I made some spacing changes in #3296 , but we can always tweak things further.
