### ISSUE TITLE
Redux store remove some reducers by replaceReducer, state is not removed immediately

### ISSUE THREAD

**Issue by zhbhun** [reduxjs/redux#3300]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

https://codesandbox.io/s/2v9jlj2rj0

While store.replaceReducer accept new reducer(created by combineReducers and remove some reducer), store state does't remove the state of that reducer .

**What is the expected behavior?**

store.replaceReducer should remove state of removing reducer.

https://github.com/reduxjs/redux/blob/master/src/combineReducers.js#L176

`hasChanged` may check `nextState`'s key count with `state`'s key count.

**Comment by timdorr** [comment]
We dispatch an action right after replacing the reducer, so you can build your reducer function to clear unknown keys if you want: https://github.com/reduxjs/redux/blob/master/src/createStore.js#L227

**Comment by zhbhun** [comment]
But redux does't recommend to use actionType: https://github.com/reduxjs/redux/blob/master/src/index.js#L35.

By the way, reducer function does't receive the replace action when using redux-devtools-extension in development: https://codesandbox.io/s/j3l2r9vnr9. In this demo, the state of removed reducer is also removed. But it still not work (the state of removed reducer is still in store) in my complex project.

While adding or removing reduce dynamically, my reducer may receive wrong default state that is last removed reducer's state.

**Comment by leoyli** [comment]
+1, I think it is a bug.  I do see my state unmounted in the devToos, but when I mount the reducer again, the state is the previous state, not the initial state.

**Comment by mihanizm56** [comment]
Also have the save problem. After the reducer is removed - I it cannot be triggered and it isn't shown in dev-tools.
But right after injecting it in the next return to the page - the data is exist!
