### ISSUE TITLE
Feature Request - Redux's Types for Typescript

### ISSUE THREAD

**Issue by carpben** [reduxjs/redux#3328]
**What is the current behavior?**
One of the core principles of Redux is that state should be immutable. Practically however, state could be mutated either in the reducer, and later on in components. 

**What is the expected behavior?**
We can now statically check mutation of objects by defining their type as DeepReadonly ([source1](https://stackoverflow.com/questions/41879327/deepreadonly-object-typescript), [2](https://www.npmjs.com/package/utility-types), [3](https://t.co/LnQjZHW0A9)). This could further be used for functions, by defining their parameters as DeepReadonly. I've started using it in my code and it works quite well. I get an error in the editor once I try to change a property of a parameter defined this way. It would be great if we can add this feature to the type of Redux's reducers. Something like: 

```ts
type Reducer<S = any, A extends Action = AnyAction> = (
  state: DeepReadonly<S | undefined>,
  action: DeepReadonly<A>
) => DeepReadonly<S>
```
This can protect state from mutation. 
To a lesser degree this could be relevant to Actions as well.

**Comment by timdorr** [comment]
I think this is something that should stay on the user's end. You can either mark properties of your State type as readonly, or use something from utility-types. But I think trying to be proactive about forcing one-way data behaviors might be an issue. Many times folks put non-primitive values into their state, possibly with more complex typings. While they probably shouldn't be doing that, I don't think it's our job to say they can't.

**Comment by carpben** [comment]
@wmira, While I too think this feature could be useful, there is no need to define each field as readonly. As I mentioned in the original post, today you can use a generic DeepReadonly type, and pass it any object. The result would be a new type with all fields defined as readonly. I believe you can import DeepReadonly from utility-types. This will look something like: 

```ts
interface IAction {
   type:string
   payload:SomeType
}

interface IState {
    a: number, 
    b: string, 
    c: array
}

const reducer : Reducer<DeepReadonly<IState>, DeepReadonly<IAction>> = 
   (state, action) => {
      ....
     Reducer Code 
     ....
   }
``` 

All fields and subfields of state and action will be defined as readonly in the reducer.

**Comment by carpben** [comment]
@timdorr, What if instead of changing the type Reducer, we add another type of reducer, which defines state and action as DeepReadonly? This will allow only users who want this feature to opt in conveniently. 

My understanding is that not mutating state is an important principle of Redux, and Many programmers use various tools to avoid muation (Immer, ImmutableJS etc.). So I think offering a type of a reducer that protects state could be of benefit. I'll be happy to prepare a PR.
