### ISSUE TITLE
v4 breaking change: lib dir with cjs files removed

### ISSUE THREAD

**Issue by srghma** [reduxjs/redux#3348]
In v3 I used to import bindActionCreators from `lib` dir, that contained code compiled to cjs

```
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
const bindActionCreators = _interopRequireDefault(require('redux/lib/bindActionCreators'))
```

In v4 this is no longer possible.

____________

I cant use `src` dir too, because it's es
```
# will throw error because of the `export ....`
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
const bindActionCreators = _interopRequireDefault(require('redux/src/bindActionCreators'))
```

_____________

Workaround is 

```
const bindActionCreators = require('redux').bindActionCreators
```

but it's bad for project size

Q: why not to return cjs compiled files?

**Comment by timdorr** [comment]
With a tree-shaking bundler, any unused imports will be automatically dropped. That won't apply to CJS files, but will work with ES modules. 

This and other reasons are in the PR that changed this: #2358
