### ISSUE TITLE
Symbol keys in combineReducers

### ISSUE THREAD

**Issue by grundiss** [reduxjs/redux#3352]
**Do you want to request a _feature_ or report a _bug_?**
Well, both...

**What is the current behavior?**
I know, that redux encourages "serialization first"-way of doing stuff. However I think sometimes it causes difficulties. I want part of my store to be serializable and part of it — not. What I try to do:
```javascript
combineReducers({
  x: (state, action) => state,
  [Symbol.for('y')]: (state, action) => state,
})
```
Because of how `combineReducers` works, my `y`-reducer is getting lost.

**What is the expected behavior?**
As a developer I'd like to be more in control of keys I put in `combineReducers`.

**Comment by timdorr** [comment]
This isn't possible. [We use `Object.keys`](https://github.com/reduxjs/redux/blob/master/src/combineReducers.js#L116), which will skip over Symbol keys. Unfortunately, there isn't a unified API for getting both Symbol and string keys, so we assume the common case of string keys. 

I personally don't think there's a reason to use Symbol keys, as they are relatively difficult to work with. I'd stick to string keys.

**Comment by unadlib** [comment]
`Reflect.ownKeys` is a good improvement API, and it has a complete polyfill. So will you really consider that it is the optional replacement and uses `Object.keys` by default?

**Comment by unadlib** [comment]
@timdorr Because in some redux-based encapsulation implementations, the symbol is occasionally required to be used in `combineReducers`,  it will become very meaningful.

**Comment by markerikson** [comment]
I don't think we need to implement this in the core.  If you'd like to create your own version of `combineReducers` that handles Symbols as well, go ahead!
