### ISSUE TITLE
The code in server rendering recipe doesn't guarantee the same initial state is used to render on server and client

### ISSUE THREAD

**Issue by yelite** [reduxjs/redux#3353]
In https://github.com/reduxjs/redux/blob/master/docs/recipes/ServerRendering.md, server and client code are as follow:

#### `server.js`

```js
// Compile an initial state
let preloadedState = { counter }

// Create a new Redux store instance
const store = createStore(counterApp, preloadedState)

// Render the component to a string
const html = renderToString(
<Provider store={store}>
  <App />
</Provider>
)

// Grab the initial state from our Redux store
const finalState = store.getState()

// Send the rendered page back to the client
res.send(renderFullPage(html, finalState))
```

#### `client.js`

```js
// Grab the state from a global variable injected into the server-generated HTML
const preloadedState = window.__PRELOADED_STATE__

// Allow the passed state to be garbage-collected
delete window.__PRELOADED_STATE__

// Create Redux store with initial state
const store = createStore(counterApp, preloadedState)

hydrate(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
)
```

Note that client DOM is rendered with a different redux state than the one used to render server DOM. In few cases, this leads to DOM mismatch when hydrating in client side (I found this issue when fixing DOM mismatch caused by `redux-form`).

I believe the right place to get preloaded state is before `createStore`, so that code path between getting 'preloaded state' and hitting `renderToString`/`hydrate` keeps the same on client and server.

Few updates on those example code are made on my branch https://github.com/reduxjs/redux/compare/master...yelite:patch-1 

I am wondering if there is anything wrong with my approach, because the original code snippet is in official doc for years. There might have some reason that I didn't realize.

**Comment by timdorr** [comment]
I think you're misinterpreting what the initalState argument does. It loads up the store with an initial value for state. It does not get updated with the state of the store over time. It is discarded. Your proposed changes would lead to a `__PRELOADED_STATE__` value of just the same initial `{}`.

**Comment by yelite** [comment]
@timdorr 
> It does not get updated with the state of the store over time.
That's the point. It doesn't get updated. `__PRELOADED_STATE__` should be the same state that drives the server side rendering, in order to make `hydrate` work without DOM mismatch.
