### ISSUE TITLE
Ask for Help:what is this statement grammar for js?

### ISSUE THREAD

**Issue by theflycloud** [reduxjs/redux#3373]
Ask for Help:what is this statement grammar for js? 
   [$$observable]: observable

I saw this in createStore.js,not understand this kind of syntax(especially there is a pair of square brackets) . Does anyone help explain the syntax.?

**Comment by timdorr** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names
