### ISSUE TITLE
Enhance error handling : bad React Nodes passed to the state.

### ISSUE THREAD

**Issue by Aarbel** [reduxjs/redux#3376]
I losed 2 hours to understand that i was passing a React Node to my Redux Store, and that was making my app crash without throwing an error. My breakpoint stopped on this function : 

```JS
function stringify(obj, replacer, spaces, cycleReplacer) {
  return JSON.stringify(obj, serializer(replacer, cycleReplacer), spaces)
}
```
These lines are inside `json-stringify-safe` dependency, and used by `redux-persist`.

Could be great to throw an error on this case ;)

**Comment by timdorr** [comment]
Throwing an error inside of a reducer makes the function impure, which is a requirement of Redux. There should either be sufficient checks to ensure it does not throw an error.

**Comment by markerikson** [comment]
Note that the [`configureStore` function](https://redux-starter-kit.js.org/api/configureStore) from our new [Redux Starter Kit package](https://redux-starter-kit.js.org/) includes a middleware by default that will [warn if you've put a non-serializable value into actions or the state](https://redux-starter-kit.js.org/api/getdefaultmiddleware#included-default-middleware).  I'd encourage you to try using that.
