### ISSUE TITLE
[examples] todos-flow combineReducers() throws Flow error of missing type annotations

### ISSUE THREAD

**Issue by synchronos-t** [reduxjs/redux#3377]
There seems to be something missing in the type annotations of the _todos-flow_ example, as its [combineReducers()](https://github.com/reduxjs/redux/blob/104b134f98d4ae8f091f696148cec75010526301/examples/todos-flow/src/reducers/index.js#L8) function throws a Flow error:

> Missing type annotation for `A`. `A` is a type parameter declared in  function type [1] and was implicitly instantiated at  call of `combineReducers` [2].

Where the [1] is the type declaration from flow-typed:
`declare export function combineReducers<O: Object, A>(reducers: O): CombinedReducer<$ObjMap<O, <S>(r: Reducer<S, any>) => S>, A>;`

and the [2] the call:
`export default combineReducers({
  todos,
  visibilityFilter
});`

So, I inferred that I should type annotate the combineReducers() something like:
`export default combineReducers<CombinedReducers, State>`

So, the example should instead be something like this, amirite?
```
import type { State } from '../types';

const reducers = {
  todos,
  visibilityFilter,
};

export default combineReducers<typeof reducers, State>(reducers);
```

Or is there something missing in the flow-typed definitions?

I tested using the example project and let the npm and flow-typed just install their things. (I also changed the .flowconfig not to refer to ../../flow-typed, but instead just flow-typed.)

**Comment by stevewillard** [comment]
@synchronos-t ran into the same issue. Were you able to resolve this?

**Comment by maryjenel** [comment]
I resolved this by 
```export default combineReducers<Object, Action>(reducers);
```

**Comment by wgao19** [comment]
Hey @synchronos-t the second type parameter for `combineReducers` is meant for action instead of state. Check out the [libdef for redux in Flow Typed](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/redux_v4.x.x/flow_v0.55.x-v0.88.x/redux_v4.x.x.js#L53), the file has some more definitions on the top that you can learn about Redux's annotations.

**Comment by markerikson** [comment]
Honestly, I'm inclined to delete the `todos-flow` example at this point.  We don't need like 5 variations of the todos example.

**Comment by timdorr** [comment]
I agree. We don't maintain those types, so it doesn't make sense for us to have an example that uses them.

**Comment by markerikson** [comment]
Closing this, and we're going to get around to deleting that example at some point soon.
