### ISSUE TITLE
TypeScript: `combineReducers` returns incorrect type

### ISSUE THREAD

**Issue by OliverJAsh** [reduxjs/redux#3379]
**Do you want to request a _feature_ or report a _bug_?**

Bug

Re. https://github.com/reduxjs/redux/pull/2809

**What is the current behavior?**

``` ts
import { AnyAction, Reducer, combineReducers, Action } from 'redux';

type State = {
  reducerA: number;
  reducerB: number;
};

declare const reducerA: Reducer<State['reducerA']>;
declare const reducerB: Reducer<State['reducerB']>;

// Expected type: `(state: Partial<State> | undefined, action: AnyAction) => State`
// Actual type: `(state: State | undefined, action: AnyAction) => State`
const stateReducer = combineReducers({
  reducerA,
  reducerB,
});

declare const action: AnyAction;

// Unexpected error!
// Argument of type '{ reducerA: undefined; reducerB: undefined; }' is not assignable to parameter of type 'State'.
stateReducer(
  {
    reducerA: undefined,
    reducerB: undefined,
  },
  action,
);

// Workaround (so long as `strictFunctionTypes` is disabled):
type ReducerWithInputType<InputState = any, S = any, A extends Action = AnyAction> = (
  state: InputState | undefined,
  action: A,
) => S;
const stateReducer2: ReducerWithInputType<Partial<State>, State> = combineReducers({
  reducerA,
  reducerB,
});
const state = stateReducer2(
  {
    reducerA: undefined,
    reducerB: undefined,
  },
  action,
);
```

**Comment by timdorr** [comment]
I'm not getting this error. What version of TS are you on? I'm on 3.3.3 myself.

**Comment by OliverJAsh** [comment]
3.3.3333, with `strict` enabled.

**Comment by timdorr** [comment]
Ah, that's what I was missing. 

Well, I'm not seeing why you would expect a Partial type for your State. We're just handing back the return types from the reducers you've passed in. Nothing about that is marked as optional, so undefined isn't usable here in strict mode.

**Comment by OliverJAsh** [comment]
Each reducer given to `combineReducers` receives `S | undefined`. Therefore, I expect the combined reducer to receive a state param type where each property may be `S | undefined`. Currently it returns a reducer where each property must be `S`.

**Comment by OliverJAsh** [comment]
FWIW this bug was already confirmed with https://github.com/reduxjs/redux/pull/2809. We just never got round to fixing it, which is why I'm raising an issue, so it be properly tracked.

**Comment by timdorr** [comment]
We actually don't want the individual reducer object keys to be undefined. We want the overall input state to be `State | undefined`. The undefined state is only for the initial reducer run to process on initialState/preloadedState. Outside of that context, you should never be passing in undefined data into the reducer, as it's always coming from within the store itself.

**Comment by OliverJAsh** [comment]
My use case was to call the reducer directly, skipping the store. This is for SSR where we don't need a store, we just need to create some (constant) for an incoming request to the server.

**Comment by Philipp91** [comment]
> We actually don't want the individual reducer object keys to be undefined

The [documentation](https://redux.js.org/recipes/structuring-reducers/initializing-state) for "Initializing State" disagrees:

> With `combineReducers()` the behavior is more nuanced. Those reducers whose state is specified in `preloadedState` will receive that state. Other reducers will receive `undefined` and because of that will fall back to the `state = ...` default argument they specify.

You also wrote:

> Outside of [the initial reducer run], you should never be passing in undefined data into the reducer, as it's always coming from within the store itself.

My use case is a little bit different, I want a redux action that deletes everything but one key in my combined reducer. So I just call the combined reducer with a newly created object `{keyToKeep: oldState.keyToKeep}` that omits all the other properties. According to that section from the documentation that should be legal. It works in practice. Just TypeScript doesn't like it because the types technically don't allow it.
