### ISSUE TITLE
should be wrapped with brackets

### ISSUE THREAD

**Issue by jzendo** [reduxjs/redux#3381]
Line: https://github.com/reduxjs/redux/blob/master/src/combineReducers.js#L39
will throw SyntaxError.

It should use brackets wrapped:
**({})**.toString.call(inputState).match(/\s([a-z|A-Z]+)/)[1]

**Comment by markerikson** [comment]
I just tried it with the following code, and this appears to work fine:

```js
const counter = (state = 0) => state;
const dummyReducer = combineReducers({ counter });
const testResult = dummyReducer(new Map(), { type: "TEST" });
```

Log output:

```
The previous state received by the reducer has unexpected type of "Map". 
Expected argument to be an object with the following keys: "counter"
```

Appreciate the report, but there doesn't seem to be an issue here.
