### ISSUE TITLE
Question about ensureCanMutateNextListeners

### ISSUE THREAD

**Issue by buoyantair** [reduxjs/redux#3386]
What kind of bugs happen if we don't use it? 
https://github.com/reduxjs/redux/blob/4fb7a44857549a3d6348933a7c542b5b7c5ad1ca/src/createStore.js#L67-L77

**Comment by timdorr** [comment]
You don't use this. It's an internal function called by subscribe to prevent the listeners from being modified during dispatch.

**Comment by buoyantair** [comment]
@timdorr I was actually asking what happens if _redux_ doesn't use it? I mean is it like some way to prevent a race condition of sorts?

**Comment by timdorr** [comment]
Yep
