### ISSUE TITLE
TypeError: items.map is not a function  React 

### ISSUE THREAD

**Issue by Belssem** [reduxjs/redux#3388]
```import React from 'react'
import { BrowserRouter as Router, Route } from 'react-router-dom';
import LoginForm from './LoginForm';
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: {},
      isLoaded: false,
    }
  }
  componentDidMount() {
    fetch(' http://127.0.0.1:8000/api/roles')
      .then(res => {return res.json();})
      .then(json => {
        this.setState({
          isLoaded: true,
          items: json,    })
      });
  }
  render() {

  const { isLoaded, items } = this.state;
    if (!isLoaded) {
      return <div>Loading...</div>
    }
    else {
      return (
        <div >
         <ul>
           {items.map( item => 
             <li key={item.id}>{item.name}</li>
           )}
         </ul>
      </div>
      )
    }
  }
}
export default App


> I got this problem when i try to fetch data from an api to react . any help plz?

**Comment by FireyFly** [comment]
This code doesn't appear to use Redux at all. I would suggest StackOverflow or a React tutorial for general React questions/debugging like this.

**Comment by piotrekdonicz** [comment]
You can't iterate over an object, as you set `items: {}`. `Object.map()` will throw you an error 'map is not a function'

**Comment by Belssem** [comment]
```import` React from 'react'
import { BrowserRouter as Router, Route } from 'react-router-dom';
import LoginForm from './LoginForm';
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: [],
      isLoaded: false,
    }
  }
  componentDidMount() {
    fetch(' http://127.0.0.1:8000/api/roles')
      .then(res =>   res.json())
      .then(json => {
        console.log(this.state.items)
        this.setState({
          isLoaded: true,
          items: json
        });
  })}
  render() {
    var { items = [] } = this.props;
    var { isLoaded } = this.state;
    if (!isLoaded) {
      return <div>Loading...</div>
    }
    else {
      return (
        <div >
         <ul>
           {items.map( item => (
             <li key={item.id}> Name : {item.name}</li>
           ))}
         </ul>
      </div>
      )
    }
  }
}
export default App

> Now I changed it to items: [] but i got any resuls :\ the error was gone but i didn't see anything in the screen

**Comment by timdorr** [comment]
This has nothing to do with Redux.

**Comment by Luoxue-xu** [comment]
> ```js
> import React from 'react'
> import { BrowserRouter as Router, Route } from 'react-router-dom';
> import LoginForm from './LoginForm';
> class App extends React.Component {
>   constructor(props) {
>     super(props);
>     this.state = {
>       items: {},
>       isLoaded: false,
>     }
>   }
>   componentDidMount() {
>     fetch(' http://127.0.0.1:8000/api/roles')
>       .then(res => {return res.json();})
>       .then(json => {
>         this.setState({
>           isLoaded: true,
>           items: json,    })
>       });
>   }
>   render() {
> 
>   const { isLoaded, items } = this.state;
>     if (!isLoaded) {
>       return <div>Loading...</div>
>     }
>     else {
>       return (
>         <div >
>          <ul>
>            {items.map( item => 
>              <li key={item.id}>{item.name}</li>
>            )}
>          </ul>
>       </div>
>       )
>     }
>   }
> }
> export default App
> ```
> 
> I got this problem when i try to fetch data from an api to react . any help plz?

you can try `React.Children.map` .[https://reactjs.org/docs/react-api.html#reactchildrenmap](#reactchildrenmap)
