### ISSUE TITLE
Discussion: throw debug errors only in developer mode

### ISSUE THREAD

**Issue by mad-gooze** [reduxjs/redux#3391]
Redux has a lot of debug checks that are intendent for developers like [this checks in `dispatch()`](https://github.com/reduxjs/redux/blob/master/src/createStore.js#L185).

This checks are mostly useless in production mode. In think redux can adopt the idea of `prop-types` and do this checks only in development mode (by wrapping them in `process.env.NODE_ENV` check so they are removed in production build).

I've made some changes (just commented out all error checks to remove this code from build) to see how it affects production bundle.
Current size of `redux.min.js`: 6440B (2396B with zopfli)
With error checks removed: 3528B (1487B with zopfli)

So removing this code in production build gives almost 2x decrease of bundle size.

The drawback is that this will break backward compatibility (I don't really think someone relies on this behaviour but anyway).

**Comment by timdorr** [comment]
Dan has said why this is the case before: https://github.com/reduxjs/redux/issues/771#issuecomment-142259143

> > Why in this project huge checks doesn't wrap into if(process.env.NODE_ENV...)

> These checks actually throw exceptions. They're not just warnings. If they were wrapped in if (...), then production and development behavior would differ, which is bad. If developer misses a problem and the problem makes it into production, it will eventually throw (because sanity checks actually check for important mistakes that will cause errors in production), but in a different place. You'll have weird stack traces that you can't possibly reproduce in development. For these reasons, if some behavior throws, it has to throw both in development and production.

I think to restate Dan's point, those aren't just "checks for developers", they are fundamental behaviors of Redux. We detected an error and will throw accordingly. That's not a developer-only concern; it matters in production as well.

**Comment by mad-gooze** [comment]
Ok, the other idea is to use minified errors like react does
https://reactjs.org/docs/error-decoder.html/

**Comment by mad-gooze** [comment]
> If developer misses a problem and the problem makes it into production, it will eventually throw (because sanity checks actually check for important mistakes that will cause errors in production), but in a different place. 

The same thing is also correct for prop-types checks - but they are disabled for production to minify the build. I don't really see big difference here.

**Comment by mad-gooze** [comment]
Removing errors also greatly affects performance
```javascript
function counter(state, action) {
  if (typeof state === 'undefined') {
    return 0
  }

  switch (action.type) {
    case 'INCREMENT':
      return state + 1
    case 'DECREMENT':
      return state - 1
    default:
      return state
  }
}

console.time();
var store = Redux.createStore(counter)
for (let i = 0; i < 1000000; i++) {
  store.dispatch({ type: 'INCREMENT' })
  store.dispatch({ type: 'INCREMENT' })
  store.dispatch({ type: 'DECREMENT' })
}
console.timeEnd();
```
version from master runs this code for **350ms**
version with removed error logging runs this code for **20ms**

**Comment by markerikson** [comment]
@mad-gooze : I would find it very surprising for error checks to affect behavior that much.

Thus far, you haven't actually shown which code you've even changed.  If you can put together a fork of the Redux repo that shows exactly what you're changing and a benchmarks repo that demonstrates the differences, I can maybe glance at it briefly.  But, I generally agree with Tim on this one.

**Comment by timdorr** [comment]
The benchmark there is a red herring anyways. As we discussed when last changing isPlainObject, dispatch isn't really the bottleneck. It's the subscribers that contain the bulk of the work, typically a UI update with something like React.
