### ISSUE TITLE
counter-vanilla example doesn't work in codesandbox

### ISSUE THREAD

**Issue by harshan007** [reduxjs/redux#3396]
**What is the current behavior?**

https://redux.js.org/introduction/examples#counter-vanilla
doesn't work. Atleast in Chrome.

**What is the expected behavior?**

Counter should work but it doesn't.

**Comment by matthewhartman** [comment]
Hey Harshan,

Can you please specify your operating system and  Google Chrome version that you are testing with.

Cheers.

**Comment by timdorr** [comment]
I think it was an issue with codesandbox. It's working on my end now.

**Comment by markerikson** [comment]
Yep, CodeSandbox bug that's been fixed, because @CompuIves is awesome :)

https://twitter.com/CompuIves/status/1114247088999682048
