### ISSUE TITLE
Empty package for Redux 4+

### ISSUE THREAD

**Issue by maurocolella** [reduxjs/redux#3397]
**_bug_**

First: thank you. For this awesome library, the docs, etc.

**What is the current behavior?**
On Manjaro Linux, possibly on a Windows 10 Pro (multi-boot), when installing any version of redux > 4, `node_modules/redux` only contains a `package.json`. No other files.

Reverting to redux `3.7.2` resolves the problem.

```
  "devDependencies": {
    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.3",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "express": "^4.13.4",
    "isomorphic-webpack": "^2.1.1",
    "node-sass": "^4.5.3",
    "node-style-loader": "^0.0.1-alpha",
    "nodemon": "^1.14.11",
    "react-hot-loader": "^4.0.1",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "url-loader": "^1.0.1",
    "webpack": "^4.5.0",
    "webpack-cli": "^3.3.0",
    "webpack-dev-middleware": "^3.1.2",
    "webpack-hot-middleware": "^2.19.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "bluebird": "^3.5.0",
    "body-parser": "^1.18.2",
    "camelize": "^1.0.0",
    "cookie-parser": "^1.4.3",
    "dotenv": "^7.0.0",
    "ejs": "^2.5.7",
    "express-session": "^1.15.6",
    "file-loader": "^3.0.1",
    "immutable": "^3.8.1",
    "isomorphic-fetch": "^2.2.1",
    "mobile-detect": "^1.4.1",
    "moment": "^2.22.0",
    "normalize.css": "^8.0.0",
    "object-hash": "^1.3.0",
    "picturefill": "^3.0.2",
    "prop-types": "^15.6.1",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-ga": "^2.5.0",
    "react-lazyload": "^2.3.0",
    "react-redux": "^6.0.1",
    "react-router-dom": "^5.0.0",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "responsive-loader": "^1.1.0",
    "session-storage-cache": "^1.0.4",
    "sharp": "^0.22.0",
    "smoothscroll-polyfill": "^0.4.0",
    "three": "^0.103.0"
  }
```
`node v.9.3.0 (with nvm)`

Installed with `npm install`. 

**What is the expected behavior?**
For redux to install with all the necessary files.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

See above. `node v.9.3.0`, `npm 5.5.1`, dependencies are installed with `npm install`. It works with `redux 3.7.2`.

**Comment by markerikson** [comment]
Appreciate the report, but I'm going to have to chalk this up to some kind of issue outside of our control, and likely only on your own machine.  The current build, 4.0.1, is clearly published correctly on NPM, and you can see the contents here:

https://unpkg.com/redux@4.0.1/

**Comment by maurocolella** [comment]
With two operating systems? 

The bug that doesn't like number 4? 

Somehow I doubt that. 

But do rest assured I will not take the time to complete a detailed bug report the next time around. *If* this had anything to do with, say, a proxy along the way, and you started seeing businesses expressing frustration, well.

I wish you patience in handling them.

**Comment by markerikson** [comment]
Sorry, I'm not trying to dismiss your problem entirely.  You're clearly seeing _something_ weird.

But, at the same time: Redux 4 has been out for months.  It's being downloaded millions of times a month.  If the published package was busted, someone would have said something immediately.

I do genuinely appreciate that you took the time to put together the bug report.  _If_ you can replicate this behavior on, say, another machine or another network, then perhaps there's something bigger going on.  But, until then, I don't see how this could be anything we can look into on our end.

**Comment by maurocolella** [comment]
Understood. For some reason, it affects both `4.0.0` and `4.0.1`, so I
genuinely believe some cache could be acting up. But agreed, if it has a
very (*very*) local effect, there probably isn't much that you could do at
this point.
