### ISSUE TITLE
A todos example using lit-element

### ISSUE THREAD

**Issue by noamraph** [reduxjs/redux#3406]
Hi,

I translated the "todos" example to use the lit-element library. Something nice about it is that it is just vanilla javascript - you can just start a simple web server from the directory and it works. It's here: https://github.com/noamraph/redux-todo-lit-element

Would you be interested in adding it to the examples directory?

Thanks,
Noam

**Comment by timdorr** [comment]
Thanks, but we're not looking to expand the examples set at this time.
