### ISSUE TITLE
Redux Connect Error (undefined is not a function: "_react.useMemo")

### ISSUE THREAD

**Issue by Gmtas** [reduxjs/redux#3421]
### Issue Description

I use wix/react-native-navigation. I want to access states in the store from a component but the following problem occurs where I do the connect process. I don't understand why I got this error. Please help...

### Steps to Reproduce / Code Snippets / Screenshots

![Screenshot_20190503-125322_EcoFarm](https://user-images.githubusercontent.com/33094523/57141272-82612b80-6dc2-11e9-8141-6edf82f8f73b.jpg)

 **Generating Recucer**
``` 
const initialState = { 
    state_1: true
};

let genReducer = (state = initialState , action) => {

    switch (action.type){
        case 'SET_STATE_1':
            return Object.assign({}, state, {state_1: action.payload.state_1});
            break;

        default:
            return state;
    }
};
export default genReducer ;
```

 **Generating Store**
```
import {combineReducers, createStore} from 'redux';
import genReducer from './genReducer ';

let combinedReducers = combineReducers({
    genReducer 
});

let Store = createStore(combinedReducers );
export default Store;
```

 **Register Component**
```
...

const createApp = (Component, ...props) => {
  return class App extends React.Component<TProps> {
    render() {
      return (
        <Provider store={store}> 
            <Component {...props} /> 
        </Provider>
      );
    }
  }
}
Navigation.registerComponent("HOME_SCREEN", () => createApp (HomeScreen));
...
```

 **Connect; Where the error occurred**
 
```
 ...
type Props = {};
export class HomeScreen extends Component<Props> {
  render() {
    return (
      <View style={{...}}>
           ...
      </View>
    );
  }
}

const mapStateToProps = (state)=>{
    const {genReducer} = state;

    return {
        state_1: genReducer.state_1
    }
};

export default connect(mapStateToProps)(HomeScreen);

```
 

 **package.json**
```
...
 "dependencies": { 
    "react": "16.6.3",
    "react-native": "0.57.8", 
    "react-native-navigation": "^2.17.0", 
    "react-redux": "^6.0.1",
    "redux": "^4.0.1"
  }
...
```

**Comment by Yakimych** [comment]
`const {genReducer} = state;` looks suspicious. Shouldn't it be `state.state_1`?

**Comment by markerikson** [comment]
You seem to have two issues:

- Your package declares you're using `react-redux : ^6.0.1`, but you're actually using 7.x
- If you do use 7.x, you need a newer version of React and React-Native.  We require a minimum React version of 16.8.3.

**Comment by Gmtas** [comment]
which react-redux version support this react version?
