### ISSUE TITLE
[Documentation] Reducing boilerplate - createReducer example appears wrong

### ISSUE THREAD

**Issue by ScottyMJacobson** [reduxjs/redux#3424]
**Do you want to request a _feature_ or report a _bug_?**

There seems to be a bug in the documentation - in [Reducing Boilerplate - Generating Reducers](https://redux.js.org/recipes/reducing-boilerplate#generating-reducers)

**What is the current behavior?**

The docs say:

```JavaScript
export const todos = createReducer([], {
  [ActionTypes.ADD_TODO]: (state, action) => {
    const text = action.text.trim()
    return [...state, text]
  }
})
```

**What is the expected behavior?**

I'm relatively new to Redux, but I can't think of any reason why the anonymous function would return an array, so I think the docs should say:

```JavaScript
export const todos = createReducer([], {
  [ActionTypes.ADD_TODO]: (state, action) => {
    const text = action.text.trim()
    return {...state, text}
  }
})
```

**Comment by markerikson** [comment]
Appreciate the PR, but the docs are correct.  The state for this portion of the app is an array of strings, such as `["Buy milk"]`.  The initial provided state value is an empty array, and the `state` argument to each "case reducer" function will be the last returned array.  Therefore, the reducer function needs to return an array every time.

**Comment by ScottyMJacobson** [comment]
thanks @markerikson! will extra-rtfm before pull requesting from now on
