### ISSUE TITLE
Docs anchor link hover issue

### ISSUE THREAD

**Issue by pshrmn** [reduxjs/redux#3427]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

When hovering over some anchor links (the chain link icon), the content jumps. For example:

![ohno](https://user-images.githubusercontent.com/1127037/57628499-ac9faf80-755f-11e9-88a0-9f160b43b630.gif)

https://redux.js.org/api/store#getState

The issue seems to be related to the headers that use anchor tags.

```md
### <a id='getState' class='anchor'></a>[`getState()`](#getState)
```

The link's text is a link to the correct hash, but the anchor link ends up looking like this:

```
https://redux.js.org/api/store#a-id-getstate-class-anchor-a-getstate-getstate
```

**Comment by timdorr** [comment]
Might be a docusaurus issue too.

**Comment by pshrmn** [comment]
You're right, it comes from Docusaurus. Their [function for generating anchor links](https://github.com/facebook/Docusaurus/blob/1edbeecbe565cbbbc0a6e6532c7c2d0c58d78807/packages/docusaurus-1.x/lib/core/anchors.js) doesn't check if its content is a link. I opened https://github.com/facebook/Docusaurus/issues/1455.

**Comment by timdorr** [comment]
Note that we have those anchors to support older links from when we were on Gitbook, so we can't really get rid of them any time soon (it's not been that long since we switched).

**Comment by pshrmn** [comment]
Would putting empty (no text content) anchor tags with the old hash id beneath the heading work?

```markdown
### `getState()`

<a id='getState'></a>
```

**Comment by wgao19** [comment]
I might be missing the background so might be proposing something dumb here -- but it seems that removing the L34 `position: relative` on `website/static/css/custom.css` solves the problem?

So what was `position: relative` intended for in the first place? I've played around the site a bit and I'm not seeing any observable changes other than the anchors no longer jump around.

**Comment by timdorr** [comment]
Normally that's to create a parent anchor point for a child's position: absolute. The absolute position will be relative to the nearest ancestor with a defined position, including those with explicit relative positions. 

If we don't have anything absolutely positioned underneath that element, then we should be good to remove it.
