### ISSUE TITLE
[docs] The navigation of the store page looks strange

### ISSUE THREAD

**Issue by muzea** [reduxjs/redux#3435]
**Do you want to request a _feature_ or report a _bug_?**

report a bug.

**What is the current behavior?**

https://redux.js.org/api/store

![image](https://user-images.githubusercontent.com/7843281/58479269-864a5880-818a-11e9-90d3-040bc50e8a3c.png)

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/7843281/58479316-9cf0af80-818a-11e9-9ebd-2a343d8d1d7f.png)

The wording in `docs/api/Store.md` is,
```
### <a id='getState' class='anchor'></a>[`getState()`](#getState)
```
why use Hyperlink?

**Comment by timdorr** [comment]
It's not a hyperlink, it's an anchor. This is support to support old incoming links to the page. We need to apply the solution from #3427

**Comment by IAmVisco** [comment]
Despite the fact that mentioned PR is merged, problem still persists.
