### ISSUE TITLE
assertReducerShape is bundled into production builds

### ISSUE THREAD

**Issue by esprehn** [reduxjs/redux#3440]
**Do you want to request a _feature_ or report a _bug_?**

Bug.

**What is the current behavior?**

assertReducerShape is called in production as well. This was discussed here:
https://github.com/reduxjs/redux/issues/816#issuecomment-143784515

It says it shouldn't have a perf impact, but we see it in our profiles.

<img width="333" alt="assert redux cost" src="https://user-images.githubusercontent.com/415779/58829236-3e00bf80-85fc-11e9-842c-1bfe60084a25.png">

**What is the expected behavior?**

Does not call it in production, like the other asserts in that same file. This also means the code can be minified out instead of shipping that long error message to users.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

All versions.

**Comment by timdorr** [comment]
As Dan pointed out in the linked thread, it doesn't add significantly to the boot time (it is only run during the initial combineReducers call, not during dispatch) and will catch user errors cause by dev/prod mismatch. There are a number of runtime assertions in `dispatch` as well. An assertion is necessarily dev-only. We want to keep this in the prod build.

**Comment by esprehn** [comment]
It does add significantly to the boot time (contrary to what Dan said), see the attached screenshot that shows it takes 9ms in our app on average hardware.

**Comment by timdorr** [comment]
I don't agree that 9ms is significant. 

Again, that's only during the initial combineReducers call, which should only be once during the boot. You shouldn't ever be incurring that setup time, where many other things like parsing and the initial window paint will take much much longer to complete.
