### ISSUE TITLE
[Example: Todo List] - Use action type constants instead of strings

### ISSUE THREAD

**Issue by mohcinenazrhan** [reduxjs/redux#3445]
I think it’s better to encourage people using action type constants rather than string literals.
I think it would be good if we could recommend this practice by using it in the full source code of the todo application.

Why: avoid typos using actions type strings, to use constants instead, place action type constants in a separate file to hold our action type and export them, so that we can benefit of auto-completion, and use them everywhere in our app without making typos.

You can see this implementation here: https://codesandbox.io/s/todos-71gtc

If you think it is a good idea, I can submit a pull request.

**Comment by markerikson** [comment]
I don't think there's a specific need to change the example atm.  In fact, when we revamp the docs, I'm actually considering _not_ using constants in the initial tutorials to simplify things.  Thanks for the comment, though!

**Comment by mohcinenazrhan** [comment]
What has confused me is that in the **basic tutorial**, the constants are used while they aren't in the **complete source code**. Thanks
