### ISSUE TITLE
Composing middlewares

### ISSUE THREAD

**Issue by marouanekadiri** [reduxjs/redux#3457]
The applyMiddleware function does two things it chains the middlewares from the left to the right and apply it to the store.

I suggest to let the user choose the way he wants to chain his middlewares, maybe group them into a **Set of middlewares** and then chain those sets to get a composed of already composed middlewares.

Creating a function that allow users to compose his middlewares by him self would be very useful in term reusability (imagine a group of middlewares that do a lot of things and we can just import it and use it as a single middleware) and also decouple the composition of middlewares from the applyMiddleware function. 

**composeMiddlewares** is a function that takes a group of middlewares and compose them to get a singled composed middleware.

**Example:**
Let's say we have middlewares A, B, C, D & E. With the applyMiddleware function we can chain those middlewares in the order specified as each middleware is seen as a standalone middleware. But what if middlewares A, B, C shares a specific semantic and we want them to be always attached together in the respective order. Well **composeMiddleware** saves your life, you can compose your middlewares and use the result as a composed middleware `const abc = composeMiddleware(A,B,C)`. The middleware abc can be moved in different orders with the D & E middleware in the applyMiddleware function like this `applyMiddleware(abc, D, E)` <=> `applyMiddleware(A, B, C, D, E)` or `applyMiddleware(D, abc, E)` <=> `applyMiddleware(D, A, B, C, E)`.

**Comment by markerikson** [comment]
Appreciate the PR, but I don't see a need to add this to the core.  If someone wants to customize middleware setup, they're welcome to copy-paste the `applyMiddleware` source and modify it to suit their needs.  For that matter, I don't see how there's any difference between passing one of those "composed" middleware to `applyMiddleware`, and just doing `applyMiddleware(d, a, b, c, e)`.

**Comment by marouanekadiri** [comment]
@markerikson Yeah, if you see it from the perspective of the user handling his middlewares, it's the same as using applyMiddleware. But if i want to create a library that uses bunch of middleware in the order i want and expose it to my users so they can use it in their setup. Then, I see a use case for this.
