### ISSUE TITLE
Discussion: References to Flux

### ISSUE THREAD

**Issue by mplis** [reduxjs/redux#3464]
I'm wondering if comparisons to Flux in the core documentation (aka anything except [Prior Art](https://redux.js.org/introduction/prior-art)) are that helpful anymore. I doubt that most new Redux users are familiar with Flux, so the comparisons might do more harm than good at this point.

For example, on the [Actions page of the Basic Tutorial](https://redux.js.org/basics/actions), it mentions that in Flux, action creators typically dispatch the action when invoked. At best, this provides no value to people not familiar with Flux and at worst, it might be confusing.

I think that section could at least be put in a "note", similar to what's done on the [Store API](https://redux.js.org/api/store#a-note-for-flux-users) page and I'd question whether it really needs to be in there at all.

**Comment by markerikson** [comment]
Yep, on my list of things to change in the docs rewrite.  See #3313 .
