### ISSUE TITLE
"Invalid descriptor for property 'dispatch'" in IE11

### ISSUE THREAD

**Issue by lid2000** [reduxjs/redux#3468]
**Do you want to request a _feature_ or report a _bug_?**

Bug.

**What is the current behavior?**

With Redux 4.0.2 and up, IE11 throws up an error on load of "Invalid descriptor for property 'dispatch'." The script debugger flags 570,9 in redux.js as the source of the error (which appears to be inside the _objectSpread2(target) function. I don't think this is the source of the error itself as that function exists within previous versions of Redux and seems unchanged between versions. Redux 4.0.1 works fine and does not have this issue.

**What is the expected behavior?**

Redux works normally as expected.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

4.0.2 and 4.0.3 running in IE11 on Windows 10. No other browser seems to be affected. Previous versions (4.0.1 being the most recent) worked.

**Comment by markerikson** [comment]
Possibly related to this Babel issue?

https://github.com/babel/babel/pull/10170

Also, someone just raised a vaguely similar issue with Redux Starter Kit:

https://github.com/reduxjs/redux-starter-kit/issues/152

**Comment by lid2000** [comment]
I think it probably is. Guessing the versions of 4.0.2 and 4.0.3 currently on npm were built when those bugs were live in Babel.

**Comment by fdwcomune** [comment]
Possibly related issue on [react-native](https://github.com/facebook/react-native/issues/25563)

**Comment by f-roland** [comment]
We ran into this issue today as well. reverting to `redux@4.0.0` fixed the issue for us on react-native 0.57.5

**Comment by wieringen** [comment]
I experience the same problem with "redux": "^4.0.1"

**Comment by f-roland** [comment]
@wieringen check in your lock file - you probably upgraded without knowing it to `4.0.2` or `4.0.3`
removing the carret in your package json will make sure it doesn't pull the failing minor update

**Comment by wieringen** [comment]
Ahh yes you are right. :)

**Comment by akashuba** [comment]
Same issue with native browsers on android 5.

**Comment by timdorr** [comment]
Looks like they just fixed it yesterday: https://github.com/babel/babel/releases/tag/v7.5.4

I can push a 4.0.4 (error not found?) release using Babel 7.5.4.

**Comment by timdorr** [comment]
Pushed out 4.0.4 now. Thanks for letting us know!
