### ISSUE TITLE
Adding [Symbol.observable] to Observable interface is an in-range breaking change.

### ISSUE THREAD

**Issue by trusktr** [reduxjs/redux#3473]
This causes problems like the following in existing projects:

```
node_modules/typedux/dist/store/ObservableStore.d.ts:15:22 - error TS2420: Class 'ObservableStore<S>' incorrectly implements interface 'Store<S, AnyAction>'.
  Property '[Symbol.observable]' is missing in type 'ObservableStore<S>' but required in type 'Store<S, AnyAction>'.

15 export declare class ObservableStore<S extends TRootState> implements Store<S> {
                        ~~~~~~~~~~~~~~~

  node_modules/typedux/node_modules/redux/index.d.ts:247:3
    247   [Symbol.observable](): Observable<S>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.observable]' is declared here.
```

**Comment by trusktr** [comment]
in my particular case, I can set `skipLibCheck` to `false` in `tsconfig.json` to work around the problem, but if I go into the `typedux` project directly then there will be the issue.

**Comment by trusktr** [comment]
Correction, I meant, set `skipLibCheck` to `true`.

**Comment by markerikson** [comment]
*sigh*

And this is why I said the other day that I rather wish we _didn't_ ship our own typings.

**Comment by timdorr** [comment]
This was always [being put on the store](https://github.com/reduxjs/redux/blob/master/src/createStore.js#L291), but was incorrectly left out of the typings. I'm sorry if this breaks your particular use case, but the typings are correct and you should definitely be adding that to correctly implement a Observable.
