### ISSUE TITLE
when composing enhancers don't crash redux if one enhancer is undefined

### ISSUE THREAD

**Issue by croraf** [reduxjs/redux#3477]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

For example when "Redux devtools" are not installed in the browser this code:

```
const enhancers = compose(
    applyMiddleware(thunk), 
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

const store = createStore(
  reducers,
   /* preloadedState, */
   enhancers,
);
```

crashes redux with `Uncaught TypeError: Cannot read property 'apply' of undefined`, because second argument to compose (second enhancer) is undefined.

**What is the expected behavior?**

Would be good if some enhancer is undefined not to crash, but to continue to operate as if this argument was not provided to compose. 
(Not sure if this means the change of `compose` or the change of `createStore`)

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux version: 4.0.1
OS+Browser: Windows 10 + Chrome 75, Ubuntu 18 + Chrome 75, Windows 10 + IE

**Comment by timdorr** [comment]
We actually specifically removed this way back in #2167. The determination was it is better to fail than to silently continue to execute. We want to know when the store configuration isn't what we expect.

**Comment by croraf** [comment]
@timdorr OK. 

From what I see compose is allowed to have undefined as an argument. The application should fail at this point saying "an argument is not a function" or something? I think this was the intention of  #2167 ?

Where the application fails is during `createStore`. And it fails with a non helpful error "Cannot read property 'apply' of undefined".
