### ISSUE TITLE
State doesn't update when replaceReducers is called with combineReducers and one of the reducers passed to it is removed. 

### ISSUE THREAD

**Issue by anubhavgupta** [reduxjs/redux#3488]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
The `combineReducers` function does't detect if one of the reducers passed to it is removed(via replaceReducers) and thus returns an old state.
  
```js
// Reducers
const foo = (state = { value: 'foo' } ) => state
const bar = (state = { value: 'bar' }) => state

const ACTION = { type: 'ACTION' };

const originalCompositeReducer = combineReducers({ foo, bar })
const store = createStore(originalCompositeReducer)
store.dispatch(ACTION)


const initialState = store.getState() // returns -> { 
 //                                                   foo: { value: 'foo' }, 
 //                                                   bar: { value: 'bar' } 
 //                                                }

// now remove `foo` reducer
store.replaceReducer(combineReducers({ bar }))
const nextState = store.getState() // returns -> { 
//                                                 foo: { value: 'foo' }, 
//                                                 bar: { value: 'bar' } 
//                                                }
//                      should have returned -> { bar: { value: 'bar' } }
expect(nextState).not.toBe(initialState) // --> this fails
```

Steps to reproduce: 
Open [JSFiddle Link](https://jsfiddle.net/f5er907y/2/):
1) Click "Dispatch action" button
-> 2 boxes gets rendered,  one of `foo` and other of `bar`. 
2) Click "Replace Reducer: remove `bar` reducer" button
-> Again, 2 boxes gets rendered,  one of `foo` and other of `bar`. 
**Expected**: Only one box should render, i.e. box of `bar` only.

**What is the expected behavior?**
The `combineReducers` function should detect if one or more reducers passed to it is removed(via replaceReducers) and thus should update the store with new state.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux Version: V4.0.4
OS: MAC
Worked on previous versions: no.

**Comment by anubhavgupta** [comment]
Raised a PR which will fix this issue.

**Comment by lileilei** [comment]
```
test
redux@4.0.4
onClick={e=>{ 
      store.replaceReducer(combineReducers({ bar }))
 }}
 it didn't work！！

---------------------
redux@3.7.2  
is
success ！

**Comment by markerikson** [comment]
Given that #3488 has been merged, this can be closed.
