### ISSUE TITLE
store.replaceReducer is not a function in middleware

### ISSUE THREAD

**Issue by MatteoGioioso** [reduxjs/redux#3502]
**Do you want to request a _feature_ or report a _bug_?**
Bug or feature

**What is the current behavior?**
When I access the store in the middleware and call `replaceReducer` I got this error
```
TypeError: store.replaceReducer is not a function
``` 
I can call `replaceReducer` at component level but not in a middleware

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

```
export const asyncReducerInjectorMiddleware = store => next => action => {
    store.asyncReducers = {}
    store.asyncReducers['myReducerName'] = asyncReducer;
    store.replaceReducer(createReducer(store.asyncReducers));
   next(action);
};
```

**What is the expected behavior?**
It should be able to call `replaceReducer` inside a middleware, or there is a reason why this is not working?

Thanks

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
`"redux": "^4.0.1"`

**Comment by mhelmer** [comment]
From the [API docs of `applyMiddleware`](https://redux.js.org/api/applymiddleware#arguments):

> `...middleware` (_arguments_): Functions that conform to the Redux _middleware API_. Each middleware receives [`Store`](Store.md)'s [`dispatch`](Store.md#dispatchaction) and [`getState`](Store.md#getState) functions as named arguments, and returns a function. 

So the middleware will not receive the entire store, and you probably wouldn't want to mutate the store and call `replaceReducer` inside a middleware anyway since that would run on every dispatch.

You could do this setup in your  `configureStore` function. If you really need it to be reusable you could do it in a store enhancer.

**Comment by MatteoGioioso** [comment]
@mhelmer Thanks for the answer.
Unfortunately in my use case I need to access `replaceReducer` in the middleware. 

>  you probably wouldn't want to mutate the store and call replaceReducer inside a middleware anyway since that would run on every dispatch

No, of course I will conditionally check, that was just an example.

**Comment by kevinpeno** [comment]
Can we reconsider this? There are other user generated `StoreEnhancer`s that make sense to be accessed via middleware that do not effect state. As it stands right now **only** `dispatch` and `getState` are available and that makes this very inflexible.

I get that you are trying to prevent the user from shooting themselves in the foot, but maybe pop a warning for dangerous built-ins when they are called instead?
