### ISSUE TITLE
Question: boilerplate and predictability

### ISSUE THREAD

**Issue by MarcoPal** [reduxjs/redux#3526]
Hi, after a few months of working with redux, I got an idea that I would like to share.
I built a small function which produces an object containing action types and action creators, where the action creators names are the action types in camelCase, and the action arguments are defined as array of keys.

A simple example:
```
export const counter = createActions({
  COUNTER_INCREMENT: [],
  COUNTER_DECREMENT: [],
  COUNTER_ADD      : ["value"]
});
```
now the content of **counter** is the following object

```
{

  actionTypes: {

    COUNTER_INCREMENT : "COUNTER_INCREMENT",
    COUNTER_DECREMENT : "COUNTER_DECREMENT",
    COUNTER_ADD       : "COUNTER_ADD"

  },

  actions    : {

    counterIncrement: () => ({
      type: 'COUNTER_INCREMENT'
    }),

    counterDecrement: () => ({
      type: 'COUNTER_DECREMENT'
    }),

    counterAdd      : (value) => ({
      type : 'COUNTER_ADD',
      value: value
    })

  }
}

```

so i can use it in a reducer:

```
case counter.actionTypes.COUNTER_INCREMENT:
  ...
case: counter.actionTypes.COUNTER_DECREMENT:
  ...
case: counter.actionTypes.COUNTER_ADD:
  ...
```

and in a component
```
dispatch( counter.actions.counterIncrement() );
dispatch( counter.actions.counterDecrement() );
dispatch( counter.actions.counterAdd(5) );
```

This approach drastically reduces the redux boilerplate,
but the question is, it also breaks the predictable definition of redux?

**Comment by timdorr** [comment]
Nope, that's fine. There's actually already a package that does this for you: https://github.com/redux-utilities/redux-actions

**Comment by markerikson** [comment]
Or, even better, our [official Redux Starter Kit package](https://redux-starter-kit.js.org).
