### ISSUE TITLE
Broken link in the docs, section 'Learning resources'

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [reduxjs/redux#3562]
There's a broken link in this page of the docs: https://redux.js.org/introduction/learning-resources

The broken link is: https://www.pshrmn.com/tutorials/react/redux/

I don't see any tutorial now in https://www.pshrmn.com (otherwise I'd open a pull request)

**Comment by AlbertVilaCalvo** [comment]
That's how it looked like in the past: https://web.archive.org/web/20170425122319/http://www.pshrmn.com/tutorials/react/redux/

**Comment by markerikson** [comment]
Hmm.  Thanks for the pointer.  I pinged the author to see what's up with that.
