### ISSUE TITLE
1 critical vulnerability, 16303 high vulnerabilities

### ISSUE THREAD

**Issue by AnandarajT** [reduxjs/redux#3572]
I just used npm install in the counter example. After installing the packages npm reported many vulnerabilities.

I don't know the threat these vulnerabilities pose. Please fix them so unaware users will be safe when running the examples.

I haven't checked other examples so check them and fix if any vulnerability found

**Comment by markerikson** [comment]
NPM is considerably over-zealous.  The vast majority of those warnings are irrelevant for typical build tools.  Appreciate the comment, but there's not likely to be any real problems for users installing the examples.

If you'd like to file some PRs that do update some of the dependency versions for the examples, we can get those merged in.
