### ISSUE TITLE
Allow getState in reducer

### ISSUE THREAD

**Issue by 4-1-1** [reduxjs/redux#3573]
Here is a demo scene.

```js
const repoFile = (state = {}, {type, payload}) => {
    switch (type) {
        case uiAction.route.type: {
            if (REPO.FILE.REF.path === payload.path) {
                const topState = getStore().getState();
                const basic = getBasics(topState);
                if(basic.defaultBranch===payload.params.ref){
                         return state;
                 }
                return payload.params;
            }
            return state;
        }
        default:
            return state;
    }
};

```

I don't get the reason to forbid getState() in reducers.
I have read the source code.

```js
function getState(): S {
    if (isDispatching) {
      throw new Error(
        'You may not call store.getState() while the reducer is executing. ' +
          'The reducer has already received the state as an argument. ' +
          'Pass it down from the top reducer instead of reading it from the store.'
      )
    }

    return currentState as S
  }

```
If I can't getState . I must to write  a lot action to do this.

**Comment by nickmccurdy** [comment]
If your reducers used the entire store's state, their isolation would break, and they wouldn't be reusable. Making sure your reducers are in the right shape is easier than worrying about changing your reducers when you compose them differently.

**Comment by 4-1-1** [comment]
> If your reducers used the entire store's state, their isolation would break, and they wouldn't be reusable. Making sure your reducers are in the right shape is easier than worrying about changing your reducers when you compose them differently.

sorry, I never reuse reducer , and it would to be ok to composed them 
I can't imagine what problem would to be worried

**Comment by ematipico** [comment]
You can solve your problem using a middleware. Inside your middleware you can check the action, read the store and fire additional actions based on some custom logic.

**Comment by nickmccurdy** [comment]
Redux's suggestion is still the best: Use the reducer's state slice from its first argument. If that doesn't have the state you need, you should reorganize your reducer code so each reducer has access to the right state.

**Comment by 4-1-1** [comment]
> You can solve your problem using a middleware. Inside your middleware you can check the action, read the store and fire additional actions based on some custom logic.

I just think , It's unnecessary to limit us to do this things.
And It's easier for me to use getState . 
If It's not ok, I guess I prefer to write some actions .
I am afraid a middleware make app slow. This action is sent when route mounted.

**Comment by 4-1-1** [comment]
> Redux's suggestion is still the best: Use the reducer's state slice from its first argument. If that doesn't have the state you need, you should reorganize your reducer code so each reducer has access to the right state.

When I need to access the entire store, My first sense tell me, there  is a third parameter  pass to reducer . Finally, It's totally forbid . 
Anyway I think It should be more freely . make code fly

**Comment by ematipico** [comment]
> I am afraid a middleware make app slow. 

It won't, don't worry 😉 Personal experience

**Comment by markerikson** [comment]
No, calling `getState` in a reducer is _not_ allowed.

Please see [the Redux FAQ entry on how to "share state between slices"](https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers) for suggestions.
