### ISSUE TITLE
Can we store event in the redux?

### ISSUE THREAD

**Issue by JAISAIKIRANALLURI** [reduxjs/redux#3574]
Hi,

I'm trying to store a event which contains html graphic element in the redux store. When I'm dispatching the action, I can see the element in the reducer, but when I'm trying the get the state from store through reducer,I can see that element is losing all the properties. I'm curious to know, whether it can be done?
![Image1 redux](https://user-images.githubusercontent.com/30841604/65273231-48f54680-db3e-11e9-9381-5e00e8297f1d.PNG)
![image2redux](https://user-images.githubusercontent.com/30841604/65273247-55799f00-db3e-11e9-9eb3-5ad73ad1763e.PNG)

**Comment by markerikson** [comment]
Please only store serializable values in Redux:

https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state
