### ISSUE TITLE
All api documentation is reload loop

### ISSUE THREAD

**Issue by higimo** [reduxjs/redux#3575]
https://redux.js.org/api/api-reference

![image](https://user-images.githubusercontent.com/2804205/65536437-11a2e300-df0c-11e9-9804-2eda16d9bf94.png)

**Comment by markerikson** [comment]
The `https://redux.js.org` site is working.  Whatever issue you're seeing must be somewhere on a network path between you and the site.

**Comment by higimo** [comment]
now site is working.

**Comment by markerikson** [comment]
Looks like this was due to a Netlify redirect issue:

https://www.netlifystatus.com/incidents/s37rb933prc3
