### ISSUE TITLE
Discussion: bindActionCreators currying

### ISSUE THREAD

**Issue by arkafon** [reduxjs/redux#3576]
Hello!
It's pretty common pattern to use **bindActionCreators** for _mapDispatchToProps_ in simple way:
```
const mapDispatchToProps = dispatch => 
  bindActionCreators({ action1, action2 }, dispatch);
```
It may be shorter in some simple cases if **bindActionCreators** could return function for implicit dispatch applying like this:
```
const mapDispatchToProps = 
  bindActionCreators({ action1, action2 }); // returns (dispatch) => ...
```
Of course you have to accept that _ownProps_ are not accessible in this simple case and if you need it you can use _bac_ in standart way.

**Comment by nickmccurdy** [comment]
I believe in your use case it's best to use the object form:

```js
const mapDispatchToProps = { action1, action2 };
```

**Comment by arkafon** [comment]
> I believe in your use case it's best to use the object form:
> 
> ```js
> const mapDispatchToProps = { action1, action2 };
> ```
> 
> Also it seems like your examples are using `mapStateToProps` rather than `mapDispatchToProps`.

Thanks for pointing on my typo  :)

Also thanks for advice. It's funny, but i've known about object shorthand syntax in react-redux already.
