### ISSUE TITLE
RxJS.from(Redux.createStore(reducer)) occurs Type Error

### ISSUE THREAD

**Issue by yuta0801** [reduxjs/redux#3586]
**Do you want to request a _feature_ or report a _bug_?**

Issue, but I don't know is it a Redux or RxJS issue

**What is the current behavior?**

Type error occurs at `RxJS.from(Redux.createStore(reducer))`

```
index.ts:6:21 - error TS2345: Argument of type 'Store<unknown, Action<any>>' is not assignable to parameter of type 'ObservableInput<any>'.
  Type 'Store<unknown, Action<any>>' is not assignable to type 'Subscribable<any>'.
    Types of property 'subscribe' are incompatible.
      Type '(listener: () => void) => Unsubscribe' is not assignable to type '{ (observer?: PartialObserver<any>): Unsubscribable; (next: null, error: null, complete: () => void): Unsubscribable; (next: null, error: (error: any) => void, complete?: () => void): Unsubscribable; (next: (value: any) => void, error: null, complete: () => void): Unsubscribable; (next?: (value: any) => void, error?...'.
        Types of parameters 'listener' and 'observer' are incompatible.
          Type 'PartialObserver<any>' is not assignable to type '() => void'.
            Type 'NextObserver<any>' is not assignable to type '() => void'.
              Type 'NextObserver<any>' provides no match for the signature '(): void'.

6 const state$ = from(store)
                      ~~~~~
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

https://codesandbox.io/s/github/yuta0801/redux-rxjs-from-typeerror

**What is the expected behavior?**

No Type error occurs

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

```
redux: 4.0.4
rxjs: 6.5.3
typescript: 3.6.4
```

**Comment by timdorr** [comment]
The store is already an Observable (it implements Symbol.observable), so you can use it with RxJS functions without converting it with `from`.

**Comment by yuta0801** [comment]
How can I use it with RxJS functions?

I tried it, but error occurred:
```ts
// common obserbable
import { of } from 'rxjs'
import { map } from 'rxjs/operators'

of(1).pipe(map(v => v))
of(1).subscribe({
  next: value => console.log(value)
})

// redux store
const store = createStore(reducers)

// that makes sense.
// redux store has subscribe method different from rxjs
store.subscribe({
  next: value => console.log(value)
  // type error here
})

// no method exists..
store.pipe(map(v => v))
```

**Comment by yuta0801** [comment]
@timdorr What should I do

**Comment by yuta0801** [comment]
OK, it seems type declaration issue in index.d.ts that is in the latest version 4.0.4 published on npm and not in master now

https://github.com/reduxjs/redux/blob/9b70f1c3138d46b7d16166b7bb9b211b8099823e/index.d.ts#L238

And [fixed](https://github.com/reduxjs/redux/commit/9b70f1c3138d46b7d16166b7bb9b211b8099823e#diff-6211333314dc7d3dd7ddc7768d98ed87R290) in the process of converting to TypeScript in #3533

But these changes are not yet published on npm..
Is there a schedule for publishing the next version?

**Comment by tbuschto** [comment]
"from(reduxStore)" used to work for me in an older project, but using redux 4.0.5 with rxjs 6.5.5 and TypeScript 3.8.3 it won't work as @yuta0801 described.

> The store is already an Observable (it implements Symbol.observable), so you can use it with RxJS functions without converting it with `from`.

It has no "pipe"  method though, so it seems like a legit issue to me @timdorr
