### ISSUE TITLE
How to test redux with hooks

### ISSUE THREAD

**Issue by idangozlan** [reduxjs/redux#3589]
Hi,

I can't see any information regarding how to test "connected" components with redux hooks and not wrapping component. is there any way to do it today?

Thanks

**Comment by markerikson** [comment]
You'd need to render a Provider component with a valid store around your component in a test.

**Comment by idangozlan** [comment]
Well, it's a little bit problematic with Enzyme, can you please take a look here?
https://github.com/airbnb/enzyme/issues/2202

**Comment by nickmccurdy** [comment]
Enzyme typically falls behind on support for testing modern React features. If you'd like to use hooks, I'd recommend [react-testing-library](https://github.com/kentcdodds/react-testing-library).
