### ISSUE TITLE
storify link in docs, section learning resources, is broken

### ISSUE THREAD

**Issue by cchanxzy** [reduxjs/redux#3605]
A storify link in the docs: [learning resources](https://redux.js.org/introduction/learning-resources#learning-resources) is dead.

Broken link: https://storify.com/acemarke/redux-pros-cons-and-limitations

**Comment by markerikson** [comment]
Hah.  Yeah, Storify died a couple years ago, and I don't even remember what that tweet thread was about or if I exported the Storified version.

**Comment by r3dm1ke** [comment]
This was fixed in [3619](https://github.com/reduxjs/redux/pull/3619), can someone close it?
