### ISSUE TITLE
DeepPartial does not work without strictNullChecks enabled

### ISSUE THREAD

**Issue by jfirebaugh** [reduxjs/redux#3612]
**Do you want to request a _feature_ or report a _bug_?**

Report a bug.

[Example code](https://www.typescriptlang.org/play/index.html?strictNullChecks=false&ssl=1&ssc=1&pln=10&pc=1#code/JYWwDg9gTgLgBAbzgYygUwIYzQZRtNOAXzgDMoIQ4BydAEwFcAPagKFZgE8xC8tCAvIlZw4GAFxwAzjCjAAdgHMRcAEaT5DADZbWRdnTTItGdGQbzkMYBHlx6DZGigAKGfwD8kvtgCU3mH4AbnZkWxk4BWBrDC0fNAD+OCEkCRpSCAhqABo1DW0tYlZUTGw8AhcHJyhcqJi4wL9WIA):

```
import { createStore } from 'redux'

type State = {
  a: string
  b: null
}

declare function reducer(state?: State): State;

const initialState: State = { a: 'foo', b: null }
createStore(reducer, initialState)
```

**What is the current behavior?**

If `strictNullChecks` compiler option is not enabled, this produces:

```
 error TS2769: No overload matches this call.
  Overload 1 of 2, '(reducer: Reducer<State, Action<any>>, enhancer?: StoreEnhancer<unknown, unknown>): Store<State, Action<any>>', gave the following error.
    Argument of type 'State' is not assignable to parameter of type 'StoreEnhancer<unknown, unknown>'.
      Type 'State' provides no match for the signature '(next: StoreEnhancerStoreCreator<{}, {}>): StoreEnhancerStoreCreator<unknown, unknown>'.
  Overload 2 of 2, '(reducer: Reducer<State, Action<any>>, preloadedState?: DeepPartial<State>, enhancer?: StoreEnhancer<unknown, {}>): Store<...>', gave the following error.
    Argument of type 'State' is not assignable to parameter of type 'DeepPartial<State>'.
      Types of property 'b' are incompatible.
        Type 'null' is not assignable to type 'never'.
```

**What is the expected behavior?**

Type checks successfully.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Redux 4.0.4, Typescript 3.7.2. It worked in 3.x versions of Redux (because they didn't use `DeepPartial`).

**Comment by jfirebaugh** [comment]
It works if I change the definition of `DeepPartial` to:

```ts
export type DeepPartial<T> = {
  [K in keyof T]?:
    T[K] extends null ? null :
    T[K] extends object ? DeepPartial<T[K]> : T[K]
}
```

**Comment by timdorr** [comment]
We've already removed this during the TS conversion, so this will be implicitly "fixed" in the next release.
