### ISSUE TITLE
[Docs Rewrite] Meta-Issue: Redux Toolkit section

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3614]
This is a tracking issue to cover all work related to adding a miniature version of the RTK docs to the Redux core docs.

## Concept

The idea is to specifically document RTK within the core Redux docs, in the same way that we have information on using React-Redux in the core.  First suggested here: https://github.com/reduxjs/redux-starter-kit/issues/246#issuecomment-552700922 .

For simplicity, I think we should probably just copy-paste most or all of the API docs and the "Usage Guide" page, but not the tutorials.  We can point to the main RTK docs site for those.  Or, perhaps we could have sidebar links that just point directly to the RTK docs pages.  Some of that may require waiting for an upgrade to Docusaurus v2.

## Tasks

- [x] Determine which portions of the RTK content should be available in the Redux core docs
- [x] Determine approach for copying or linking content
- [x] Add content

**Comment by markerikson** [comment]
Paging the Docusaurus folks: @wgao19 , @endiliey , @yangshun . 

Can we add external links to the sidebar in DS v1, or just in v2?

**Comment by yangshun** [comment]
Hmm I don't think so. @endiliey could we backport this feature? Since it's available in v2 and the API is the same.

**Comment by endiliey** [comment]
Sorry but I think adding this to v1 back isnt that easy, although lot of API in v2 stays the same, the underlying code is very different (its a re-write after all). I am hesitant to add it back to v1 since there’s no tests in v1 on that part and it could cause regression. (In v2 we have 100% test coverage on docs functionality so regression is harder).

**Comment by markerikson** [comment]
Okay.  Maybe for now we should just have a small section with an "Overview" page, and link to the RTK docs pages from that page.

**Comment by markerikson** [comment]
Settled on just adding an "Overview" page for now that reuses some of the text from the RTK "Getting Started" page to describe what RTK is and why you should use it.  I added links to the individual RTK API reference pages at the bottom.

That should suffice for now.
