### ISSUE TITLE
official way to support modular architecture with clear boundaries

### ISSUE THREAD

**Issue by alzalabany** [reduxjs/redux#3637]
### Problem:
Following flux pattern in courageous separation of business logic from ui, sounds great -in theory- .

For years I structured my project into separate packages 

1. SDK : Redux logic (biz logic)
2. UI.   : views that consume sdk as black box emitting events uni-directionally and listen to state change using HOC or hooks  

Main concern that

1. now I find my self building a monolithic sdk , I no longer capable for modularity
2. A single broken reducer in tree of reducers I’m capable of taking entire system down (no boundaries)
3. Adding/disabling a module mean entire state tree shape change
4.  lazy loading slices are problematic at least, definitely not guaranteed. 

### Who is the intended target audience?
Architects

### What are the intended results or takeaways from reading this page?

Define a methodology for multi package app structure with clear boundaries between modules yet still within flux proposal

**Comment by markerikson** [comment]
We've just added a somewhat broad suggestion on folder structures as part of our "Style Guide" docs page:

https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks

We also do plan on having some discussions on folder structures as part of the docs rewrite.

If you have specific suggestions beyond that, please let us know.
