### ISSUE TITLE
[Docs Rewrite] The dispatch() store method example

### ISSUE THREAD

**Issue by wale-bant** [reduxjs/redux#3645]
## What docs page needs to be fixed?

- **Section**: API Reference
- **Page**: Store

## What is the problem?
In the example of the dispatch(action) store method, the addTodo function which takes in a text parameter returns an object.
Object consist of key, value pairs. However, the second item in the retun object does not follow this rule. The function is written as bellow:
![dispatch](https://user-images.githubusercontent.com/47564977/69963882-133ee780-1509-11ea-90e0-0dad286d7558.png)

## What should be changed to fix the problem?
To fix this, the addTodo function should be re-written as:

```
function addTodo(text) {
  return {
    type: 'ADD_TODO',
    text: text
  }
}
```
This way the "text" key is assigned the value of the "text" parameter.

**Comment by wale-bant** [comment]
Shoud i go ahead and fork the repo to correct this mistake?

**Comment by wale-bant** [comment]
I submitted a PR already #3646

**Comment by timdorr** [comment]
This is correct as-is. It's the object property shorthand syntax introduced in ES2015: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
