### ISSUE TITLE
Investigate creating a CRA template package

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3650]
CRA 3.3.0 introduced project templates:

- https://github.com/facebook/create-react-app/releases/tag/v3.3.0
- https://create-react-app.dev/docs/custom-templates/

Based on that information, we should be able to define a `cra-template-redux` package that sets up Redux Toolkit and React-Redux automatically, in the same way that CRA's default template sets up React automatically.

This would make it even easier to get started with Redux.

**Comment by BenLorantfy** [comment]
I can give this a go. One question; do we want both a JS template and a TS template?

**Comment by BenLorantfy** [comment]
Here's my attempt: https://github.com/BenLorantfy/cra-template-redux-test

You can try it out with `yarn create react-app my-app --template redux-test`

Not sure how opinionated we should be / what opinions we should bake into the template. (e.g. file structure, store structure, etc). Also not sure how complicated the example redux code should be. The counter example I added might be too simple.

**Comment by nickmccurdy** [comment]
> I can give this a go. One question; do we want both a JS template and a TS template?

How does this currently work in CRA? Is TS support implemented as another template? If not, how does it affect the default template and can it be used with other templates?

**Comment by BenLorantfy** [comment]
They have a separate template for TS: https://github.com/facebook/create-react-app/tree/master/packages/cra-template-typescript

**Comment by DWMiller** [comment]
I'm hesitant/torn on whether or not a slice should be included. They're a useful tool, but the downsides make using one more context dependent. 

At the very least I think a createReducer example should be standard. A createSlice in addition could be good, but that then raises the question of how much template is too much template.

**Comment by markerikson** [comment]
I absolutely want a `createSlice()` usage in the template.

I'd say that `createSlice()` satisfies 98% of the use cases.  Yes, RTK includes and exposes `createReducer()` and `createAction()`, but most of the time you shouldn't even need to use those directly.

The default CRA template includes files that are there to specifically demonstrate "here's things you can do":

- `index.js`: required entry point
- `index.css`: shows you can import a CSS file into JS
- `logo.svg`: shows you can import an image
- `App.js`: shows you can have a separate component file
- `App.css`: shows you can have multiple CSS files
- `App.test.js`: shows you can write tests, and test components

In the same way, I would want to have a tiny slice in the template by default.  Doesn't have to be much more than a counter, but if it is a counter, I'd like to have the value nested inside of an object in the slice, so you end up with something like `state.counter.value`, and show that you can have a "mutating" update like `state.value += 1`.

**Comment by DWMiller** [comment]
My objection to createSlice is, unless I'm misunderstanding something about it, is the lack of option to have different reducers respond to the same actions.

The use cases it's good for are your very narrow, isolated states that you're pretty sure nothing else will ever care about. There's nothing wrong with that, but that's the context that makes me question having it as the default.

I no longer commit to using a slice upfront because half the time I ended up refactoring out of when because I didn't properly consider the need somewhere else for one of the actions, more so when trying to be proactive about treating actions as events.

And I don't mean for this to come off as anti-slice, I love the setup for them, but my experience in using them is that they need to be more of a considered choice while createReducer is an effective default. I treat slices more as optimization to tidy things up a little when my app state/events have been mostly fleshed out and I feel things have been locked down enough to get away it. 

To reiterate, I do think a simple slice example is good, I just also think a createReducer example is more useful as a starting point, and something you'd want to know even if you never used a slice, while the reverse is not true. No worries if you don't agree with that or think my perspective is less common, not going to throw a fit either way, just getting my view on my own experiences with it out there  ;)

Also not a fan of the mutating style syntax via immer, but not going to argue that one :D

**Comment by markerikson** [comment]
@DWMiller : "listening to other actions" is explicitly why we added the `extraReducers` option:

https://redux-toolkit.js.org/api/createSlice#extrareducers

So yeah, I _do_ think that `createSlice` handles almost every use case, and is the right approach.

I agree that "slices / ducks" in general [somewhat obscure the idea that other parts of the app can respond to that action, and that's always been my point of concern](https://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/#defining-actions-action-creators-and-reducers-in-separate-files).  But, historically most actions have been 1:1 with a matching reducer, and too many folks have complained about "needing to edit a dozen files to work on one feature".  Writing action creators by hand borders on pointless, `createSlice` can generate those for you, and at that point you're basically 95% of the way to having a "duck" file already.

**Comment by DWMiller** [comment]
Well, nevermind me than, I missed that addition. Off to do some reading and experiment with that.

**Comment by DWMiller** [comment]
@markerikson Quick follow up and side note, that looks great, absolutely addresses my objections. I'm also just discovering the "prepare" option, nice work with that ;)

**Comment by nickmccurdy** [comment]
I like how the generated code/app looks, though maybe we should split up the JSX in `index.js` to multiple indented files. I also agree with @markerikson here about including `createSlice`.

**Comment by nickmccurdy** [comment]
Hey @iansu, I noticed you own `cra-template-redux` on npm. Were you planning on using that for something else within CRA or would you be okay with us using it for Redux toolkit?

**Comment by iansu** [comment]
I actually grabbed it to reserve it for you before we published 3.3.0. Just let me know what account you want to be the new owner and I’ll transfer it.

**Comment by BenLorantfy** [comment]
Yeah I wasn't sure where to put `Provider`. If I put `Provider` in `App.js`, I can't use `useSelector` or `useDispatch` in App, which means I have to split up App into components, which would make the code a little less simple.

So I put it index.js, but not sure if that's the best spot?

**Comment by markerikson** [comment]
`<Provider>` should generally only exist in `index.js`, per https://redux.js.org/recipes/configuring-your-store and https://redux-toolkit.js.org/tutorials/advanced-tutorial#setting-up-the-redux-store .

**Comment by nickmccurdy** [comment]
I was just suggesting different formatting, this is what Prettier does:
```js
ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById("root")
);
```

**Comment by BenLorantfy** [comment]
ah I see, I can run prettier on it 👍

**Comment by salvoravida** [comment]
Hi, can i suggest to think also to an advaced template with redux-saga?
Most enterprise apps can't  scale with redux-thunk. Maybe it is an idea creating 2 redux templates.

**Comment by markerikson** [comment]
@salvoravida : I know you're a big fan of sagas, but no, I don't want to have them in a default template.

I do see a benefit to having both a JS and a TS template.

**Comment by BenLorantfy** [comment]
I ran prettier on my template. Wondering if someone wants to make an empty repo for the template? Then I can make a PR into it for further discussion.

**Comment by nickmccurdy** [comment]
I can help make a TS template after that's done, though I'll need some help reviewing it as I'm not used to the best practices for the new Redux Toolkit types

**Comment by markerikson** [comment]
Just created https://github.com/reduxjs/cra-template-redux and https://github.com/reduxjs/cra-template-redux-typescript .

@nickmccurdy : the "Advanced Tutorial" shows the right approaches: https://redux-toolkit.js.org/tutorials/advanced-tutorial

**Comment by markerikson** [comment]
@iansu : I see you published a blank `cra-template-redux` package a month ago.  Can you add myself and @timdorr as publishers?

**Comment by iansu** [comment]
@markerikson Yes, I can do that. I can even fully transfer the package to one of you. I need your npm usernames though. You can either post them here or just DM me on Twitter (same username) if that's easier.

**Comment by timdorr** [comment]
We're `acemarke` and `timdorr` on npm.

Does CRA support these being namespaced? If so, could we do it under the @reduxjs org.

**Comment by iansu** [comment]
I've added both of you. We do not currently support namespaces but we probably have to eventually. I'll add it to the list.

**Comment by BenLorantfy** [comment]
FYI, I created a PR for further discussion/review: https://github.com/reduxjs/cra-template-redux/pull/1

**Comment by nickmccurdy** [comment]
This is done.
