### ISSUE TITLE
es module process is not defined during tests and development 

### ISSUE THREAD

**Issue by lakshay35** [reduxjs/redux#3653]
I am running a environment from @open-wc and am using redux inside of there. The es directory inside node_modules/redux/ is where our redux library imports come from. On line 657 in node_modules/redux/es/redux.js, there is a line that reads 
```
if (process.env.NODE_ENV !== 'production'...
```

The tests and development runs in the browser, which I believe prevents the server and karma from detecting a node 'process' and causes the whole thing to not run. A temporary workaround if removing that line but I'd like to help our redux and get this resolved once and for all.

**Comment by timdorr** [comment]
You should use the redux.mjs file instead. That has all the process.env stuff filtered out.
