### ISSUE TITLE
Syntax highlight is incorrect for "newState"

### ISSUE THREAD

**Issue by johnlinp** [reduxjs/redux#3654]
## What docs page needs to be fixed?

- **Section**: Basic Tutorial
- **Page**: Reducers

## What is the problem?

The code snippet

```
(previousState, action) => newState
```

is rendered as

![](https://i.imgur.com/EpNZ7io.png)

The html source is

```html
<code class="hljs">
(previousState, action) =&gt; 
<span class="hljs-keyword">new</span><span class="hljs-type">State</span>
</code>
```

## What should be changed to fix the problem?

The variable `newState` should be rendered as a normal variable.

**Comment by johnlinp** [comment]
Hi @timdorr Can you please tell me why you closed this issue?

**Comment by markerikson** [comment]
Because he made a commit that changed the variable name and fixed the issue:
https://redux.js.org/basics/reducers

**Comment by johnlinp** [comment]
I see. Thank you @markerikson.
