### ISSUE TITLE
Consider using error code strategy employed by react

### ISSUE THREAD

**Issue by heygrady** [reduxjs/redux#3655]
https://github.com/facebook/react/tree/master/scripts/error-codes

Right now, every production website that uses redux is shipping lengthy error messages that are better suited to development.

Example:

> 'Reducer "'+t+"\" returned undefined when probed with a random type. Don't try to handle "+n.INIT+' or other actions in "redux/*" namespace. They are considered private. Instead, you must return the current state for any unknown actions, unless it is undefined, in which case you must return the initial state, regardless of the action type. The initial state may not be undefined, but can be null.'

My rough guestimate is that you could reduce the [minified version of redux](https://unpkg.com/redux@4.0.4/dist/redux.min.js) from 6660 characters to more like 4200 characters by replacing these long messages with terse, generated error codes like `throw code(1)`. Seems worth it for potential savings of more than 35%.

**Comment by markerikson** [comment]
Well, it's been 4.5 years and no one has complained yet :)  But, I do see your point.  It's not a priority for us to work on atm, but if you or someone else would like to put together the infrastructure, we can take a PR.

**Comment by andrewmcgivery** [comment]
@markerikson I think this one can be closed now, right?

**Comment by markerikson** [comment]
Yep!

FYI, I've got `4.1.0-alpha.0` ready to go - I just don't actually have publishing rights for the `redux` package atm because I've never had to publish it before :)  Will put that up as soon as Tim adds me there.

**Comment by markerikson** [comment]
Live now: https://github.com/reduxjs/redux/releases/tag/v4.1.0-alpha.0
