### ISSUE TITLE
Broken link in Server Rendering docs code snippet comment

### ISSUE THREAD

**Issue by themichaelyang** [reduxjs/redux#3666]
## What docs page needs to be fixed?
Recipes > Server Rendering > Inject Initial Component HTML and State

https://redux.js.org/recipes/server-rendering/#inject-initial-component-html-and-state

## What is the problem?

The `WARNING` comment in the code snippet in this section has a broken link. 

## What should be changed to fix the problem?

Current code snippet comment is:
```
// WARNING: See the following for security issues around embedding JSON in HTML:
// http://redux.js.org/recipes/ServerRendering.html#security-considerations
```

Should be updated to: 

```
// WARNING: See the following for security issues around embedding JSON in HTML:
// https://redux.js.org/recipes/server-rendering/#security-considerations
```

**Comment by markerikson** [comment]
Yep, good catch.  Can you go ahead and submit a PR to fix that?

**Comment by themichaelyang** [comment]
Sure!
