### ISSUE TITLE
StoreCreator does not accept Partial<S> as preloadedState

### ISSUE THREAD

**Issue by nappy** [reduxjs/redux#3670]
When passing an `Partial<StoreState>` to `createStore<StoreState, AnyAction, {}, {}>` as preloaded state, even when using the result of `combineReducers`, type checking fails as of redux 4.0.5

### Steps to Reproduce

Find a minimal demo here:
https://codesandbox.io/s/blazing-rgb-o8f03

### What is the expected behavior?

It should not throw type errors as in redux 4.0.4
Might be related with https://github.com/reduxjs/redux/pull/3485

**Comment by nappy** [comment]
Nevermind I was using the following type arguments `createStore<StoreState, AnyAction, unknown, unknown>` and had to adjust to createStore<CombinedState<StoreState>, AnyAction, unknown, unknown>` as of redux 4.0.5. Was not related to typescript version, and is probably intended behavior.

**Comment by nappy** [comment]
Although the resulting store is now `Store<CombinedState<StoreState>, AnyAction>`, which does not seem right. Maybe someone can clarify.

I do not know if such changes in type arguments are considered braking or not, but to me it still feels wrong.

**Comment by timdorr** [comment]
Yes, this is a know problem with the current types. This will be fixed in 5.0.
