### ISSUE TITLE
createStore should perhaps accept preloadedState: PreloadedState<S> | S

### ISSUE THREAD

**Issue by abirmingham** [reduxjs/redux#3672]
At least as of `4.0.5`, `createStore` accepts `preloadedState: PreloadedState<S>`. One imagines that one can pass `S` to `preloadedState`, and in most cases this is correct. However, there are cases in which `S` is not assignable to `PreloadedState<S>`, at least since `typescript@3.6.3`. See https://github.com/microsoft/TypeScript/issues/35992 for more information on this issue. It's unclear to me whether https://github.com/microsoft/TypeScript/issues/35992 is a typescript bug, but I'm wondering if `createStore` should accept `preloadedState: PreloadedState<S> | S`, which would mitigate the issue of branded types being mapped to `never`.

**Comment by timdorr** [comment]
This is fixed for 5.0 via #3485.

**Comment by abirmingham** [comment]
> This is fixed for 5.0 via #3485.

Thanks @timdorr !!!
