### ISSUE TITLE
chat action creators - return type incorrect

### ISSUE THREAD

**Issue by tonyhallett** [reduxjs/redux#3678]
## What docs page needs to be fixed?

[recipes/UsageWithTypescript - Type Checking Actions & Action Creators](https://github.com/reduxjs/redux/blob/master/docs/recipes/UsageWithTypescript.md#type-checking-actions--action-creators)

## What is the problem?

```ts
export type ChatActionTypes = SendMessageAction | DeleteMessageAction
```

ChatActionTypes return type is too wide

```ts
export function sendMessage(newMessage: Message): ChatActionTypes {
  return {
    type: SEND_MESSAGE,
    payload: newMessage
  }
}

// TypeScript infers that this function is returning DeleteMessageAction
export function deleteMessage(timestamp: number): ChatActionTypes {
  return {
    type: DELETE_MESSAGE,
    meta: {
      timestamp
    }
  }
}
```
## What should be changed to fix the problem?

Change to SendMessageAction and DeleteMessageAction

**Comment by timdorr** [comment]
As pointed out in the docs, TS will infer that the return type is the more specific `Send/DeleteMessageAction` types. We use the union type so that passing to the reducer is easier.

**Comment by tonyhallett** [comment]
Agreed it will infer the type.  Although you could change both action creators to return the incorrect action and it would still compile successfully.  What is the point of the return type other than to ensure that the function returns the correct type !

I agree with the union type for discriminated union in the reducer.
