### ISSUE TITLE
Documentation webpage using 100% of CPU

### ISSUE THREAD

**Issue by jsphkm** [reduxjs/redux#3688]
I'm noticing that the redux documentation website is using 100% of my CPU.

The reading comes from my mac's Activity Monitor and Safari alerting this:
```
This webpage is using significant energy.  Closing it may improve the responsiveness of your Mac.
```

This issue is consistently replicable with this page for now, https://redux.js.org/recipes/server-rendering

Using:
Safari 13.0.4
16" MacBook Pro

I was unable to replicate this on Chrome

**Comment by markerikson** [comment]
Hmm. Not sure what to tell you. It's primarily a plain static HTML file, and whatever JS is getting loaded on that page really shouldn't be doing anything fancy.

**Comment by timdorr** [comment]
Sounds like an extension gone bad. Nothing we can do about that.

**Comment by jsphkm** [comment]
Am I the only one experiencing this?

I did have one Safari extension called Bear, so I deleted the extension and the app since I don't use it.

Restarted Safari - same issue
Restarted Computer - same issue

Activity monitor shows 100% instantly

It's only with this webpage, other ones are fine.

This is my activity monitor as soon as I restarted my computer after I've restarted like stated above,
the only webpages are this GitHub issue page and the redux page:

<img width="840" alt="Screen Shot 2020-02-03 at 11 35 02 AM" src="https://user-images.githubusercontent.com/28643797/73684559-47ee2d00-4679-11ea-880a-895b13f5c4e6.png">

**Comment by jsphkm** [comment]
Do you think it has something to do with cache? Maybe the Safari is busy caching the pages?

It seemed like deleting cache and then restarting the computer made it seem like it fixed it for about less than a minute, until it showed up with 100% again.

**Comment by timdorr** [comment]
Looking at the Timeline in the dev tools, it's something with the CSS. The styles are getting invalidated constantly.

However, this only occurs on the home page. Since folks don't tend to hang out there long, I'm not particularly worried about it. I also noticed that Docusaurus's site doesn't suffer from this issue, so perhaps it's an upstream fix we'll get shortly.

**Comment by markerikson** [comment]
Poking @yangshun and @wgao19 as an FYI, as this sounds like a Docusaurus issue.

**Comment by yangshun** [comment]
We've received similar reports as well. It's probably a Safari bug but we could try to prevent instances of styles that will trigger the bug.

**Comment by yangshun** [comment]
Found the issue. It's due to the use of `transition: all` within `.navbar__search-input`. Disabling those lines in the web inspector fixes the CPU issue. We'll push out a fix.

**Comment by yangshun** [comment]
`docusaurus@2.0.0-alpha.43` has been released which contains the fix.
