### ISSUE TITLE
Typescript: $CombinedState as a possible return type of combineReducers?

### ISSUE THREAD

**Issue by josias-r** [reduxjs/redux#3689]
As it's recommended in redux w/ TS we get the type of a store w/ combined reducers doing the following:
```
type OriginalRootState = ReturnType<typeof combineReducers({myreducers: ..., ..., ...})>;
```
This is very helpful for a well-typed application. I stumbled on some advanced use-cases where I got type conflicts when I used the `keyof OriginalRootState` type.

Those type conflicts where caused because one possible key of that return type is `typeof $CombinedState`. Why is this type (of type unique symbol) a possible key value of the return type?

I'm currently hacking around it, by exporting a "cleaned" keyof type:
```
export type OriginalRootState = ReturnType<typeof combineReducers({myreducers: ..., ..., ...})>;
export type CleanRootStateKeys = Exclude<
  keyof OriginalRootState,
  typeof $CombinedState
>;
```

Redux version "^4.0.5"

**Comment by markerikson** [comment]
Can you provide a CodeSandbox that reproduces the issue?

**Comment by timdorr** [comment]
That's explained here: https://github.com/reduxjs/redux/blob/v4.0.5/index.d.ts#L35-L56

At its core, it's this last line:
>  It just makes this type distinquishable from plain `{}`.
