### ISSUE TITLE
Remove "Note About Other Routing Libraries" note from Usage with React Router page

### ISSUE THREAD

**Issue by bolatovumar** [reduxjs/redux#3694]
## What docs page is being added or updated?

- **Section**: https://redux.js.org/advanced/usage-with-react-router#next-steps
- **Page**: https://redux.js.org/advanced/usage-with-react-router

### What updates should be made to the page?
"Note About Other Routing Libraries" should be removed as it mentions two routing libraries which are deprecated and haven't had any activity in their repos for years. They don't have any npm downloads either.

### Do these updates change any of the assumptions or target audience? If so, how do they change?
No

**Comment by markerikson** [comment]
Agreed.  Please submit a PR and we can get that in.
