### ISSUE TITLE
Using Immutable.JS with Redux and React hooks

### ISSUE THREAD

**Issue by aachauhan2009** [reduxjs/redux#3699]
## What docs page is being added or updated?

[Using Immutable.JS with Redux](https://redux.js.org/recipes/using-immutablejs-with-redux/#use-a-higher-order-component-to-convert-your-smart-components-immutablejs-props-to-your-dumb-components-javascript-props)

- **Section**: https://redux.js.org/recipes/recipe-index
- **Page**: https://redux.js.org/recipes/using-immutablejs-with-redux/#use-a-higher-order-component-to-convert-your-smart-components-immutablejs-props-to-your-dumb-components-javascript-props

### What updates should be made to the page?

Can anyone please update best practices for using immutable js with hooks? The current approach which is using hoc is causing useEffect to run if non-primitive data is given as dependency array. 

Should we create a separate view for each and every component which is using hooks with dependency? 

### Do these updates change any of the assumptions or target audience? If so, how do they change?

The target audience for this document change doesn't change as it will be targeted for the react community.

Here is simple example i created in codesandbox
[![Edit react-hooks-with-immutable-redux-store](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/winter-star-o08lq?fontsize=14&hidenavigation=1&theme=dark)

**Comment by markerikson** [comment]
At this point, [we now officially recommend _not_ using Immutable.js](https://redux.js.org/style-guide/style-guide#use-plain-javascript-objects-for-state).

Given that, I don't have any plans to update that docs page, and in fact will likely end up removing it as part of the ongoing docs rewrite.

(Also, note that this sounds more like a usage question than anything else.)

**Comment by FabKremer** [comment]
@aachauhan2009 at [NeoCoast](neocoast.com) we've worked to solve this issue. Feel free to [check it out](https://github.com/NeoCoast/Neox)! ⭐️
