### ISSUE TITLE
Is redux really a cache?

### ISSUE THREAD

**Issue by mohankoppuravuri** [reduxjs/redux#3703]
People say redux act as a cache. By default it uses async-storage which means redux stores in sqlite database.
Is it like every time it fetches from database? 
If it fetches from sqlite then How it is a cache. Technically in terms of speed cache >> RAM >> database (redux).
Please explain why people consider it as a cache?

**Comment by timdorr** [comment]
We don't use any storage system by default. I think you have this confused for another project. 

Regardless, this is a bug tracker, not a discussion forum. Closing.
