### ISSUE TITLE
Use Redux toolkit but do not use Immutable

### ISSUE THREAD

**Issue by JeremiAnastaziak** [reduxjs/redux#3711]
## What docs page needs to be fixed?

- https://redux.js.org/style-guide/style-guide/
- https://redux.js.org/style-guide/style-guide/#use-redux-toolkit-for-writing-redux-logic
- https://redux.js.org/style-guide/style-guide/#use-plain-javascript-objects-for-state

## What is the problem?

Redux style guide says: "use redux toolkit", "do not use immutable.js"
Redux toolkit recipe says: "use immutable.js"
https://redux.js.org/recipes/using-immutablejs-with-redux/

## What should be changed to fix the problem?
It's confusing, stick with one recommendation.

**Comment by timdorr** [comment]
We should probably just drop that page entirely. Many folks are moving off Immutable to Immer or TypeScript (or both!).

**Comment by markerikson** [comment]
Yes, I plan to drop that page entirely as part of the docs rewrite.

When we do that, I want to redirect any external incoming links to that page to the "Immutable Update Patterns" page instead, using the `_redirects` file.

**Comment by enoh-barbu** [comment]
> We should probably just drop that page entirely. Many folks are moving off Immutable to Immer or TypeScript (or both!).

how can one drop Immutable in favor of TS? these are different tools

**Comment by timdorr** [comment]
Readonly types or fields.

**Comment by enoh-barbu** [comment]
@timdorr if I don't ask too much, can you please give me a more detailed example. I know we might get out of subject, but might be handy also for other folks reading these comments :)

**Comment by markerikson** [comment]
Fixed by #4053 .
