### ISSUE TITLE
Support to Flow in docs

### ISSUE THREAD

**Issue by fanny** [reduxjs/redux#3716]
## What docs page is being added or updated?

- **Section**: Recipes
- **Page**: - 

## For Adding New Content
Since the flow is a static type checker with a large usage, I was asking me why the doc don't have a topic, explaining the use with the flow. I saw in Recipes section, that we have an section explaining the usage with typescript, but I can't see the same with the flow, i only see a simple example of todo. Is there any reason? because I'm starting using redux in an app with flow, and I miss this on the doc.

### What kind of content category is this page (tutorial, how-to, explanation, reference)?
Reference

**Comment by markerikson** [comment]
Hi.  Appreciate the suggestion.  Unfortunately, [given how small Flow's market share is at this point](https://docs.google.com/presentation/d/1M-JUtp9I5_gSk8OpV9Adk9sYzhoU-VNcwz9RUJ1-8Sw/edit#slide=id.g6efabcab1d_0_1364), I'm not sure it's worth adding specific documentation on this.

**Comment by fanny** [comment]
Good point, thanks for share this resource.

**Comment by fanny** [comment]
@markerikson I'm also have interest in contribute with this community. Do you have any suggestions?

**Comment by markerikson** [comment]
We're working on [a major rewrite of the Redux core docs](https://github.com/reduxjs/redux/issues/3592).  Could definitely use help with some of the items listed under there.
