### ISSUE TITLE
Devtools scrollbars should be dark in dark mode 

### ISSUE THREAD

**Issue by asadikhlas** [reduxjs/redux#3717]
**What is the current behavior?**
When Chrome Devtools are in "dark mode", all the standard panels have a dark scrollbar:

![Screenshot from 2020-03-03 03-10-29](https://user-images.githubusercontent.com/33983874/75722723-97695c80-5cfc-11ea-9d94-3f3aa5539de4.png)

**However, the Redux Devtools still show a light scrollbar:**

![Screenshot from 2020-03-03 03-13-43](https://user-images.githubusercontent.com/33983874/75722927-0777e280-5cfd-11ea-860e-7c4639f3dfa3.png)

**What is the expected behavior?**
Scrollbars should be styled similarly to the standard panels

### Which versions of Redux, and which browser / OS are affected by this issue?
Any Redux version
Chrome 79.0
Ubuntu 18.04.3 LTS

**Comment by markerikson** [comment]
This is the repo for the Redux core library, not the DevTools.  We also don't actually maintain the DevTools extension ourselves.  That's located over at https://github.com/zalmoxisus/redux-devtools-extension .  I'd suggest filing an issue over there.
