### ISSUE TITLE
useSelector() - changing redux state without useDispatch ???

### ISSUE THREAD

**Issue by borakuldeep** [reduxjs/redux#3718]
### What is the current behavior?
```
let data= useSelector((state:State) => state.data);
data = data.filter(/* filter data.... */)
```
above line actually changes the state. Not sure if it should. State should be change only via useDispatch.

### Steps to Reproduce
```
let data= useSelector((state:State) => state.data);
data = data.filter(/* filter data.... */)
```

### What is the expected behavior?

Redux state should be changed via dispatch actions only (??) If not, then useDispatch seems redundant in redux hooks. 

### Environment Details

 "react-redux": "^7.2.0",
 "redux": "^4.0.5",

**Comment by Qquanwei** [comment]
In this situation actually you are not modify the state of store. the variable ‘data’ only a local variable, data = data.filter(...) only modify the local variable ‘data’ without the ‘data’ point object. so state of store is not be modify.

But in other way, redux cannot prevent user modify the data of production.

**Comment by timdorr** [comment]
I'm not seeing how that particular code would modify anything. The data variable is local and non-referential, so it won't write back to the value in the store object by itself.

I would recommend looking into use Redux Toolkit, as it has an immutability library built-in (Immer) and can prevent these kinds of issues: https://redux-toolkit.js.org/

**Comment by markerikson** [comment]
Yeah. That code shouldn't be causing any mutations as shown.  However, in general, the Redux core does nothing to prevent mutations.  Any reference to `state` is the actual value kept in the store, and if you mutate it, it's your bug :)  But, Redux Toolkit will throw errors by default if it detects mutations.

**Comment by borakuldeep** [comment]
Thanks All, yeah I have to figure out what is wrong with my code. :)

**Comment by DaCheeseMan** [comment]
Hi!
Could you share your error? I'm experiencing the same behavior.
