### ISSUE TITLE
Link broken: https://redux.js.org/api-reference/store#subscribelistener

### ISSUE THREAD

**Issue by chinmaykude** [reduxjs/redux#3725]
Below link is broken, please fix it. Please refer to attached screenshots for more reference.

_https://redux.js.org/api-reference/store#subscribelistener_

### What is the current behavior?
Below link is broken:
_https://redux.js.org/api-reference/store#subscribelistener_

Please fix the broken link.

### Steps to Reproduce
Navigate to _https://redux.js.org/api-reference/store#subscribelistener_

![image](https://user-images.githubusercontent.com/23414927/76071084-b1849280-5fbb-11ea-901e-13cf8c038f0b.png)
![image](https://user-images.githubusercontent.com/23414927/76071138-c95c1680-5fbb-11ea-9d2e-033981fd6bb4.png)

**Comment by markerikson** [comment]
Where are you seeing the original link in the first place?

**Comment by timdorr** [comment]
Can you submit a PR? An issue isn't really the best format for this.

**Comment by markerikson** [comment]
That said, we should add redirects to handle old incoming links and point them to the current URLs.  I know I have a bunch in there already, but looks like I might have missed some.
