### ISSUE TITLE
Typescript declaration file using namespace

### ISSUE THREAD

**Issue by kaysonwu** [reduxjs/redux#3735]
## New Features

Typescript declaration file using namespace

### Why should this feature be included?

Type reuse

### What docs changes are needed to explain this?

TS supports global type declaration.  Example：

```ts
// global.d.ts

interface IModel {
  ....
  reducers: Record<string,  any>;
}

// /models/global.ts

const Global: IModel = {
  ...
  reducers: {
    save(state, action) {
    }
  }
};

export default Global;
```

In this way, import is not required for global types.  Unfortunately, TS does not support the use of the 'import' keyword reuse type in the declaration file. 

If I declare the type as follows:

```ts
// global.d.ts
import { Reducer } from 'redux';

interface IModel {
  ....
  reducers: Record<string,  Reducer>;
}
```

Then, when I use it, I have to add import

```ts
// /models/global.ts
import { IModel } from 'global.d.ts' 

const Global: IModel = {
  ...
  reducers: {
    save(state, action) {
    }
  }
};

export default Global;
```
In order to save import, I started looking for some solutions. Finally found that react can well implement type reuse. Because react uses namespaces to declare types. So, I can reuse the type of react without import. As follows:

```ts
// global.d.ts

type Key = React.Key;
```

**Comment by timdorr** [comment]
[React only uses global definitions](https://unpkg.com/browse/@types/react@16.9.23/global.d.ts) to provide types for projects not pulling in DOM types (such as React Native). It does not put all of its types in the global scope. We don't have any global type requirement, so this isn't something we need to implement.

I would highly advise against relying on global types. It makes tracking callsite usage extremely tough, meaning it becomes harder to modify types over time.

**Comment by kaysonwu** [comment]
I may not have described it clearly. Actually, I want redux to use namespace wrapper type declaration files. E.g：[React](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L65).

There is such a requirement because the type I define depends on the Redux type, and I hope to inherit it.
