### ISSUE TITLE
"Basics" link is a 404

### ISSUE THREAD

**Issue by CluEleSsUK** [reduxjs/redux#3743]
## What docs page needs to be fixed?
The link to basics on the main README (front github page)

## What is the problem?
Clicking "basics" leads to the redux website but says the page is not found (https://redux.js.org/basics).

## What should be changed to fix the problem?
The URL should be https://redux.js.org/basics/basic-tutorial

**Comment by timdorr** [comment]
Could you submit a PR to fix this?
