### ISSUE TITLE
Docs: More Style Guide entries

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3759]
## What docs page is being added or updated?

- **Section**: Style Guide
- **Page**: Style Guide

### What updates should be made to the page?

Some additional items I'd like to add:

- [x] Organize reducers based on type of data and features, not specific components
- [x] Use hooks as the default, instead of `connect`
- [x] Name state slices after their data, without the word `reducer` in the name (ie, `state.users`, not `state.usersReducer`)

Any others we should add?

**Comment by tony-go** [comment]
Is slice usage should not be the default usage? Or toolkit stay stand alone in this part of the documentation?

**Comment by markerikson** [comment]
@tony-go Not sure what you're asking. Can you clarify?

**Comment by tony-go** [comment]
Sorry 🙈 !

As items to add, you do you think about to use createSlice (toolkit) as default usage?

**Comment by markerikson** [comment]
@tony-go We have separate plans to rewrite the tutorial sequence later.  See https://github.com/reduxjs/redux/issues/3592 .

This issue is just about adding specific new entries to the Style Guide page.

**Comment by markerikson** [comment]
Per https://github.com/reduxjs/redux-toolkit/issues/521 , possibly add a recommendation for the `no-param-reassign` ESLint rule to avoid people doing `state = newValue` in RTK reducers?

**Comment by Luchanso** [comment]
Recommendation like `'no-param-reassign': ['error', { props: true, ignorePropertyModificationsFor: ['state'] }]`, this will ignore rule for `state` variable

**Comment by markerikson** [comment]
@Luchanso 	Nice, thanks for the suggestion!

**Comment by markerikson** [comment]
Going to mark this as resolved.  I don't think we specifically should add the `no-param-reassign` thing in the style guide, but I'll mention it in the RTK "Writing Reducers with Immer" usage guide.
