### ISSUE TITLE
Fetching from Reddit API in advanced tutorial fails with CORS error in console on firefox (with strict enhanced tracking protection enabled)

### ISSUE THREAD

**Issue by andoks** [reduxjs/redux#3760]
## What docs page needs to be fixed?

- **Section**: https://redux.js.org/advanced
- **Page**: https://redux.js.org/advanced/async-actions

## What is the problem?
When running Firefox (75.0) in "strict" (or certain configurations of custom) "Enhanced Tracking Protection" mode, calls toward the Reddit API fails with the following error in the console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.reddit.com/r/reactjs.json. (Reason: CORS request did not succeed).

This was confusing, as I initially thought this was due to something I had done wrong in the tutorial.

After investigating some more, I started thinking it was an issue with the Access-Control-Allow-Origin header from the API as the exact same fetch code worked with https://jsonplaceholder.typicode.com/.

However the tutorial code _did_ work on chrome, which made the issue all the more confusing. I ended up finding someone else that had the same issue on [reddit](https://www.reddit.com/r/redditdev/comments/di9y1t/reddit_api_calls_being_blocked_by_firefox_content/f3ua0ax/), which led me to test the "Standard" Enhanced Tracking Protection mode which made the tutorial code that I had written initially, work.

## What should be changed to fix the problem?
One solution could be to switch to some API in the example that is not considered a tracker by Firefox (or any other browser).

I also wanted to add this issue for posterity, so that if anyone else stumbles over the same issue, they won't have to waste as much time as I did with trying to find the root cause.

**Comment by markerikson** [comment]
Appreciate the notice, but yeah, nothing we can do about this atm.
