### ISSUE TITLE
Async Actions comment in code is linking to already closed issue

### ISSUE THREAD

**Issue by Alexsey** [reduxjs/redux#3777]
## What docs page needs to be fixed?

- **Section**: Advanced Tutorial
- **Page**: Async Actions

## What is the problem?
The comment in first Async Action code says
```
Do not use catch, because that will also catch
any errors in the dispatch and resulting render,
causing a loop of 'Unexpected batch number' errors.
https://github.com/facebook/react/issues/6895
```

And the issue that the comment is linking to is already closed for almost 3 years with description that this kind of error should never be thrown by React ever again. So the whole comment is obsolete

## What should be changed to fix the problem?

I'm new to React and cannot tell if there is still a reason not to add an error handling, but if there is some - now it's different. So, somebody with a better knowledge of React should do:
1. Remove the current comment, because it's obsolete
2. Add a new comment about error handling and/or error handling code

Or consider not adding error handling in this section in the sake of simplicity but add it to full example code (like above with actions for error handling and with data normalization)

**Comment by timdorr** [comment]
In general, it's not really a good idea to catch errors during rendering, as that might hide errors that should be caught in an error boundary. While the linked issue has some age to it, it's still good advice.

If you want to submit a PR to remove that comment from the example, we can certainly take a look.
