### ISSUE TITLE
Updating Normalized Data with merging approach, wrong example

### ISSUE THREAD

**Issue by SDP190** [reduxjs/redux#3779]
## What docs page needs to be fixed?

- **Section**: [Simple Merging](https://redux.js.org/recipes/structuring-reducers/updating-normalized-data#simple-merging)
- **Page**: [Managing Normalized Data](https://redux.js.org/recipes/structuring-reducers/updating-normalized-data)

## What is the problem?

The docs says to do deep copy with lodash merge tool, for the example of adding a new Comment to post.

> ..._We'll use the example of adding a new Comment to a Post_.
One approach is to merge the contents of the action into the existing state. In this case, we need to do a deep recursive merge, not just a shallow copy. The Lodash merge function can handle this for us: 
``` 
import merge from 'lodash/merge'

function commentsById(state = {}, action) {
  switch (action.type) {
    default: {
      if (action.entities && action.entities.comments) {
        return merge({}, state, action.entities.comments.byId)
      }
      return state
    }
  }
} 
```
However, I am not sure why deep copy is needed here for a new Comment object why not just use that comment object supplied by action and add it to state by returning a new state object wich should combine old comments and new comments, like:
`return {...state, ...action.entities.comments.byId}` or via ` return Object.assign({}, state, action.entities.comments.byId)
`
Maybe its not a good practice to use the same objects from the action? so we need to create it again in reducer? ( - if so, when we initialize the store with a huge list of data fetched from api for example, we would have to create again all data in reducer!! - ), but even if so, still don't have to deep merge old state object? we can do: 
```
return  _.merge( { ...state}, action.entities.comments.byId);
```
The only case I can see for deep merge here, is if using that same logic for updating existing items (not as stated in docs page:  _We'll use the example of adding a new Comment to a Post_), **and the action items contain only the updated properties**, then we might need deep merge old state with updated propeties.

## What should be changed to fix the problem?

Maybe change example to:
`return  { ...state, ...action.entities.comments.byId};`
or (if we should not reference objects from the action):
`return  _.merge( { ...state}, action.entities.comments.byId);`
or it should be made clear that the example is specifically needed only when using that for updating existing items and the action items contain only updated properties!

**Comment by timdorr** [comment]
Can you make a PR with your changes? That will be a better format to discuss the problem.

**Comment by SDP190** [comment]
@timdorr why closing the issue before solving it? Just ignoring the issue won't help the documentation!
I should do a PR? why? I am not a member, and I don't have the time for cloning the repo, just wanted to make you aware of the problem in your documentation, if you don't like to fix it your own its Ok, but will confuse redux users.

**Comment by timdorr** [comment]
You don't need to be a member of this org or manually fork a repo. Just go here and hit the pencil icon in the upper right: https://github.com/reduxjs/redux/blob/master/docs/recipes/structuring-reducers/NormalizingStateShape.md

**Comment by SDP190** [comment]
thanks @timdorr, [here is PR](https://github.com/reduxjs/redux/pull/3780)
