### ISSUE TITLE
loose-envify incorrectly listed as dependency in v4.0.5

### ISSUE THREAD

**Issue by BruceRBowers** [reduxjs/redux#3790]
### Prior Issues

None known

### What is the current behavior?

In the package.json file, (and in the npm registry), redux@4.0.5 lists loose-envify as a dependency.

### Steps to Reproduce

$ npm view redux@4.0.5 dependencies

### What is the expected behavior?

What should Redux be doing?

loose-envify should not be listed as a dependency of redux@4.0.5.

### Environment Details

Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?

N/A

**Comment by timdorr** [comment]
This is for browserify users. I believe we're dropping it in 5.0 though.
