### ISSUE TITLE
Remove Link to WordPress Framework

### ISSUE THREAD

**Issue by Santiago8888** [reduxjs/redux#3793]
## What docs page needs to be fixed?

- **Section**:ReadMe
- **Location**: First Sentence

## What is the problem?
The reference to the WordPress framework loses focus on Redux's introduction. It may have been relevant three years ago (2017) but given the flourishment of Redux community is hardly relevant anymore.

## What should be changed to fix the problem?
Current:
Redux is a predictable state container for JavaScript apps. (Not to be confused with a WordPress framework – Redux Framework.)

Proposed:
Redux is a predictable state container for JavaScript apps.

**Comment by timdorr** [comment]
While I agree, the owner of that framework has gotten angry about us unintentionally co-opting the name. As a show of good faith, we need to leave it in place indefinitely.
