### ISSUE TITLE
Basic Tutorial: Usage with React - Code bug

### ISSUE THREAD

**Issue by AliEskandari** [reduxjs/redux#3796]
## What docs page needs to be fixed?
The code for the Link.js component in the basic tutorial has a bug. This is the url for the code block: [`Link.js`](https://redux.js.org/basics/usage-with-react#componentslinkjs)

- **Section**:
Basic Tutorial
- **Page**:
Usage with React
Subsection: Implementing Presentational Components
Code Block for File: `components/Link.js`

## What is the problem?
Lines 4-7 of the `components/Link.js` code reads...
```js
const Link = ({ active, children, onClick }) => {
  if (!active) { // <= bug: should be "if (active) {"
    return <span>{children}</span>
  }
...
```
Using `!active` in this case would mean inactive filters will not be clickable. This is obviously not desired. Inactive filters should be clickable, and Active filters should be disabled (not clickable).

## What should be changed to fix the problem?
Changing the code to the following will fix it:
```js
...
if (active) {
...
```

**Comment by timdorr** [comment]
Yup. We haven't synced this code with what's in the example in a while. Can you make a PR to fix this? That's a better format than an issue.

**Comment by markerikson** [comment]
That said, note that the entire tutorial sequence will hopefully get rewritten in the not-too-distant future.
