### ISSUE TITLE
Redux Essentials Tutorial Part 4 has a type error

### ISSUE THREAD

**Issue by samwightt** [reduxjs/redux#3812]
## What docs page needs to be fixed?

- **Updating Post Entries**:
- **Redux Essentials, Part 4: Using Redux Data**:

## What is the problem?
On the **Redux Essentials, Part 3: Basic Redux Data Flow** page, the user is told to create this initial state containing integer ids:

```
const initialState = [
  { id: 1, title: 'First Post!', content: 'Hello!' },
  { id: 2, title: 'Second Post', content: 'More text' }
]
```

However, later on in the tutorial, the user is told to create a `SinglePostPage` that compares a route parameter (a string) with each post id. Because a triple equals sign is used and type conversion doesn't happen, the original data will always show the not found page. New data works just fine, but old data does not.

## What should be changed to fix the problem?

The selector code should be:

```
const post = useSelector(state =>
    state.posts.find(post => post.id.toString() === postId)
)
```

**Comment by markerikson** [comment]
Y'know, I think I fixed this in the app code and just forgot to update the snippets in the page.  I changed the IDs to strings:

https://github.com/reduxjs/redux-essentials-example-app/commit/c783509a6da54bb21066f20c760f2afdc7203f2c

```js
const initialState = [
  { id: '1', title: 'First Post!', content: 'Hello!' },
  { id: '2', title: 'Second Post', content: 'More text' },
]
```

@samwightt 	, can you submit a follow-up PR to drop the `.toString()` and update the displayed snippets to match what's in that commit?

**Comment by samwightt** [comment]
Yep sure!
