### ISSUE TITLE
Minor bugs in code for fetching data with createAsyncThunk

### ISSUE THREAD

**Issue by hettlage** [reduxjs/redux#3826]
## What docs page needs to be fixed?

- **Section**: Tutorial: Redux Essentials, Part 5
- **Page**: Loading Posts

## What is the problem?

There are two small bugs in the code:

* In `features/posts/PostsList.js` the `postStatus` value `'error'` should be `'failed'`.
* In `features/posts/postsSlice.js`

```javascript
    [fetchPosts.rejected]: (state, action) => {
      state.status = 'failed'
      state.error = action.payload
    }
```

should presumably be

```javascript
    [fetchPosts.rejected]: (state, action) => {
      state.status = 'failed'
      state.error = action.error.message
    }
```

## What should be changed to fix the problem?

The code should be updated in the documentation.

**Comment by markerikson** [comment]
Fixed the example project and just pushed an edit to the docs.  Thanks!
