### ISSUE TITLE
@@INIT action is transmitted a second time and store is reset to erase the modification before when non-existing url is access or page is refreshed.

### ISSUE THREAD

**Issue by kevin-hans** [reduxjs/redux#3827]
## What docs page needs to be fixed?

- **Section**:
https://redux.js.org/tutorials/essentials/part-3-data-flow
- **Page**:

## What is the problem?
There seems to be a bug in the example below.
https://codesandbox.io/s/github/reduxjs/redux-essentials-example-app/tree/tutorial-steps

@@INIT action is transmitted a second time and store is reset to erase the modification before when non-existing url is accessde or page is refreshed.

This problem also exists in local.

## What should be changed to fix the problem?
I think the example source code should be fixed.

**Comment by markerikson** [comment]
Can you clarify the repro steps?  What do you mean by "when a non-existing URL is accessed"?

**Comment by timdorr** [comment]
This is expected behavior. We're not persisting the data from the API anywhere, so it is supposed to disappear when reloading. It's just randomly generated and a mock of a real API you might build/use.
