### ISSUE TITLE
Redux Essentials, Part 3, Incorrect Image

### ISSUE THREAD

**Issue by jordanmoore753** [reduxjs/redux#3830]
## What docs page needs to be fixed?

- **Redux Essentials**
- **Part 3: Basic Data Flow**

## What is the problem?

In the section entitled [Showing the Post List](https://redux.js.org/tutorials/essentials/part-3-data-flow#showing-the-posts-list), the image which should show a successful render of the posts list, instead shows an image of what I believe to be the completed application. The image shows a list of notifications, a navbar with posts, users, and notifications buttons, and a refresh notifications button to the right of the navbar.

## What should be changed to fix the problem?

I took a picture of my screen upon successfully rendering the posts list. This picture could be used in place of the current one to show what a user's screen should look like at this point in the tutorial. 

![correct_step](https://user-images.githubusercontent.com/46928924/88929919-c6064780-d248-11ea-8a10-aba6124343ea.jpg)

Thank you for your time!

**Comment by markerikson** [comment]
Whoops, I completely messed that one up :) 

Could you go ahead and file a PR to replace that?  Crop your screenshot to the same size and shape as the existing one (I think it's like 800x???).

**Comment by jordanmoore753** [comment]
Thanks for the quick response, Mark! I just submitted the PR to fix the image problem.
