### ISSUE TITLE
Objects used to hydrate create store must be plain ol objects

### ISSUE THREAD

**Issue by 42shadow42** [reduxjs/redux#3838]
### What is the current behavior?

Right now redux throws the error: The preloadedState argument passed to createStore has unexpected type of "Object". Expected argument to be an object with the following keys: "todos" when passing an object created via new()

### Steps to Reproduce

Create a root reducer by using combineReducers.
Create a store using an object created via new

export const TodoAppReducer = combineReducers({
	todos: TodosReducer
});

export const TodoAppStore = createStore(TodoAppReducer, new TodoAppState());

### What is the expected behavior?

Redux should accept object created via new as long as they conform to the shape expected by the reducer as expected.

### Environment Details

I was using 4.0.5

**Comment by 42shadow42** [comment]
I can work around this issue by using Object.assign({}, new TodoAppState()), when creating the store, because it creates a 'plain ol' copy of the object with the properties that match the shape, it would be sufficient to bake this logic into createStore if for some react requires that objects not be instantiated via new.

I consider this a bug because the existing behavior creates confusion indicating an error where in fact the application is behaving exactly as expected.

**Comment by timdorr** [comment]
This is a core rule of Redux. State must be serializable and an object type instance is not.
