### ISSUE TITLE
Docs header overflows between 997 and 1157px

### ISSUE THREAD

**Issue by MirceaUngureanu** [reduxjs/redux#3839]
## What docs page needs to be fixed?

- **Section**: Header
- **Page**: All

## What is the problem?

The header content is overflowing when the browser width is between 997px and 1157px.
Tested on the latest version of Chrome and Safari.
![Screenshot 2020-08-07 at 10 48 15](https://user-images.githubusercontent.com/21081189/89635454-e5335380-d89e-11ea-98f4-6de0168eeaa7.png)

## What should be changed to fix the problem?
The easiest fix would be to set `flex-wrap: nowrap;` on `.navbar__inner`.

I'm happy to do a quick pull request for this.

**Comment by markerikson** [comment]
The styling comes straight from Docusaurus v2.  Any styling issues should be filed over there first so that we can pick them up in a new version, but I guess a temporary override might be useful.  Does this happen with the Redux Toolkit docs site as well?

**Comment by MirceaUngureanu** [comment]
Redux Toolkit is fine because it doesn't have that many items in the navbar. But if it did, it would suffer from the same issue.
Maybe in the future, it's worth amending the layout a bit to match `react-redux` until the sidebar layout kicks in.
I'll add the override to `/website/src/css/custom.css`.
