### ISSUE TITLE
Add `date:` property to `initialState`

### ISSUE THREAD

**Issue by klequis** [reduxjs/redux#3845]
## What docs page needs to be fixed?

- **Section**: Sorting the Posts List
- **Page**: part-4-using-data.md

## What is the problem?

After adding the code in the listing for `features/posts/PostList.js` there is an error because the posts in `initialState` don't have a `date` field.

## What should be changed to fix the problem?

Add a code listing to instruct user to add date field and related date-fns code `postsSlice.js`

## Note

Not sure if you want to add this or just have the user look it up in the related sample app?

**Comment by markerikson** [comment]
I think I did have this in the actual repo code, right?  Then yeah, should add a mention of this for the user.  Can you file a PR to update the wording in the page?

**Comment by klequis** [comment]
It is in the tag checkpoint-2-reactionButtons. Personally, if you had not mentioned the tags to me in another conversation I never would have looked there. 

I have a bit of time today so will try to do a PR on this.
