### ISSUE TITLE
broken codesandbox link in the Usage with TypeScript page

### ISSUE THREAD

**Issue by OfirD1** [reduxjs/redux#3848]
## What docs page needs to be fixed?

- **Section**: 
Recipes
- **Page**: 
[Usage with TypeScript](https://redux.js.org/recipes/usage-with-typescript)
- **Paragraph**: 
[A Practical Example](https://redux.js.org/recipes/usage-with-typescript#a-practical-example)

## What is the problem? 
The [codesandbox link](https://codesandbox.io/s/w02m7jm3q7) is broken (404).

## What should be changed to fix the problem?
fix the broken link

**Comment by markerikson** [comment]
Fixed by #4042 .

**Comment by OfirD1** [comment]
@markerikson, really nice job! 
I do however think it's worth having a complete codesandbox demo, that will simply contain this page's code snippets.
