### ISSUE TITLE
Minor update to Redux Essentials, Part 3: Basic Redux Data Flow

### ISSUE THREAD

**Issue by MirceaUngureanu** [reduxjs/redux#3849]
## What docs page is being added or updated?

- **Section**: #saving-post-entries
- **Page**: tutorials/essentials/part-3-data-flow

### What updates should be made to the page?
Because the last line of the `postsSlice.js` snippet is an export, an error can occur from copy-pasting in a rush.
By including the default export in the snippet it can be made more explicit and prevent that.
Also, can serve as a spatial reminder that the generated reducer from `createSlice` is being passed to the store.

Current:
![Screenshot 2020-08-11 at 19 55 18](https://user-images.githubusercontent.com/21081189/89937165-a25ddc80-dc0c-11ea-9837-8915c154a1f5.png)
Amended:
![Screenshot 2020-08-11 at 19 55 23](https://user-images.githubusercontent.com/21081189/89937179-a689fa00-dc0c-11ea-99ed-740018f82fa3.png)

Happy to do a quick pull request for this.

**Comment by markerikson** [comment]
Sure, please do!
