### ISSUE TITLE
Code examples that are not included

### ISSUE THREAD

**Issue by klequis** [reduxjs/redux#3851]
## What docs page needs to be fixed?

- **Section**: Adding Authors for Posts
- **Page**: part-4-using-data#more-post-features.md

## What is the problem?

More of a question than a fix: In a couple of places, "Adding Authors for Posts" for example, code modifications are mentioned at the bottom of a section without a code listing.

E.g.,

"We can now import the PostAuthor component into both PostsList.js and SinglePostPage.js, and render it as <PostAuthor userId={post.user} />, and every time we add a post entry, the selected user's name should show up inside of the rendered post."

It is easy enough to look in the final version to see of the example code and see where the additions should be. However, it seems odd that if you don't do that the components are added in later code examples, but not highlighted, and the project won't compile without the addition. 

I'll guess this was done to save the tutorial getting longer but I find it a bit confusing. Wondering if you would be open to 1. added the left out code examples, or 2. highlighting the changes when they appear later? I don't really like number 2, it seems odd to highlight something not under discussion in the current section.

I think the overall flow of the tutorial would be improved by adding the additional code examples.

**Comment by markerikson** [comment]
Yeah, the tutorial was already getting much longer than I had originally intended it to be, and in fact ended up at a whopping 25K words.  I also wasn't trying to show literally every line of code that gets changed - the goal is to focus on the meaningful changes, and I link to the current state of the code in the sandboxes at the end of each section.

I understand the point of the request, but I'm hesitant to try to add in more code sections when it doesn't feel like they're going to add as much value.

**Comment by klequis** [comment]
Makes sense.
