### ISSUE TITLE
Redux middleware example causes confusion

### ISSUE THREAD

**Issue by jackylong1992** [reduxjs/redux#3858]
## What docs page needs to be fixed?

One of the seven examples on redux middleware section causes me confused. It is the **timeoutScheduler**.
https://redux.js.org/advanced/middleware#seven-examples

## What is the problem?
I don't think that the cancel() function will ALWAYS be called. The only way we can call this function is register timeoutScheduler as first middleware on the chain then execute store.dispatch()().
## What should be changed to fix the problem?
I think we should remove that out of the examples. Since the returned value is NOT important when using middleware.

**Comment by markerikson** [comment]
The middleware isn't trying to "always" run the `cancel` function.  It's simply generating a form of an "unsubscribe"-type callback, and returning that as the result from `dispatch()`.  That way, the caller can cancel the timer if desired:

```js
const cancelTimer = dispatch({type: 'increment', meta: {delay: 5000}});

// later
cancelTimer();
```

Returned values _are_ important, because a middleware can return anything it wants from `dispatch()`.  That's how thunk functions are able to return a promise - the thunk middleware returns whatever the thunk function itself returns.

**Comment by jackylong1992** [comment]
@markerikson I don't think you can ALWAYS call to cancelTimer() if you have MORE than one middleware in the chain. The dispatch() only return the returned value from the FIRST middleware in chain.
It will NOT work if we do this: 
![image](https://user-images.githubusercontent.com/24369083/90590714-74c7f300-e20b-11ea-90a9-46ad494667dd.png)

**Comment by markerikson** [comment]
That's how Redux middleware work.

Any middleware may substitute its own return value. If a middleware is written correctly, it _should_ pass later return values forward, ie, `return next(action)`.

However, any middleware in front of that may _also_ substitute its own return value, delay the return value, not return anything, etc.

So, it's a question of how the middleware in the chain are cooperating with each other.

But yeah, this middleware itself is written correctly. Trust me on this :)

**Comment by jackylong1992** [comment]
@markerikson thanks for your explanation. It would be better if that flexibility is described more clearly in your document.

**Comment by markerikson** [comment]
Rewriting the existing "Basics/Advanced" tutorial is literally what I'm working on right now :)

See #3854 .
