### ISSUE TITLE
Codesandbox for typescript example isn't working

### ISSUE THREAD

**Issue by codec-abc** [reduxjs/redux#3862]
## What docs page needs to be fixed?

- **Section**: Recipes
- **Page**: Usage with typescript

## What is the problem?

The [link](https://github.com/reduxjs/redux/blame/master/docs/recipes/UsageWithTypescript.md#L29) to a [https://codesandbox.io/s/w02m7jm3q7](codesandbox) is valid but when opening the sandbox I got an error message 
`Something went wrongRequest failed with status code 404` with both FF and Chrome.

## What should be changed to fix the problem?

I have no idea as I don't know Redux (yet) nor codesandbox.

**Comment by timdorr** [comment]
You have your markdown backwards here. The link text goes in the square brackets and the link goes in the parentheses. That's why it 404s, because http://codesandbox isn't a valid URL.

**Comment by codec-abc** [comment]
Yeah I mean [codesandbox](https://codesandbox.io/s/w02m7jm3q7) which it **is** a 404

**Comment by codec-abc** [comment]
So the issue remain.

**Comment by timdorr** [comment]
This is a duplicate of #3848
