### ISSUE TITLE
Undefined variables used in test examples for connected components

### ISSUE THREAD

**Issue by retagaine** [reduxjs/redux#3868]
## What docs page needs to be fixed?
https://github.com/reduxjs/redux/blob/master/docs/recipes/WritingTests.md

- **Section**: Connected components
- **Page**: https://redux.js.org/recipes/writing-tests

## What is the problem?
There are a few variables which are undefined in the examples (I was only interested in testing for connected components, so I didn't get around to reading the rest of the document).

For example:
```javascript
import { connect } from 'react-redux'

const App = props => {
  return <div>{props.user}</div>
}

export default connect(mapStateToProps)(App)
```

`mapStateToProps` is undefined here, and
```javascript
// test-utils.js
import React from 'react'
import { render as rtlRender } from '@testing-library/react'
import { createStore } from 'redux'
import { Provider } from 'react-redux'

function render(
  ui,
  {
    initialState,
    store = createStore(reducer, initialState),
    ...renderOptions
  } = {}
) {
  function Wrapper({ children }) {
    return <Provider store={store}>{children}</Provider>
  }
  return rtlRender(ui, { wrapper: Wrapper, ...renderOptions })
}

// re-export everything
export * from '@testing-library/react'
// override render method
export { render }
```
`reducer` is undefined here.

## What should be changed to fix the problem?
I'm not familiar with Redux, but it would be nice to have minimal working examples for `mapStateToProps` and `reducer`. I tried running this test out of `create-react-app` boilerplate and it errored out. If fixing this part of the docs is approachable by a beginner in a few days' time I can certainly try and fix it in my spare time.

**Comment by timdorr** [comment]
Is this not intentional? We don't want to focus on how you set up your reducers and mapStateToProps functions, as those can be done in a bunch of different ways. Instead, we want to abstract those away so that we can focus on what the testing code and applying it to your own tests (which will obviously be different than this code).

**Comment by markerikson** [comment]
maybe just add a comment saying "Import your own reducers and components as appropriate" ?

**Comment by MatanBobi** [comment]
> Is this not intentional? We don't want to focus on how you set up your reducers and mapStateToProps functions, as those can be done in a bunch of different ways. Instead, we want to abstract those away so that we can focus on what the testing code and applying it to your own tests (which will obviously be different than this code).

That was indeed intentional.
Np @markerikson I'll update it asap :)
