### ISSUE TITLE
Need clarification about using "feature folders" in doc/style-guide

### ISSUE THREAD

**Issue by ZYinMD** [reduxjs/redux#3869]
## What docs page needs to be fixed?

- **Section**: style-guide
- **Page**: style-guide: best practices

Specifically, it's about [this part](https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks).

## What is the problem?
I'm trying to follow the style-guide to put my react redux code into feature folders, but encountered a problem: if `featureA/componentA` and `featureB/componentB` both dispatch to `sliceX`, in which folder should I write the reducer for `sliceX`?

Note: there are 3 possible scenarios: 
1. `A` and `B` dispatch the same actions, which means I can certainly write a duck, the question is where to put the duck.
2. `A` and `B` dispatch different actions `actionA` and `actionB` to the same slice, which means I could still write a duck, but it'd also make sense to define `actionA` inside `featureA`, define `actionB` in `featureB`. If so, the question becomes what folder to put the reducer.
3. Another slice `SliceY` also responds to `actionA`, which makes it impossible to use `createSlice` for `sliceX` to begin with. The question becomes where to put `reducerX`.

## What should be changed to fix the problem?
Give a few words of advice / recommendations on these scenarios. I'm sure they happen in every project.

(The official answer may be "it's up to you", but please at least give some opinions on some practices that may occur: e.g. "write everything in A and import into B" or "write in a 3rd centralized location like `src/redux`)

**Comment by timdorr** [comment]
Components of different features can certainly dispatch actions from other features. That's already implied by having the `common` folder in the example. 

A feature folder doesn't have to have all of the elements in the example. You can have a feature that's just a slice, or you can have a feature that's just components. So for your 1st and 2nd examples, you would put the duck in its own feature folder, separately from A and B. The 3rd example wouldn't be a recommended way to structure your application, as you can't use a slice.

I don't think we need to document this. This should already be apparent from the document.

**Comment by ZYinMD** [comment]
Hi @timdorr, regarding your comment about the 3rd example, I must be missing something obvious:  the style guide strongly recommends [Allow Many Reducers to Respond to the Same Action](https://redux.js.org/style-guide/style-guide#allow-many-reducers-to-respond-to-the-same-action).  It's also very common in real life, for instance `dispatch((dataFetched(data))`. Many reducers in different slices will respond to this one action, and you can't use `createReducer` to write them.

Several other places in the style guide are actually encouraging this pattern in one way or another:
[Model Actions as Events, Not Setters](https://redux.js.org/style-guide/style-guide#model-actions-as-events-not-setters)
[Put as Much Logic as Possible in Reducers](https://redux.js.org/style-guide/style-guide#put-as-much-logic-as-possible-in-reducers)
[Avoid Dispatching Many Actions Sequentially](https://redux.js.org/style-guide/style-guide#avoid-dispatching-many-actions-sequentially)

**Comment by markerikson** [comment]
@ZYinMD The point is that:

- Any given action is either primarily associated with a given slice (and thus defined inside of a `createSlice` call), or generic enough it should be defined somewhere else (possibly using `createAction`)
- In order for slice A to respond to actions defined in slice B, it either explicitly imports an action creator from B (if using Redux Toolkit) or an action constant (if written by hand), or it copy-pastes the action type string manually

Where those _files_ live is entirely up to you.

**Comment by ZYinMD** [comment]
Hi @markerikson thanks! Yes I know it's up to me where to put my files, but I created this issue specifically about docs / style-guide / [Structure Files as Feature Folders or Ducks](https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks), which talks about where to put my files.

The good news is, from yours and Tim's answer, I have gotten the conclusion that I'm happy with:
1. if `featureA` and `featureB` both dispatch to `sliceX`, create a `featureX` folder and put the duck there. 
1. if `sliceX` and `sliceY` both respond to `actionA`, put both reducers in `featureA` folder. Note that it's impossible to use `createSlice` in this case.
1. if both `sliceX` and `sliceY` responds to both `actionA` and `actionB`, then I need 4 feature folders `X` `Y` `A` `B`.

This may be obvious to you, but it's surprisingly hard to see for someone who's used to put all reducers in a centralized place, where the directory and file tree is organized to mirror the redux store shape.

**Comment by markerikson** [comment]
I'm not sure where you're getting the "impossible to use `createSlice`" bit.  It's fine to use `createSlice` in general. The only potential problem is if `sliceX` needs to import an action from `sliceY`, while `sliceY` _also_ needs to import an action from `sliceX`, thus causing a cyclical dependency issue.

If that happens, then you need to break the cycle yourself somehow, likely by defining that specific action type using `createAction` in another file.

See https://redux-toolkit.js.org/usage/usage-guide#exporting-and-using-slices

**Comment by ZYinMD** [comment]
Hi @markerikson, because actions created by `createSlice` have prefixes. 

Suppose I want both `sliceX` and `sliceY` to respond to action `foo`. If I use `creatSlice` to create `sliceX` and action `foo`, then `foo.type` will be `"X/foo"`. I can export it, but this action is tightly coupled with `sliceX`. 

If I use `foo.type` to create `sliceY` by calling `createSlice`, then `reducerY` won't respond to `foo`, because it's only watching for action type `Y/X/foo`.

Instead, I can use `createReducer` to create `reducerY`, and pass in `foo.type`, it'll work, but semantically it's bad because `reducerY` is now responding to action type `X/foo`.

Therefore, the solution is to use `createAction` to define `foo` without any prefix, and use `createReducer` to define both `reducerX` and `reducerY`.

If you ask me, the prefix argument in `createSlice` should be optional (or at least `""` should be allowed). Forcing a prefix doesn't make sense, it's essentially saying "all these actions belong to this prefix, which is coupled to this slice".

**Comment by markerikson** [comment]
> "all these actions belong to this prefix, which is coupled to this slice".

Yes, this is _entirely_ intentional :)

As I said earlier, any action can be categorized as either primarily belonging to a given slice, in which case you define it inside of that `createSlice`, or "completely unrelated to any slice", in which case you use `createAction()` to generate it separately.

Also, you may be missing the fact that `createSlice` has an `extraReducers` field, which is how it can respond to actions that were defined outside of that slice:

https://redux-toolkit.js.org/api/createSlice#extrareducers

And it is _also_ entirely intentional that _any_ reducer may respond to _any_ action that is dispatched, even if it "belongs" to another slice.  That's not "semantically bad" - that's _how it's supposed to work_.

**Comment by ZYinMD** [comment]
Thanks very much for clarifying it's inentional.

> you may be missing the fact that createSlice has an extraReducers field.

Yes I did miss it! I thought I read the doc quite carefully, but still missed it. 

In case there are other users who're like me, I'd suggest adding an extra sentence to mention it more explicitly at the end of [this paragraph](https://github.com/reduxjs/redux-toolkit/blame/master/docs/usage/usage-guide.md#L520). Maybe something like "In such cases, make sure to check the [extraReducers API] (link)."
