### ISSUE TITLE
Remove "symbol-observable" from .d.ts files

### ISSUE THREAD

**Issue by g-plane** [reduxjs/redux#3888]
### What is the current behavior?

The `.d.ts` files in npm still contains "symbol-observable", but Redux doesn't depends on "symbol-observable" any more.

### Steps to Reproduce

In the header of [`.d.ts`](https://cdn.jsdelivr.net/npm/redux/index.d.ts) file:

```ts
/// <reference types="symbol-observable" />
```

This triple-slash is unnecessary, otherwise it will break in some cases, such as using Deno.

### What is the expected behavior?

Remove that triple-slash comment and it should work.

### Environment Details

Redux 4.0.5

**Comment by timdorr** [comment]
This is already removed on master.

**Comment by g-plane** [comment]
Ok. Will you release a new version? Last version was in last year.
