### ISSUE TITLE
[Docs] Remove note about fetch

### ISSUE THREAD

**Issue by croraf** [reduxjs/redux#3890]
## What docs page needs to be fixed?

https://redux.js.org/advanced/async-actions#note-on-fetch

## What is the problem?

It is obsolete and not important for a redux tutorial

## What should be changed to fix the problem?

Remove the entire note.

**Comment by timdorr** [comment]
Can you make a PR for this? That's a better format than an issue.

**Comment by croraf** [comment]
You cannot decide if this is to be accepted or not?

**Comment by croraf** [comment]
https://github.com/reduxjs/redux/pull/3893
