### ISSUE TITLE
[Docs] inserting Korean redux docs link to redux documentation

### ISSUE THREAD

**Issue by shawnscoding** [reduxjs/redux#3895]
## What docs page is being added or updated?

- **Section**:
- **Page**:

## For Adding New Content
Hi. a few days ago, I told you I'd like to translate redux docs into Korean and give you the link to it to post it in the redux docs. The thing is that it turns out there had already been Korean redux docs on the internet https://ko.redux.js.org/ and it is really well written. So I thought there would be no point for me to create one.
I asked the author if he is ok to display the link to this doc. I haven't got answered but I assume he'd likely be happy.
If he says he's ok, I will let you know or I will write the link to the redux doc and do PR by myself if you want.

You might want to contact him
His Github: https://github.com/deminoth
Thanks!

**Comment by timdorr** [comment]
Fixed in #3897
