### ISSUE TITLE
Docs: Add example for Reusing Reducer Logic

### ISSUE THREAD

**Issue by irvanherz** [reduxjs/redux#3900]
## What docs page needs to be fixed?

- **Section**: Recipes
- **Page**: Structuring Reducers -> Reusing Reducer Logic

## What is the problem?
This part explains some methods on how to reusing reducer. But I think this part should explains more on configuring action creator.
## What should be changed to fix the problem?
Please add example how to write action creators for these extended reducers.

**Comment by markerikson** [comment]
Can you clarify what you mean by "configuring action creators" ?

**Comment by irvanherz** [comment]
> ```js
> ...
> const rootReducer = combineReducers({
>   counterA: counter,
>   counterB: counter,
>   counterC: counter
> })
> ```
>
> Unfortunately, this setup has a problem. Because combineReducers will call each slice reducer with the same action

The documentation has solution for this such problems.
> ```js
> function createCounterWithNamedType(counterName = '') {
>   ...
> }
> 
> function createCounterWithNameData(counterName = '') {
>   ...
> }
> const rootReducer = combineReducers({
>   counterA: createCounterWithNamedType('A'),
>   counterB: createCounterWithNamedType('B'),
>   counterC: createCounterWithNamedType('C')
> })
> 
> store.dispatch({ type: 'INCREMENT_B' })
> console.log(store.getState())
> // {counterA : 0, counterB : 1, counterC : 0}
> ```

What missing here is how to do `dispatch({ type: 'INCREMENT_B' })`; with action creators.
