### ISSUE TITLE
Contribution guide and website Readme improvements

### ISSUE THREAD

**Issue by Roshanjossey** [reduxjs/redux#3901]
## What docs page needs to be fixed?

https://github.com/reduxjs/redux/blob/master/CONTRIBUTING.md
https://github.com/reduxjs/redux/blob/master/website/README.md

## What is the problem?

 - The link for docs path in https://github.com/reduxjs/redux/blob/master/CONTRIBUTING.md#docs leads to 404. It should point to `https://github.com/reduxjs/redux/blob/master/website/`
 - The commands in https://github.com/reduxjs/redux/blob/master/website/README.md uses `yarn` to run scripts. However, there's no `yarn.lock` file. There is `package-lock.json` though. I think this conflict should be avoided to make sure that everybody installs same version of packages. 

## What should be changed to fix the problem?

 - [ ] Fix link for docs path
 - [ ] Either update the commands or use yarn for installing packages and create yarn.lock file

**Comment by markerikson** [comment]
The docs link should actually point to the top-level `/docs/` folder.  We very briefly moved the docs content into `/website/docs/`, then reverted it, and this got missed.

Yeah, we use NPM for all of the package management here in the repo.

Can you file a PR to update both files?

**Comment by Roshanjossey** [comment]
Sure, I'll do it tomorrow
