### ISSUE TITLE
return promise from reducer to allow state update by web worker

### ISSUE THREAD

**Issue by lolero** [reduxjs/redux#3904]
### What is the new or updated feature that you are suggesting?
I want to execute async code inside a reducer function.

### Why should this feature be included?
I understand that async logic should be handled by middleware like thunk or saga. I use saga for all my async action handling such as AJAX request or any other async logic triggered by actions.

However, I have a high I/O application and my UI is freezing when there are many parallel processes running in my sagas.

I started using web workers to handle the heavy calculations and that helped a lot but it appears like the app still drags because of the state updates that happen in the `switch` that handles the actions inside my reducer functions.

So I thought I could also use web workers to perform the state updates in the reducers that get hit frequently. But that makes the reducer function asynchronous and redux crashes when the reducer returns a `Promise<State>` instead of the `state` itself.

```typescript
// Reducer
import { proxy, wrap } from 'comlink';
import WebWorker from 'worker-loader!./webWorker';
import { webWorker } from './webWorker';

const webWorker = wrap<typeof webWorker>(new WebWorker());
function simpleReducer(
  state: SimpleReducer = simpleInitialState,
  action: SimpleAction,
): Promise<SimpleReducer> {
  switch (action.type) {
    case SimpleActionTypes.INFREQUENT_ACTION:
      return {
     ;
    case SimpleActionTypes.FREQUENT_ACTION:
      return webWorker(proxy(state), proxy(action));
    default:
      return state;
  }
}

// WebWorker
import { expose } from 'comlink';
function webWorker(state: SimpleReducer) {
  return {
    ...state,
    frequentActionCount: state.frequentActionCount + 1,
  };
}

expose(webWorker);
```

I have looked for other ways to have a separate thread handle the state update process but have not found a way to do it. Any help would be greatly appreciated!

**Comment by markerikson** [comment]
Sorry, that's exactly what you should _never_ do in a reducer:

https://redux.js.org/style-guide/style-guide#reducers-must-not-have-side-effects

You may want to read this recent article and discussion with links on using Redux with web workers, though:

https://www.reddit.com/r/javascript/comments/j6v9iu/redux_in_web_workers_offmainthread_redux_reducers/

**Comment by lolero** [comment]
Ok.  Thanks for the quick reply! :)
