### ISSUE TITLE
Docs: The website footer has 2 same name links

### ISSUE THREAD

**Issue by nullpoo** [reduxjs/redux#3908]
## What docs page needs to be fixed?

- **Section**: Docs items of the footer
- **Page**: The website (https://redux.js.org/)

## What is the problem?

<img width="235" alt="スクリーンショット 2020-10-19 18 26 02" src="https://user-images.githubusercontent.com/1692842/96426740-9871de80-1238-11eb-904c-c2f78440997d.png">

https://github.com/reduxjs/redux/blob/b3165d0cbd0d8f48142284807d764160df26d6fa/website/docusaurus.config.js#L64-L75

The footer has 2 `Tutorial` items.

## What should be changed to fix the problem?

Probably we can give another link name for `tutorials/essentials/part-1-overview-concepts` one.
Like `Overview and Concepts`?

**Comment by markerikson** [comment]
Can you file a PR to remove the "Basics" tutorial link? That should have been removed, and I missed it previously.
