### ISSUE TITLE
Documentation page consuming too many cpu cycles

### ISSUE THREAD

**Issue by victordeleau** [reduxjs/redux#3910]
When I browse the documentation website (only when it is an active tab) with Firefox it consumes too many cpu cycles for no reasons.

### Prior Issues

This [closed issue](https://github.com/reduxjs/redux/issues/3688) seems to be related.

### What is the current behavior?

Energy impact is medium to high for no reason in the task manager of Firefox 78.3.0esr. Fan gets noisy.

### Steps to Reproduce

Just browse the documentation pages using Firefox. Apart from 78.3.0esr I haven't tried other versions. The issue doesn't appear using Chrome 86.

### What is the expected behavior?

It's a static website with no fancy stuff, it shouldn't consume that many cpu cycles.

### Environment Details

I'm using Debian 10 and Firefox 78.3.0esr.

![screenshot](https://user-images.githubusercontent.com/26342960/96630274-c0b61780-12e2-11eb-960f-c963dea561d1.png)

**Comment by markerikson** [comment]
Does this maybe have something to do with the CodeSandboxes being loaded? Does this happen on _all_ pages, or just _specific_ pages?

**Comment by victordeleau** [comment]
How can I check if CodeSandboxes are loaded ?

It doesn't seem to happen on all pages. For example it happens on https://redux.js.org/tutorials/essentials/part-1-overview-concepts but not on https://redux.js.org/recipes/configuring-your-store.

After disabling my cache and refreshing, consumption got down to 7, which is better but still high. Also, consumption seems to increase whenever I move my mouse on the page, even if it's just over some normal text. Could over-consumption be due to some kind of mouse tracking script ?

**Comment by markerikson** [comment]
Hmm. The tutorial page doesn't have any CodeSandboxes, but it does have a large animated gif.

**Comment by victordeleau** [comment]
Indeed it's quite large, but opening the GIF in a standalone tab doesn't make my cpu sweat. Thank you for your help though

**Comment by markerikson** [comment]
Yeah.  If you or anyone else can actually pinpoint a pattern in which pages are burning more CPU, and ideally _why_ it's happening, let us know, but I don't think there's anything specific we can do atm.
