### ISSUE TITLE
There is minor syntax error in sample code

### ISSUE THREAD

**Issue by WeiLi512** [reduxjs/redux#3921]
## What docs page needs to be fixed?

- **Section**:
![image](https://user-images.githubusercontent.com/50083174/97336243-e50d8780-18d2-11eb-9512-53a657b5d47a.png)

- **Page**:
https://github.com/reduxjs/redux/blob/master/docs/recipes/structuring-reducers/UpdatingNormalizedData.md#task-based-updates

## What is the problem?
`const featureReducers = createReducer({}, {
    ADD_COMMENT : addComment,
};`
There is a syntax error at the end of the line. there isn't matched parenthesis.
Also, didn't mention where `createReducer` came from?

## What should be changed to fix the problem?
Need to change the code

**Comment by timdorr** [comment]
Can you submit a PR to fix this?

**Comment by WeiLi512** [comment]
thanks, @juzhiyuan @markerikson @timdorr
