### ISSUE TITLE
Small error in code presented in Redux Fundamentals - part 5

### ISSUE THREAD

**Issue by gabrielpaesschulz** [reduxjs/redux#3933]
## What docs page needs to be fixed?

- **Section**:
Redux Fundamentals/UI and React
- **Page**:
[UI and React](https://redux.js.org/tutorials/fundamentals/part-5-ui-react)

## What is the problem?
_src/features/header/Header.js_
In the example code presented we have

`onKeyDown={handleSubmit}`

but there is no handleSubmit function in this component.

## What should be changed to fix the problem?

`onKeyDown={handleSubmit}`

to

`onKeyDown={handleKeyDown}`

in the same code we have

`const handleChange = e => setText(e.target.value`

lacking the final )

**Comment by markerikson** [comment]
Yep.  Can you submit a PR to fix these?
