### ISSUE TITLE
There is a typo in the Redux Fundamentals Part 3 document.

### ISSUE THREAD

**Issue by sungik-choi** [reduxjs/redux#3937]
## What docs page needs to be fixed?

- **Section**: Redux Fundamentals 
- **Page**: [Part 3 - Splitting Reducers](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#splitting-reducers)

## What is the problem?

There is a typo in the Redux Fundamentals Part 3 - Splitting Reducers.
`state.todos` should be changed to `state`. 
Because the reducer is splitted, the key `todos` is unnecessary.

---

**Original Document**

This is called reducer composition, and it's the fundamental pattern of building Redux apps.

Here's what the updated reducer looks like after we handle those actions:

src/features/todos/todosSlice.js
```js
export default function todosReducer(state = initialState, action) {
  switch (action.type) {
    case 'todos/todoAdded': {
      return [
        ...state,
        {
         // state.todos is undefined  
          id: nextTodoId(state.todos),
          text: action.payload,
          completed: false
        }
      ]
    }
   /* ... */
}
```

## What should be changed to fix the problem?

```js
export default function todosReducer(state = initialState, action) {
  switch (action.type) {
    case 'todos/todoAdded': {
      return [
        ...state,
        {
           // state.todos => state
          id: nextTodoId(state),
          text: action.payload,
          completed: false
        }
      ]
    }
   /* ... */
}
```

**Comment by markerikson** [comment]
Good catch, thanks!
