### ISSUE TITLE
[Docs-update] Introduction ecosystem contains deprecated and archived repositories

### ISSUE THREAD

**Issue by slim-hmidi** [reduxjs/redux#3941]
## What docs page needs to be fixed?

- **Section**: Introduction
- **Page**: Ecosystem

## What is the problem?
I find that there are some libraries mentioned in the documentation that are deprecated or archived. 
The list of repositories that I checked:

**Deprecated:**

- Angular-redux/store
- Jumpsuit/jumpstate

**Archived:**
- Redux-insights
- Redux-ui
- Redux-devtools-inspector
- Redux-devtools-chart-monitor
- Redux-little-router

## What should be changed to fix the problem?
Removing the libraries from the ecosystem section.

**Comment by markerikson** [comment]
Please feel free to file PRs that update that page!
