### ISSUE TITLE
Small typo in export statement

### ISSUE THREAD

**Issue by gauravsoti1** [reduxjs/redux#3956]
## What docs page needs to be fixed?

- **Converting the Todos Reducer**:
- **Tutorials -> Redux Fundamentals**:

## What is the problem?
`
const todosSlice = createSlice({
  name: 'todos',
  initialState,
  reducers: {
    todoAdded(state, action) {
      const todo = action.payload
      state.entities[todo.id] = todo
    },
    todoToggled(state, action) {
      const todoId = action.payload
      const todo = state.entities[todoId]
      todo.completed = !todo.completed
    }
  }
})

export const { todoAdded, todoDeleted } = todosSlice.actions`

## What should be changed to fix the problem?
In export statement, todoDeleted should be changed to todoToggled

**Comment by timdorr** [comment]
Can you submit a PR for this instead?

**Comment by gauravsoti1** [comment]
@timdorr Done. PR: https://github.com/reduxjs/redux/pull/3957
