### ISSUE TITLE
the npm script test not set NODE_ENV environment variable which result in error occurs when run `npm test`

### ISSUE THREAD

**Issue by yibingxiong** [reduxjs/redux#3965]
Thanks to develop such a good library.

### Prior Issues

not found

### What is the current behavior?

when run npm test. Error occurs; Like the following.

```
> jest

 FAIL  test/utils/warning.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
```

### Steps to Reproduce

1. git clone this repo
2. npm install
3. npm test

Error occurs.

I found that is because the environment variable NODE_ENV not set.

### What is the expected behavior?

the unit test by jest passed;

### Environment Details

master code

**Comment by timdorr** [comment]
Jest already does this for you: https://jestjs.io/docs/en/environment-variables#node_env

It would appear something else is going on in your local environment if that is not working. Sorry, but we can't provide support for that.

**Comment by yibingxiong** [comment]
Ok. Thank you. I will try to find why it dosn't work in my machine.
