### ISSUE TITLE
[Tutorial Docs] Updating Initial state to account for expected changes in UI (PR: #3964)

### ISSUE THREAD

**Issue by tylerthedeveloper** [reduxjs/redux#3967]
## What docs page needs to be fixed?

- **Section**: 
redux/docs/tutorials/essentials

- **Page**:
part-4-using-data.md

## What is the problem?

We change the UI to state that we will expect posts to have a reactions property in the ReactionButtons component, but we both don't check for null or update the initial state. This will break when trying to add a new post and only is resolved by going to the next step. It is important to inform the reader to keep mind of changing default state.

## What should be changed to fix the problem?

Here is a PR that updates the initial state and follows parity from other parts of the tutorial - https://github.com/reduxjs/redux/pull/3964

**Comment by markerikson** [comment]
I think this should be resolved by #4153 .
