### ISSUE TITLE
How to ensure that the data in the store is immutable

### ISSUE THREAD

**Issue by 787941287** [reduxjs/redux#3971]
## New Features
 a immutable store
### Why should this feature be included?
i can change store with getstate()

**Comment by markerikson** [comment]
Yes, `getState()` just returns a reference to your data.  The need for you to maintain immutable updates is entirely documented:

https://redux.js.org/faq/immutable-data#what-approaches-are-there-for-handling-data-immutability-do-i-have-to-use-immutable-js

Please use our official Redux Toolkit package, which makes writing immutable updates easier, and eliminates accidental mutations:

https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#immutable-updates-with-immer
