### ISSUE TITLE
[Docs: Rephrase] Explain correctly what a thunk is

### ISSUE THREAD

**Issue by Sakai-san** [reduxjs/redux#3972]
## What docs page needs to be fixed?

- **Section**: Recipes
- **Page**: Usage With TypeScript

## What is the problem?
In the paragraph [Usage with Redux Thunk](https://redux.js.org/recipes/usage-with-typescript#usage-with-redux-thunk), the concept of thunk is wrongly explained.

> A thunk is a function that returns another function that takes parameters dispatch and getState.

This definition corresponds to a **thunk action creator** but not to a thunk.

## What should be changed to fix the problem?
Explain correctly what a thunk is.

Here is a suggestion : 
> A thunk is a function that wraps an expression for delaying the evaluation of that expression. In Redux, a thunk takes parameters dispatch and getState.

**Comment by samarmohan** [comment]
Wasn't this fixed in #3973?

**Comment by markerikson** [comment]
Looks like it, yeah.
