### ISSUE TITLE
Documentation Fix: I want a link to a Top title in the sidebar

### ISSUE THREAD

**Issue by sakito21** [reduxjs/redux#3994]
## What docs page needs to be fixed?

Sidebar for the entire page.

## What is the problem?

I'm having trouble sharing a document link.

e.g.
I want to read the `Understanding Redux` , so I want to share the link.

![スクリーンショット 2021-01-15 15 32 42](https://user-images.githubusercontent.com/15010907/104689985-ee2a2a00-5746-11eb-8235-8dac0b36429c.png)

However, I can't browse `https: //redux.js.org/understanding/`.

I can't share the whole thing with this.

## What should be changed to fix the problem?

I want a link in Top title.

How about making a top page for each item?

This is a sample I imagine.
![スクリーンショット 2021-01-15 15 38 11](https://user-images.githubusercontent.com/15010907/104690490-ddc67f00-5747-11eb-93a1-8cc6ae00f776.png)

I will make a PR if you like.

**Comment by markerikson** [comment]
There is no page for `/understanding`.  It's a category, so there's nothing to link to.

**Comment by sakito21** [comment]
@markerikson 
I want to share the entire category with a link.
What should I do in this case?

**Comment by markerikson** [comment]
I'd just copy the link to the first actual page in the category (in this case, "Motivation").
