### ISSUE TITLE
Why redux calls all reducers every time an action is dispatched ? Meanwhile mostly in real world app we just want to update a specific state in the store with a specific reducer ? 

### ISSUE THREAD

**Issue by papercoding22** [reduxjs/redux#3999]
Is it good for performance when a large app has over 100 reducers, when it calls 100 reducers with 99 redundant calls.

As I read from the source code, whenever dispatch an action with a specific type to the store, it will call the combination reducer function and loop through all over the reducers and call each one to find the matching action type which time complexity is O(n). But in real world app, for myself, I mostly just need to update a specific state in the store at a specific reducer and with specific action.

Here is a snippet of code in `combineReducers.ts`

```
return function combination(
    state: StateFromReducersMapObject<typeof reducers> = {},
    action: AnyAction
  ) {
    if (shapeAssertionError) {
      throw shapeAssertionError
    }

    if (process.env.NODE_ENV !== 'production') {
      const warningMessage = getUnexpectedStateShapeWarningMessage(
        state,
        finalReducers,
        action,
        unexpectedKeyCache
      )
      if (warningMessage) {
        warning(warningMessage)
      }
    }

    let hasChanged = false
    const nextState: StateFromReducersMapObject<typeof reducers> = {}
    for (let i = 0; i < finalReducerKeys.length; i++) {
      const key = finalReducerKeys[i]
      const reducer = finalReducers[key]
      const previousStateForKey = state[key]
      const nextStateForKey = reducer(previousStateForKey, action)
      if (typeof nextStateForKey === 'undefined') {
        const errorMessage = getUndefinedStateErrorMessage(key, action)
        throw new Error(errorMessage)
      }
      nextState[key] = nextStateForKey
      hasChanged = hasChanged || nextStateForKey !== previousStateForKey
    }
    hasChanged =
      hasChanged || finalReducerKeys.length !== Object.keys(state).length
    return hasChanged ? nextState : state
  }
```

So I do some experiment in the code, when dispatching an action, I add one more field call `targetState` which is a specific state key to let the store knows which state I want to update and where to find the exact reducer and just call it, so that time complexity now is O(1).

this is my code, it just for experiment, so it might be not good enough.

```
dispatch({type: 'ADD_TODO', targetState: 'todos'})
```

```
    let hasChanged = false
    let nextState: StateFromReducersMapObject<typeof reducers> = {}

    if (action.targetState) {
      nextState = { ...state }
      const reducer = finalReducers[action.targetState]
      const prevTargetState = state[action.targetState]
      const nextTargetState = reducer(prevTargetState, action)
      if (typeof nextTargetState === 'undefined') {
        const errorMessage = getUndefinedStateErrorMessage(
          action.targetState,
          action
        )
        throw new Error(errorMessage)
      }
      nextState[action.targetState] = nextTargetState
      hasChanged = hasChanged || nextTargetState !== prevTargetState
    } else {
      for (let i = 0; i < finalReducerKeys.length; i++) {
        const key = finalReducerKeys[i]
        const reducer = finalReducers[key]
        const previousStateForKey = state[key]
        const nextStateForKey = reducer(previousStateForKey, action)
        if (typeof nextStateForKey === 'undefined') {
          const errorMessage = getUndefinedStateErrorMessage(key, action)
          throw new Error(errorMessage)
        }
        nextState[key] = nextStateForKey
        hasChanged = hasChanged || nextStateForKey !== previousStateForKey
      }
      hasChanged =
        hasChanged || finalReducerKeys.length !== Object.keys(state).length
    }
    return hasChanged ? nextState : state
```

Thank you for reading

**Comment by NguyenChiTrung1310** [comment]
duno

**Comment by JustFly1984** [comment]
iIt is by design. Not all real world applications updating only one reducer per action dispatch. For example if you have application with authentication, on user logout you really want to cleanup all (most of)reducers, so you do not leak any data, so you can dispatch an action LOGOUT, which resets current reducers state to initial. You do not really want to dispatch 99 actions to cleanup 99 reducers, you want to dispatch single action. Same pattern is useful for other use cases.

In case you have 99 reducers, it is very possible that you want to split your reducers to several providers, or use other optimization technics like code splitting and lazy loading depends if your app architecture allows.

**Comment by papercoding22** [comment]
Thank for your comment @JustFly1984. Yes, we still need to one action to update multiple states in multiple reducers or reset all states at once, there is another solution for that which is simpler than declare all the same action type, let's say 'RESET_STATE' in all reducers. My solution is optional and doesn't change anything from normal flow of Redux, so I set the `targetState` is optional when dispatching an action, it still goes through all reducers if users don't want to update at the targetState,  if we knows exactly what we want to update, we will pass the `targetState`, and it will skip redundant reducers.

**Comment by Akram-Adel** [comment]
I think @papercoding22 has a good idea here, but I believe this violates the [Flux Pattern](https://facebook.github.io/flux/docs/in-depth-overview/) especially in this part:

> When an action creator provides the dispatcher with a new action, all stores in the application receive the action via the callbacks in the registry.

So if you have multiple reducers that are distinct from one another, my suggestion is just to split your store into multiple redux stores. Although I read in the docs that this is also not recommended. (again, because this violates the Flux Pattern)

**Comment by markerikson** [comment]
This has been covered in the FAQ since 2016:

https://redux.js.org/faq/performance#wont-calling-all-my-reducers-for-each-action-be-slow

**Comment by papercoding22** [comment]
> This has been covered in the FAQ since 2016:
> 
> 
> 
> https://redux.js.org/faq/performance#wont-calling-all-my-reducers-for-each-action-be-slow

Thank you
