### ISSUE TITLE
[Docs: Rewrite] Unexplained switch to separate <PostExcerpt> component usage

### ISSUE THREAD

**Issue by sysrage** [reduxjs/redux#4000]
## What docs page needs to be fixed?

- **Section**: Redux Essentials
- **Page**: Async Logic and Data Fetching

## What is the problem?

In the section "Displaying Loading State", the example code suddenly switches to using `<PostExcerpt>`, but that wasn't used in the last set of instructions where this portion of code is used. Anybody following-along the guide is forced to scroll to the bottom of this section to open the code sandbox and see exactly how the `<PostExcerpt>` component is built. The code sandbox from the previous section didn't include `<PostExcerpt>` as a separate component.

Users can ignore this and continue using the single-component layout, but it makes things a bit confusing when they get to the profiling section and don't see a separate `<PostExcerpt>` component. It also makes it difficult to then wrap `React.memo()` around it.

## What should be changed to fix the problem?

Use the separate `<PostExcerpt>` component in the previous section.

**Comment by markerikson** [comment]
Hmm. I know I went back and forth on whether to have that component a few times while writing the tutorial. It's very possible that I didn't end up showing that one clearly.

**Comment by ABDOGH98** [comment]
Hi 
I find the same problem there is any solution for that , Thanks

**Comment by markerikson** [comment]
Resolved by #4153
