### ISSUE TITLE
SinglePostPage doesn't fetch post if loaded directly (not via the list)

### ISSUE THREAD

**Issue by wwitek** [reduxjs/redux#4001]
## What docs page needs to be fixed?

Section: Redux Essentials
Page: Using Redux Data

## What is the problem?
When `SinglePostPage` is loaded directly (by typing _/posts/{postId}_ in the address bar), the page will show _Post not found_ (even if the post actually exists). The only way to view the post is to go through the `PostsList`

## What should be changed to fix the problem?
`SinglePostPage` and `EditPostForm` should be able to fetch requested item if the page is loaded directly

**Comment by markerikson** [comment]
Yeah, I deliberately opted not to handle that particular use case.  Feel free to try implementing it yourself, though!
