### ISSUE TITLE
Title is misleading. counter-vanilla (against vanilla) vs a counter in Vanilla js

### ISSUE THREAD

**Issue by rahimimo** [reduxjs/redux#4007]
## What docs page needs to be fixed?
The title
- **Section**:
- **Page**:

## What is the problem?
I was trying to read react tool kit and. I was expecting to get normal redux (vanilla redux) vs counter-vanila redux which was supposed to be RTL, but then I got the counter written in vanilla js :D and I mixed up

**Comment by markerikson** [comment]
The example has been named that since Dan wrote it in 2016. Sorry you were confused, but we're not going to rename it.
