### ISSUE TITLE
Why you don't accept async actions in Redux?

### ISSUE THREAD

**Issue by samislam** [reduxjs/redux#4013]
I'm new to Redux, but I was just wondering, why you don't accept async actions in Redux? Why it's our job (developers) to use middleware such as redux-thunk in order to handle async actions? I've written a simple imagination code  of how Redux could (probably) handle both async and sync actions without throwing any annoying error saying: "Actions must be plain objects. Use custom middleware for async actions.", see:

```
const asyncActionCreator = async ()=>{
    const response = await fetch("https://jsonplaceholder.typicode.com/posts");
    return {
        type: "FETCH_POSTS",
        payload: response
    }
}

const SyncActionCreator = () => {
  return {
        type: "SYNC_ACTION",
        payload: "Just a normal synchronous action"
    }
}

function dispatch(action){
    Promise.resolve(action).then(actionObj => console.log(actionObj))
}

dispatch(asyncActionCreator()) // you can copy the entire code and test it in browser's console, or codepen.
dispatch(SyncActionCreator()) //
```
**With all respect. 
Islam.**

**Comment by timdorr** [comment]
This is already answered in the FAQ: https://redux.js.org/faq/actions#how-can-i-represent-side-effects-such-as-ajax-calls-why-do-we-need-things-like-action-creators-thunks-and-middleware-to-do-async-behavior
