### ISSUE TITLE
Reselect does not optimize application performance

### ISSUE THREAD

**Issue by reynaldysaputra** [reduxjs/redux#4023]
### What is the current behavior?
I'm learning about Redux fundamentals in the redux documentation,
to improve application performance using shallowEqual or reselect correct? But I had a little trouble.

if you see this codepen:
https://codesandbox.io/s/gracious-framework-jv0g8?fontsize=14&hidenavigation=1&theme=dark

that's a fundamental redux lesson using shallowEqual, and when you click select on one of the todos, it will re-render the child only not to the parent (see console log if you want to know)

But the problem is here when I use reselect it will re-render the child and parent of the application (see console log)

https://codesandbox.io/s/gracious-beaver-ogw5t?fontsize=14&hidenavigation=1&theme=dark

### What is the expected behavior?
it should be if we use reselect it shouldn't re-render the parent when selecting todo child.

**Comment by markerikson** [comment]
Yes, the behavior there is explicitly mentioned in the tutorial under https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#memoizing-selectors-with-createselector :

> This actually behaves a bit differently than the shallowEqual comparison function does. Any time the state.todos array changes, we're going to create a new todo IDs array as a result. That includes any immutable updates to todo items like toggling their completed field, since we have to create a new array for the immutable update.
