### ISSUE TITLE
Where is the definition of PayloadAction?

### ISSUE THREAD

**Issue by danielo515** [reduxjs/redux#4033]
## What docs page needs to be fixed?

- **usage with typescript**:
- **typing create reducer**:

https://redux.js.org/recipes/usage-with-typescript#typing-createreducer

## What is the problem?

There is a reference to a generic type, PayloadAction, that doesn't exist on this repo and it doesn't explain where to get it from.

## What should be changed to fix the problem?
It will be ideal to include such type as part of the package. If that is not possible, provide links to it's definition.

**Comment by markerikson** [comment]
`PayloadAction` is part of Redux Toolkit, and that particular section of the page specifically discusses Redux Toolkit.

We're planning to revamp the "Usage with TS" page in the near future.  See #4025 .

**Comment by markerikson** [comment]
Fixed by #4042 .
