### ISSUE TITLE
Update `changeType` to valid property

### ISSUE THREAD

**Issue by wjohnso-insight** [reduxjs/redux#4037]
## What docs page needs to be fixed?

- **Section**: Part 4: Store
- **Page**: [Dispatching Actions](https://redux.js.org/tutorials/fundamentals/part-4-store#dispatching-actions)

## What is the problem?

The sample code for dispatching `filters/colorFilterChanged', specifically the `payload` object, references `changeType: 'selected'`, but this type has not been defined at this point in the tutorial.  

## What should be changed to fix the problem?

Update `changeType` to 'added' or 'removed', which are both defined by the end of section 3.

**Comment by markerikson** [comment]
Closed by #4038 .
