### ISSUE TITLE
isPlainObject(Object.create(null)) return false

### ISSUE THREAD

**Issue by wpj-wpj-wpj** [reduxjs/redux#4039]
it is different from other utils like immer.js https://github.com/immerjs/immer/blob/master/src/utils/common.ts#L40

**Comment by markerikson** [comment]
It's a sufficient check for our purposes, so there's no need to change the behavior at this time.

If you have a specific use case where this matters, please let us know.

**Comment by wpj-wpj-wpj** [comment]
In my case, we use user's url token as entities key, some user's token is 'constructor', '__defineGetter__', '__defineSetter__', 'hasOwnProperty'  and so no. 

When I try to check whether these user exist in my store, it will always be true.

To fix this, I need to set a null proto to redux state.

But redux think 

My solution is 
`
const nullProto = Object.create(null)
const newState = Object.assign(Object.create(nullProto),oldState)
`

This work for Redux

But when I try to use @reduxjs/toolkit which depends on immer.js, it crashes like this:

![image](https://user-images.githubusercontent.com/26898312/111581807-e6453f80-87f4-11eb-8403-da7ddb1472f4.png)

![image](https://user-images.githubusercontent.com/26898312/111581839-f6f5b580-87f4-11eb-82ef-ee253ac9efda.png)

Here is a sandbox:
https://codesandbox.io/s/new-meadow-8uokk?file=/src/index.js

**Comment by markerikson** [comment]
I'm sorry, but this seems like an extreme edge case that we shouldn't be trying to handle.
