### ISSUE TITLE
[Docs] Spelling Mistake in configureStore Method

### ISSUE THREAD

**Issue by suryakanigolla** [reduxjs/redux#4048]
## What docs page needs to be fixed?

- **Section**: Redux Toolkit Example
- **Page**: Getting Started

## What is the problem?
counterSlice object doesn't have a property called "reducer"

## What should be changed to fix the problem?
Change the spelling from "reducer" to "reducers"

**Comment by markerikson** [comment]
Appreciate the issue, but the `counterSlice` _does_ have a property called `reducer`, because that's what `createSlice` generates:

https://redux-toolkit.js.org/api/createSlice#return-value
