### ISSUE TITLE
[Docs Rewrite] Remove "Using Immutable.js" page

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#4052]
The [Using Immutable.js with Redux](https://redux.js.org/recipes/using-immutablejs-with-redux) page was originally submitted by a user who was enthusiastic about that library.  Since they put the time into writing it, and it was relevant, we merged it.

Since then, the situation has changed considerably. We now specifically recommend that [you _should_ use Immer](https://redux.js.org/style-guide/style-guide#use-immer-for-writing-immutable-updates) and [you _should not_ use Immutable.js](https://redux.js.org/style-guide/style-guide#use-plain-javascript-objects-for-state).

So, it's time to remove that Immutable.js docs page entirely.

The only real question is what redirect we should add to ensure that incoming links pointing to that page end up at a real location.  Maybe point to the "Use Immer" Style Guide link?  Note that this should be done by specifically adding a line to `website/_redirects` that lists the old URL (and probably has a `*` splat in it), and points to the new URL.

We may also need to make updates to [the "Immutable Data" FAQ page](https://redux.js.org/faq/immutable-data) as well to remove any existing references to Immutable.js (and may want to add a new entry on that page that says "Should I Use Immutable.js? No, because...").

**Comment by AaronPowell96** [comment]
Could the redirect go to https://redux.js.org/style-guide/style-guide#use-immer-for-writing-immutable-updates ? 
It clearly states "Use Immer for Writing Immutable Updates", so if somebody were directed to immutable.js via an old article etc, they can clearly read that it is now recommended to use Immer? :)

**Comment by markerikson** [comment]
Sure, go ahead!  In theory, the necessary changes are:

- Remove the existing Markdown file for this page
- Search the codebase and remove any other links to that Markdown file
- Remove the entry for the page from `website/sidebars.js`
- Add the `_redirects` entry

**Comment by markerikson** [comment]
And fixed by #4053 .
