### ISSUE TITLE
https://bugzilla.mozilla.org/show_bug.cgi?id=1626065

### ISSUE THREAD

**Issue by etherx-dev** [reduxjs/redux#4063]
https://github.com/reduxjs/redux/blob/3e114f8c0fd4461e2f642c2737d2fa8297484728/src/applyMiddleware.js#L25-L28
https://bugzilla.mozilla.org/show_bug.cgi?id=1626065

**Comment by markerikson** [comment]
No idea what you're trying to say here, so I'm going to close this. If you can leave an actual problem description we an try to actually discuss this.
