### ISSUE TITLE
Example From Doc Yielding Error 

### ISSUE THREAD

**Issue by MikeBarberry** [reduxjs/redux#4066]
This example in Store.md does not work 

```
import { createStore } from 'redux'
const store = createStore(todos, ['Use Redux'])

function addTodo(text) {
  return {
    type: 'ADD_TODO',
    text
  }
}
store.dispatch(addTodo('Read the docs'))
store.dispatch(addTodo('Read about the middleware'))
```
I run it and get ``` todos is not defined ```

**Comment by timdorr** [comment]
That is just a small snippet of code and not meant to be a complete working example. You need to define your own `todos` for that to work.
