### ISSUE TITLE
Why you used delete to remove elements from the array instead of splice?

### ISSUE THREAD

**Issue by MenaiAla** [reduxjs/redux#4080]
## What docs page needs to be fixed?

- **Section**:
[converting-the-todos-reducer](https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#converting-the-todos-reducer)
- **Page**:
[part-8-modern-redux](https://redux.js.org/tutorials/fundamentals/part-8-modern-redux)

## What is the problem?

In your example , you've used  `delete` to remove an item from an array. However, this can lead to unexpected bugs.

```javascript
 todoColorSelected: {
      reducer(state, action) {
        const { color, todoId } = action.payload
        state.entities[todoId].color = color
      },
      prepare(todoId, color) {
        return {
          payload: { todoId, color }
        }
      }
    },
    todoDeleted(state, action) {
      delete state.entities[action.payload]
    }


```
As far as I know, `delete` will delete the object property, but will not reindex the array or update its length. This makes it appears as if it is `undefined`.

## What should be changed to fix the problem?

Use `splice` method instead of `delete`.

`myArray.splice(start, deleteCount) `actually removes the element, reindexes the array, and changes its length.

**Comment by markerikson** [comment]
Because `state.entities`, at this point in the tutorial, is an object and not an array.  So, `delete` is the correct operator here.
