### ISSUE TITLE
[DOCS] add info about using  redux-toolkit in existing redux-saga projects

### ISSUE THREAD

**Issue by MNF** [reduxjs/redux#4085]
## What docs page is being added or updated?

- https://redux.js.org/tutorials/fundamentals/part-8-modern-redux and/or 
- https://redux-toolkit.js.org/tutorials/overview#migrating-vanilla-redux-to-redux-toolkit

### What updates should be made to the page?

I understand that the recommended approach for most applications is to use redux-thunk, but many applications are using redux-saga.
It will be useful to describe how existing applications with saga can benefit from redux-toolkit.
As a minimal, reference to existing articles like https://blog.logrocket.com/smarter-redux-with-redux-toolkit/ will be good.

**Comment by markerikson** [comment]
There's no real difference that's worth documenting.  The only change is in how you create the store itself - `configureStore` vs `createStore`, and passing the saga middleware via the `middleware` option instead of calling `applyMiddleware() yourself.  All the instructions at https://redux-saga.js.org/docs/introduction/GettingStarted are the same otherwise.

**Comment by michael-freidgeim-webjet** [comment]
@markerikson , you know that “There's no real difference” ,but readers do not know.
I’ve read the tutorial and thought “it’s all about redux-thunk(that I am not familiar with),I will not be able to apply it to my redux-saga application”. 
My suggestion is just to mention that  it can be apply to existing redux-saga sites

**Comment by markerikson** [comment]
The goal of both the "Fundamentals" and "Essentials" tutorials is to introduce Redux concepts and standard usage patterns, with an emphasis on what's actually included in RTK.  Sagas are not included in RTK, so there's no reason to discuss those in the tutorials.

We also can't explain _everything_ ourselves in the docs. Users need to be able to extrapolate some usage patterns themselves based on the concepts we've explained.

I do want to add a usage guide page discussing options for async logic, but there's a lot of other priorities atm.
