### ISSUE TITLE
[Docs] Redux essentials code snippet shows reduxjs/toolkit import

### ISSUE THREAD

**Issue by ajuni880** [reduxjs/redux#4086]
## What docs page needs to be fixed?

- **Section**: https://redux.js.org/tutorials/essentials/part-1-overview-concepts#store
- **Page**: https://redux.js.org/tutorials/essentials/part-1-overview-concepts

## What is the problem?
Why reading the documentation about redux essentials, appears `import { configureStore } from '@reduxjs/toolkit'` in the code snippet? Is that correct?

## What should be changed to fix the problem?

I think it should be 
```
import { createStore } from 'redux';
```

**Comment by ajuni880** [comment]
It is correct, there are two sections, redux fundamentals and redux essentials. And in redux fundamentals its using `createStore`.

**Comment by markerikson** [comment]
Yes, this is correct.  Per https://redux.js.org/tutorials/essentials/part-1-overview-concepts#redux-toolkit , https://redux.js.org/tutorials/essentials/part-2-app-structure , and https://redux.js.org/style-guide/style-guide#use-redux-toolkit-for-writing-redux-logic, Redux Toolkit is now the standard approach for writing Redux logic, and we actually discourage people from writing Redux code "by hand".
