### ISSUE TITLE
Use of miniKindOf is not ES5-compliant

### ISSUE THREAD

**Issue by embeddedt** [reduxjs/redux#4089]
### Prior Issues

None that I could find.

### What is the current behavior?

Redux causes my application to crash on some ES5 browsers because of a [nested function within an `if` statement in kindOf.ts](https://github.com/reduxjs/redux/blob/5f29b2667ff83f0189bc2aa304b214b4e19fa398/src/utils/kindOf.ts#L4-L6). This is not permitted in ES5 and Babel does not seem to provide a transform for this, probably because it would break existing code.

The exact console log is this: `SyntaxError: Nested functions cannot be declared in strict mode.`

### Steps to Reproduce

It's a bit hard to create a live repro case for this, since finding an ES5 browser is difficult nowadays. However, I can provide [a gist](https://gist.github.com/embeddedt/0f40117a6f83cffce012ff5783860905) with my Babel and browserslist configurations as well as a file highlighting the issue.

### What is the expected behavior?

Redux should run in an ES5 environment with a standard Babel configuration.

### Environment Details

Browser: Midori 0.5.11 on Ubuntu 18.04

**Comment by markerikson** [comment]
Huh. This is the first I've ever heard that nested functions aren't legal in some cases. Can you point to some kind of a reference for where this restriction is described?

**Comment by embeddedt** [comment]
> This is the first I've ever heard that nested functions aren't legal in some cases.

Same here until I ran into the error and did some research on it.

Here are some references:

* https://stackoverflow.com/a/10069457
* https://github.com/acornjs/acorn/issues/118
* http://linterrors.com/js/function-statements-should-not-be-placed-in-blocks (in particular, the section further down on syntax errors)

My understanding of this is that ES5 has extremely loose scoping rules. Normally, the function definition would be hoisted out of the if statement, so in strict mode, they chose to prevent confusion by refusing to allow functions to be declared inside if statements.

This error is rarely observed in practice for two reasons:

* Many ES5 browsers allow this type of declaration, but with an inconsistent scope. Nonetheless, for cases like this the inconsistent scoping probably wouldn't be apparent.
* ES6 allows this behavior as the scoping rules were changed there, so any browser which supports ES6 won't choke on this code.

**Comment by markerikson** [comment]
Yeah, definitely a pretty rare edge case :)

tbh this is low priority for me atm, as we're focusing on getting the RTK Query APIs out the door.  If you'd like to submit a PR that rearranges the code to make this work as expected, we can look at getting that in.

**Comment by zelflod** [comment]
It can be reproduced in IE10, you'll have error "SCRIPT1047: In strict mode, function declarations cannot be nested inside a statement or block. They may only appear at the top level or directly inside a function body.".  Looking forward to release 4.1.1

**Comment by phryneas** [comment]
Seems to happen in Safari too: https://stackoverflow.com/questions/68635182/safari-error-functions-cannot-be-declared-in-a-nested-block-in-strict-mode
We should probably bump the priority of this one.

**Comment by timdorr** [comment]
This is only code in the master branch, which is the pending 5.0 Typescript rewrite. This doesn't exist in 4.x, so there's nothing to patch.

**Comment by timdorr** [comment]
Fixed in 4.1.1: https://github.com/reduxjs/redux/releases/tag/v4.1.1
