### ISSUE TITLE
[Feature Request] Add the ability to unsubscribe via `AbortSignal`

### ISSUE THREAD

**Issue by Hawmex** [reduxjs/redux#4092]
## New Features
Unsubscribe from store via `AbortSignal`.
### What is the new or updated feature that you are suggesting?
It would look like this:
```js
import { LitElement } from "lit-element";
import { store } from "<path-to-store>";

class MyElement extends LitElement {
  // ...

  #disconnectedController;

  connectedCallback() {
    super.connectedCallback();
    this.#disconnectedController = new AbortController();
    store.subscribe(() => this.stateChanged(store.getState()), { signal: this.#disconnectedController.signal })
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.#disconnectedController.abort();
  }
}
```
### Why should this feature be included?
At first look, it might seem unnecessary. But since `AbortSignal`s are added to `addEventListener` options (as far as I know at least in Chrome and NodeJS), it may provide a cleaner approach to cleanup listeners, especially in OOP libraries where the class may provide a cleanup signal for event listeners and redux listeners, etc. .
### What docs changes are needed to explain this?
Adding an optional second argument to `subscribe` as `options` (for more options that may be added in the future).
```ts
interface SubscribeOptions {
  signal?: AbortSignal;
}

declare function subscribe(listener: () => void, options?: SubscribeOptions): () => void;
```

**Comment by timdorr** [comment]
AbortControllers/Signals are more built for asynchronous aborts (user clicks a Cancel button while downloading) and are less for synchronous operations, such as dispatching and notifying listeners. 

I also don't see much difference between what you have an just storing the result of `subscribe()` to issue the unsubscribe action. 

Thanks, but I don't see much benefit to implementing this.
