### ISSUE TITLE
[Docs] Fix the typo in the Using Redux Data section of the Redux Essentials 

### ISSUE THREAD

**Issue by wood-push-melon** [reduxjs/redux#4124]
## What docs page needs to be fixed?

- **Section**: Tutorials - Essentials
- **Page**: Using Redux Data

## What is the problem?
In the [Preparing Action Payloads](https://redux.js.org/tutorials/essentials/part-4-using-data#preparing-action-payloads) section, the first sentence's period after the `action.payload` should be outside of the ``.

## What should be changed to fix the problem?
The expected sentence should be the follow:
We just saw that the action creators from `createSlice` normally expect one argument, which becomes `action.payload`.

**Comment by timdorr** [comment]
Thanks, but can you make a PR for this instead of an issue? We don't track docs typos as bugs.

**Comment by wood-push-melon** [comment]
@timdorr Sure, I can fire a PR for this doc fix. Thank you.
