### ISSUE TITLE
redux website

### ISSUE THREAD

**Issue by heythere11** [reduxjs/redux#4128]
clicking on the search box on redux website and pressing upward arrow leads the page to become fully blank

**Comment by timdorr** [comment]
I'm not able to reproduce that on my end. But if you can reproduce in other browsers or systems, you should open up an issue on the Docusaurus repo: https://github.com/facebook/docusaurus

**Comment by markerikson** [comment]
This is a known issue with Algolia's search input, which we don't control. That's in the process of being fixed on their end. See https://github.com/reduxjs/redux-toolkit/issues/1247 .
