### ISSUE TITLE
Text Not Visible in DARK MODE

### ISSUE THREAD

**Issue by AnirudhPanda** [reduxjs/redux#4143]
## What docs page needs to be fixed?

- [Page](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)

## What is the problem?
![issue](https://user-images.githubusercontent.com/66218496/127762554-0ec92d8c-5ee6-4d96-b883-fc68fad477f7.PNG)
![issue1](https://user-images.githubusercontent.com/66218496/127762558-fa690a4a-53b8-46f8-ae1a-7ae21af9882f.PNG)

## What should be changed to fix the problem?
Fixing `.admonition a` and  `.admonition a:hover` in [custom.css](https://github.com/reduxjs/redux/blob/master/website/src/css/custom.css)

**Comment by markerikson** [comment]
Please go ahead and file PRs for this repo and the RTK repo with the same fix as from React-Redux.

**Comment by AnirudhPanda** [comment]
> Please go ahead and file PRs for this repo and the RTK repo with the same fix as from React-Redux.

Sure! Will do!
