### ISSUE TITLE
GPL licensed package inter dependency

### ISSUE THREAD

**Issue by shinesjohn** [reduxjs/redux#4161]
### Prior Issues

NA

### What is the current behavior?

Redux  internally is dependent to eslint-plugin-jsx-a11y which internally is dependent to axe-core which internally dependent to neos-axecore which is having GPL license

### Steps to Reproduce

Redux  internally is dependent to eslint-plugin-jsx-a11y which internally is dependent to axe-core which internally dependent to neos-axecore.

redux => eslint-plugin-jsx-a11y => axe-core => neos-axecore

### What is the expected behavior?

Since redux is MIT, it should not have any dependent package license having GPL license

### Environment Details

"redux": "4.1.0"

**Comment by timdorr** [comment]
That's one of our dev dependencies, not a regular dependency, i.e. it's not a dependency of anyone using Redux. If you install Redux, you don't get any GPL code installed.
