### ISSUE TITLE
[Docs] There is a typo in redux docs.

### ISSUE THREAD

**Issue by Dann1y** [reduxjs/redux#4179]
## What docs page needs to be fixed?

https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow#immutability

- **Section**: Tutorials/Redux Fundamentals
- **Page**: Immutability

### Docs Immutability code.

```javascript
const obj = { a: 1, b: 2 }
// still the same object outside, but the contents have changed
obj.b = 3

const arr = ['a', 'b']
// In the same way, we can change the contents of this array
arr.push('c')
arr[1] = 'd'
```
I think `arr[1] = 'd'` is typo.
Is that right?

![image](https://user-images.githubusercontent.com/29726020/135467796-30d48a49-4f35-4dc0-bcb2-79eae263bad4.png)

## What should be changed to fix the problem?

`arr[1] = 'b'`
```javascript
const obj = { a: 1, b: 2 }
// still the same object outside, but the contents have changed
obj.b = 3

const arr = ['a', 'b']
// In the same way, we can change the contents of this array
arr.push('c')
arr[1] = 'b'
```

like this.

**Comment by markerikson** [comment]
No, the code is correct - it's showing two different ways to mutate the array.
