### ISSUE TITLE
Missing definition in part-8-rtk-query-advanced.md

### ISSUE THREAD

**Issue by scallywag** [reduxjs/redux#4203]
## What docs page needs to be fixed?

- **Section**: Tracking Client-Side State
- **Page**: Redux Essentials, Part 8: RTK Query Advanced Patterns
- **Link**: https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#tracking-client-side-state

## What is the problem?
The tutorial uses a selector called `selectNotificationsMetadata`, but never mentions how to define `selectNotificationsMetadata`.

## What should be changed to fix the problem?
Maybe the definition should be shown as here:

https://github.com/reduxjs/redux-essentials-example-app/commit/290e6e0118610fa7543a10cbccfb5f9d0bcd18e7#diff-d55f898ee2c70d3ba7d9868062e00d7872550b6fbfd91f1d998ef25b0fbb295dR139

**Comment by timdorr** [comment]
Can you make a PR? That's a better format for docs issues. There's an "Edit this page" link at the bottom of the page to do so.

**Comment by scallywag** [comment]
Yes, I will make a PR.

**Comment by scallywag** [comment]
Wasn’t quite sure how to fix this one as a newcomer to Redux, so I brought it up in `#redux` on Discord, and the original author of the doc said he will push a fix.

**Comment by markerikson** [comment]
Should be fixed now, see #4207 . Sorry about that!
