### ISSUE TITLE
type "Middleware" can't accept action type

### ISSUE THREAD

**Issue by hrkw00** [reduxjs/redux#4222]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

### What is the current behavior?

- in index.d.ts, `Middleware` type is something like that.

```ts
export interface Middleware<
  DispatchExt = {},
  S = any,
  D extends Dispatch = Dispatch
> {
  (api: MiddlewareAPI<D, S>): (
    next: Dispatch<AnyAction>
  ) => (action: any) => any
}
```

- when we use redux through `node_modules`, we have no choice to pass action type even though it's actually acceptable. (see [here](https://github.com/reduxjs/redux/blob/066e56605763b3f71619ea2b4eadf6c08686c35c/src/types/middleware.ts#L22-L30))

### Steps to Reproduce
- I think it's happed because in ` src/applyMiddleware.ts`, all of `Middleware` types get `any` as action type. (even if it's not, passing `Dispatch` is much better than passing `any`.)
- I want to suggest to change 

```ts
export default function applyMiddleware<Ext1, S>(
  middleware1: Middleware<Ext1, S, any>
): StoreEnhancer<{ dispatch: Ext1 }>
```

to 

```ts
export default function applyMiddleware<Ext1, S, D extends Dispatch = Dispatch>(
  middleware1: Middleware<Ext1, S, D>
): StoreEnhancer<{ dispatch: Ext1 }>
```

### What is the expected behavior?
- you can use more strict `Middleware` type

### Environment Details

```
"redux": "4.1.2"
```

**Comment by markerikson** [comment]
I'm not sure I understand what problem you're describing here.  Can you show some examples of the actual code you're trying to use, preferably as a CodeSandbox that demonstrates the problem?

**Comment by hrkw00** [comment]
@markerikson Thank you for commenting to the issue, and sorry for my pure description...

I try to write my own middleware in typescript.

```ts
import {Dispatch, Middleware} from 'redux'
...
export const myMiddleware: Middleware<undefined, MY_STATE_TYPE, Dispatch<MY_ACTION_TYPE>> = storeApi => {
  return next => {
    return action => {
      /* do something middleware stuff... */
    }
  }
}
```

In the above codes, `storeApi` has an expected type. But the types of `next` and `action` are ambiguous.(`next` is `Dispatch<AnyAction>`, `action` is `any`.)  

I can't refer the action type in middleware even though I specify the type. I think this is annoying to write type-safe codes.

**Comment by markerikson** [comment]
I think you may be approaching this problem from the wrong direction.

_Any_ value can be passed into `store.dispatch()`, at any time.  There is no guarantee that `action` is only one of a known subset of action objects with specific types.  For example, I could do `store.dispatch({type: 'this/is/an/unknown/action'})`, or `store.dispatch(new Promise())`.  Your code must be written in a way that acknowledges that fact.  This is really another form of the ["don't write action type unions" advice that we give](https://redux.js.org/usage/usage-with-typescript#avoid-action-type-unions).

Instead, your code should do runtime checks to confirm that `action` really is what you think it should be.  If you're using RTK (which you should be), all of our action creators [come with an `actionCreator.match()` type guard built in](https://redux-toolkit.js.org/usage/usage-with-typescript#alternative-to-using-a-literally-typed-actiontype) - using that in as `if(addTodo.match(action))` will narrow the type of `action` inside the condition.

This is also all entirely independent of how `applyMiddleware` itself is defined.  The _types_ that matter here are exactly what you provide when declaring your middleware variable.  `applyMiddleware` doesn't have any influence on those.

If you're looking to write some middleware with stronger types, you might want to try out [the new experimental "action listener" middleware](https://github.com/reduxjs/redux-toolkit/discussions/1648) that we're hoping to add to Redux Toolkit soon.
