### ISSUE TITLE
[Docs] Bad link text color in Tips and similar sections.

### ISSUE THREAD

**Issue by Faithfinder** [reduxjs/redux#4237]
## What docs page needs to be fixed?

- **Section**: All
- **Page**: All

## What is the problem?

Links color in tips is too similar to text color

![image](https://user-images.githubusercontent.com/25051063/146109750-7dbd07a9-d6c2-4b9b-8e0d-4b4cbec553fa.png)

## What should be changed to fix the problem?
Some CSS?

**Comment by timdorr** [comment]
I don't really consider this a problem. The links have hover states and they are visually distinct from the rest of the text (bullet points).

If you want to make a PR with specific CSS changes, we can certainly discuss and consider that. But as it is, they look fine to me.

**Comment by markerikson** [comment]
I will say that when the links are directly in a paragraph, it _is_ kinda hard to see the difference:

![image](https://user-images.githubusercontent.com/1128784/146215604-d137ec32-d61b-4028-920b-62f78a315dcf.png)

like, you gotta look really carefully to see that "Injecting Endpoints" in the last line is actually a link.
