### ISSUE TITLE
[Doc] React Devtools links repeated twice 

### ISSUE THREAD

**Issue by ghulamyazdani** [reduxjs/redux#4248]
## What docs page needs to be fixed?
![image](https://user-images.githubusercontent.com/55938346/147903012-3f6bc5f3-b1f1-4d41-9c4e-b121fd4ef341.png)
Here you can see react devtools link are repeated twice .
- **Section**:[Redux essensials](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)
- **Page**:[Redux overview](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)
   

## What is the problem?
Redux devtools written twice on same page
## What should be changed to fix the problem?
Need to remove one link from there.

**Comment by markerikson** [comment]
I think you may have misread those links :)

The first pair of links are for the **React** DevTools.

The second pair are for the **Redux** DevTools.

Those are different extensions that both need to be installed.
