### ISSUE TITLE
I install react-devtools and use npx react-scripts command to start it but failed. show as below

### ISSUE THREAD

**Issue by heimiguoguo** [reduxjs/redux#4249]
## What docs page needs to be fixed?

- **Section**:
- **Page**:

**Comment by heimiguoguo** [comment]
![image](https://user-images.githubusercontent.com/22771321/148143630-c3f24f70-ff39-4c17-b6b7-79f12865b12e.png)

**Comment by timdorr** [comment]
This has nothing to do with Redux.
