### ISSUE TITLE
Convert class components to functional components in the API docs examples

### ISSUE THREAD

**Issue by mayavera** [reduxjs/redux#4253]
## What docs page is being added or updated?

- **Section**:
  - API Reference
- **Pages**:
  - [applyMiddleware](https://redux.js.org/api/applymiddleware#example-using-thunk-middleware-for-async-actions)
  - [bindActionCreators](https://redux.js.org/api/bindactioncreators#somecomponentjs)

### What updates should be made to the page?

The class-based react components should be converted to functional components.

### Do these updates change any of the assumptions or target audience? If so, how do they change?

Converting the components to functional components assumes the audience understands the basics of functional react components and hooks. In contrast, the existing examples assume the audience understands the lifecycle methods of class components. Both of these concepts are foundational to modern React development. Still, functions and hooks seem to be the preferred method of defining a component (e.g., the React docs have mainly been rewritten to use functional components: https://reactjs.org/docs/lists-and-keys.html).

**Comment by das3in** [comment]
Can we close this? Fixed in #4254

**Comment by markerikson** [comment]
Ah yes, thanks!
