### ISSUE TITLE
Broken link to React Router official doc in "Using Redux Data" session

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [reduxjs/redux#4274]
## What docs page needs to be fixed?

In the `Using Redux Data` page, there's a broken link in the `Prerequisites` session: `Familiarity with the React Router <Link> and <Route> components for page routing`.

**Added a screenshot for better context:**

![broken-link](https://user-images.githubusercontent.com/32891808/151712900-1462227b-4c04-430d-8e5e-57bf39be1322.png)

- **Section**: `Tutorials -> Redux Essentials -> Using Redux Data`

- **Page**: [Using Redux Data](https://redux.js.org/tutorials/essentials/part-4-using-data)

## What is the problem?

There's a broken link which it's supposed to redirect you to `React Router`'s doc.

## What should be changed to fix the problem?

Update it with the right `url`.

**Comment by markerikson** [comment]
Could you file a PR to update the docs page?
