### ISSUE TITLE
Redux Fundamentals - Store: wrapDispatch description

### ISSUE THREAD

**Issue by RamanSB** [reduxjs/redux#4276]
## What docs page needs to be fixed?

- **Section**: Redux Fundamentals
- **Page**: Store

## What is the problem?
The description of what wrapDispatch function does: 

wrapDispatch: The middle function receives a function called next as its argument. This function is actually the next middleware in the pipeline. If this middleware is the last one in the sequence, then next is actually the original store.dispatch function instead. **Calling next(action) passes the _middleware_ to the next middleware in the pipeline**. This is also only called once

## What should be changed to fix the problem?
I believe the sentence should state:

Calling next(action) passes the **_action_** to the next middleware in the pipeline. This is also only called once.

**Comment by markerikson** [comment]
Good catch! Could you file a PR to fix this?

**Comment by RamanSB** [comment]
Hi Mark,

Thanks, I’ll raise a PR for this, it’ll be my first.

Regards,
Raman

**Comment by markerikson** [comment]
Hey, it's a great way to get started! )
