### ISSUE TITLE
Fix in the documentation page of Redux Fundamentals Part 3

### ISSUE THREAD

**Issue by aayushibansal2001** [reduxjs/redux#4285]
## What docs page needs to be fixed?
There are some typos in the Redux Fundamentals Part 3: State, Actions and Reducers page.

**Section**: 
1. [Designing Actions](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#designing-actions)
2. [Creating the Root Reducer](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#creating-the-root-reducer)

I'm willing to make the necessary changes and submit a pull request for this problem.

**Comment by markerikson** [comment]
Which typos, specifically?

And yes, PRs to improve the docs are always welcome!

**Comment by aayushibansal2001** [comment]
In section 'Designing Actions':
![image](https://user-images.githubusercontent.com/51708118/153739730-0f3b32b6-53a5-4aaa-bb8a-e00ab069ebe2.png)

In section 'Creating the Root Reducer':
![image](https://user-images.githubusercontent.com/51708118/153739752-7384ed47-10f0-49a6-9dd7-7295d7297be3.png)

**Comment by markerikson** [comment]
Hmm. I'm not actually seeing any typos in those snippets. What words appear to be wrong?

**Comment by aayushibansal2001** [comment]
In first sentence, 'apiece' shouldn't be there.
In second sentence, 'We know we need to check to see' seems a bit ambiguous.

**Comment by markerikson** [comment]
Mmm... I wouldn't call these "typos", and that was confusing me.  "Grammar tweaks", maybe?

The point of "apiece" is to say that "_each_ action has some extra data".

But yeah, we can tweak these.
