### ISSUE TITLE
[Docs Fix] Align Tag with Heading in Style Guide

### ISSUE THREAD

**Issue by Apoorve73** [reduxjs/redux#4299]
## What docs page needs to be fixed?

- **Section**: Style Guide
- **Page**: Style Guide

## What is the problem?
The headings aren't aligned with the tags `ESSENTIAL`, `RECOMMENDED` and `STRONGLY RECOMMENDED`, as shown in the screenshots, below.

![Screenshot 2022-02-23 at 11 43 35 PM](https://user-images.githubusercontent.com/55204045/155383080-503fd74b-337d-4f62-aafb-ee041e4ff205.png)
![Screenshot 2022-02-23 at 11 49 32 PM](https://user-images.githubusercontent.com/55204045/155383090-25621a17-08ba-4d51-ad45-838aade24197.png)
![Screenshot 2022-02-23 at 11 53 05 PM](https://user-images.githubusercontent.com/55204045/155383096-e024e977-b156-455c-bcf5-cf7d80fe2d10.png)

## What should be changed to fix the problem?
The alignment property for these tags need to be kept in sync with the heading in order to prevent the distortion.

**Comment by Apoorve73** [comment]
@markerikson Would you like me to work on this?

**Comment by markerikson** [comment]
Sure, please do!

**Comment by Apoorve73** [comment]
Sure, thanks!
