### ISSUE TITLE
There is no need to change innerHTML to insert values from the store there - it is enough to change innerText

### ISSUE THREAD

**Issue by budarin** [reduxjs/redux#4309]
## What docs page needs to be fixed?

- \docs\tutorials\fundamentals\part-1-overview.md
- \docs\tutorials\fundamentals\part-5-ui-and-react.md
- \examples\counter-vanilla\index.html

## What is the problem?

Store stores values - not html, it makes no sense to change html and for security purposes

## What should be changed to fix the problem?
`valueEl.innerHTML = state.value.toString()` 

should be changed to 

`valueEl.innerText = state.value.toString()`

**Comment by markerikson** [comment]
Appreciate the feedback, but it's really not worth changing at this point :)  Besides, the example is trying to show the basic Redux + UI interaction sequence, not the intricacies of DOM APIs.

**Comment by budarin** [comment]
But this is also semantically incorrect and inculcates unsafe methods of DOM modification for beginners.

However, you are the owner of the repository - your decision is decisive :)
