### ISSUE TITLE
Reducer returns instead of modifying state in "loading users" section

### ISSUE THREAD

**Issue by tbrlpld** [reduxjs/redux#4317]
## What docs page needs to be fixed?

- **Section**: Loading Users
- **Page**: https://github.com/reduxjs/redux/blob/master/docs/tutorials/essentials/part-5-async-logic.md

## What is the problem?

I am currently going through the essentials tutorial. I feel like I have understood what reducers are for and what they do... until I hit the "loading users" section.  

All reducers up to this point do not return anything, but only "modify" the state. I understand this is relying on Immer to make turn the mutations into immutable operations on a new object. 

The confusion for me is that the reducer that is passed to `builder.addCase` is returning `action.payload` and does not do anything with `state`.

```
const usersSlice = createSlice({
  name: 'users',
  initialState,
  reducers: {},
  extraReducers(builder) {
    builder.addCase(fetchUsers.fulfilled, (state, action) => {
      return action.payload
    })
  }
})
```

There is no explanation why this reducer is different. I does not seem to be the fact that it is in `builder.addCase`. I infer this because just above in the "Loading posts" section the reducers modify state just like anywhere else in the tutorial. 

```
  extraReducers(builder) {
    builder
      .addCase(fetchPosts.pending, (state, action) => {
        state.status = 'loading'
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.status = 'succeeded'
        // Add any fetched posts to the array
        state.posts = state.posts.concat(action.payload)
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.status = 'failed'
        state.error = action.error.message
      })
  }
```

## What should be changed to fix the problem?

An explanation should be added as to why it is necessary in the "loading user" section to return something from the reducer instead of just "modifying" the state. 

Or change the code example to be consistent with the rest.

**Comment by tbrlpld** [comment]
Thanks for the pointers and explanation @markerikson! 

I think I understand and have just tested. The reducer also works when using `state.push(...action.payload)`. This would be the mutating way where nothing needs to be returned. 

I guess the mutating way was not chosen because the intent is "get the whole state from the server". In that case we want to throw away any potential client state, even if in this case we just initialised it to be empty (but we are doing that to do it in a clean way that would also work with "dirty" client state). 

And I think `state = action.payload` does not work, because this is not a mutating action on the original `state` array but points the `state` variable to a different array, which leads to Immer not being able to see any change on the original array (I am guessing it keeps its own reference to that original object). 

I'll try to come up with an explanation that fits into the tutorial and submit a PR.

**Comment by markerikson** [comment]
correct, `state = anything` _never_ works in an Immer-powered reducer, because it's just pointing the variable named `state` to another value in memory, and that is neither _mutating_ nor _returning_ a value.

https://redux-toolkit.js.org/usage/immer-reducers#resetting-and-replacing-state

**Comment by tbrlpld** [comment]
I have added https://github.com/reduxjs/redux/pull/4318 which adds a short explanation on this subject.
