### ISSUE TITLE
Stop supporting IE 11

### ISSUE THREAD

**Issue by 38elements** [reduxjs/redux#4320]
## New Features

Since React 18 plan to stop supporting IE 11, I think it is better to stop supporting IE 11 at version 5.x. Version 4.x will continue to support IE11.

### What is the new or updated feature that you are suggesting?

Stop supporting IE 11

### Why should this feature be included?

This change reduces bundle size and improves performance.

### What docs changes are needed to explain this?

It is necessary to add "IE 11 is not supported" to release note.

**Comment by markerikson** [comment]
Honestly there's basically nothing to do here :)  Redux is so tiny that there's nothing IE11 specific, really.

That said, the `master` branch (which may, eventually, someday, become v5 if we ever get around to releasing it) has already been updated to target a more modern syntax.  React-Redux v8 also has that same change.

So, I'm going to close this as "already done / nothing else to do".
