### ISSUE TITLE
Top documentation result in Google 404s

### ISSUE THREAD

**Issue by Johngeorgesample** [reduxjs/redux#4335]
## What docs page needs to be fixed?

- **Section**: https://redux.js.org/style-guide
- **Page**: Style Guide: Best Practices

## What is the problem?
The top Google result for `redux style guide` looks to be an old route that 404s: https://redux.js.org/style-guide/style-guide
![CleanShot 2022-04-18 at 10 26 41](https://user-images.githubusercontent.com/4723360/163822490-1a4c0a26-c0d7-4f8e-9889-af8f5d43db32.png)

## What should be changed to fix the problem?
A redirect should be implemented to take users from this broken link to the actual style guide section.

**Comment by josiahmokob0** [comment]
The link works fine for me, I am using a phone FYI

**Comment by timdorr** [comment]
@markerikson Is this caused by the Docusaurus upgrade? This might affect other pages.

**Comment by markerikson** [comment]
Very likely related, yes. I upgraded DS and it suddenly started reporting a CI of broken links, which were the style guide and other pages linked in the header and footer. Part of it seemed to be changed handling of files named README. I thought I fixed them, but wouldn't be surprised if there's other problems.

@slorber : any idea what would have caused these links to break with a DS upgrade?

**Comment by markerikson** [comment]
It looks like the Style Guide page may now be pointing to https://redux.js.org/style-guide/ , instead of `redux.js.org/style-guide/style-guide` . 

That's... weird.  Why would this have suddenly changed?

**Comment by Josh-Cena** [comment]
I've replied on Discord. For reference, it's because of https://github.com/facebook/docusaurus/pull/5830 which means `/<name>/<name>/` and `/<name>/index` slugs would now have the last segment omitted.

**Comment by markerikson** [comment]
Yeah, I think I'm inclined to agree as far as URL patterns go.  Let me try updating that PR to do a redirect instead.

**Comment by Josh-Cena** [comment]
Fixed in #4339 and #4340

**Comment by Johngeorgesample** [comment]
Thanks for the quick fix!
