### ISSUE TITLE
Add a new "Videos" docs page under "Tutorials"

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#4354]
We have a ton of _written_ content, but admittedly what we don't have is video or interactive content.

I've tossed around the idea of doing an Egghead course based on the "Essentials" tutorial for a while, but haven't had time to do it.

In the meantime, there's some existing videos that I've seen that appear to be _excellent_.  So, we should add a new "Videos" page and link these for now:

- Dave Gray's "Redux Toolkit Complete Tutorial": https://youtu.be/NqzdVN2tyvQ . I just saw this, and it appears to be a single 4-hour video that actually shows how to build the exact same app I came up with for the "Essentials" tutorial.  Looks like a "no fluff, all stuff" video, and the fact that it's showing the "Essentials" app is great!
- Jamund Ferguson's Egghead courses: https://app.egghead.io/instructors/jamund-ferguson
  - "Modern Redux with RTK and TypeScript": https://app.egghead.io/playlists/modern-redux-with-redux-toolkit-rtk-and-typescript-64f243c8
  - "Modernizing a Legacy Redux App with React Hooks": https://app.egghead.io/playlists/modernizing-a-legacy-redux-application-with-react-hooks-c528
  - "Confidently Testing Redux Apps with Jest and TS": https://app.egghead.io/playlists/confidently-testing-redux-applications-with-jest-typescript-16e17d9b

I haven't watched these all the way through, but I've seen enough (and know Jamund in particular well enough) to feel comfortable that this is all great content that would be worth pointing people to.

We can also link Lenz's upcoming RTKQ Egghead course there when it's available.

**Comment by kishoreandra** [comment]
Egg head courses link shows 404 😑

**Comment by markerikson** [comment]
Huh, yeah. I copied those links straight out of the "Jamund's courses" page.  Weird.

Updated the links after searching Egghead's site.  Seems like the correct URLs have `/playlist/` instead of `/course/`

**Comment by markerikson** [comment]
Done!
