### ISSUE TITLE
[Docs] Add new "side effect options and comparison" page

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#4356]
Basically a docs page version of https://blog.isquaredsoftware.com/2022/05/presentations-evolution-redux-async-logic/

Also, this page is similar: https://nordfjord.io/2020/08/31/async-redux.html

**Comment by grazirs** [comment]
Hi @markerikson! Which section of the site will this new docs page be added to?

**Comment by EduardoSCosta** [comment]
Hi @markerikson, @grazirs and I would like to do this issue, can we?

**Comment by markerikson** [comment]
Hmm. I'm usually pretty happy to see people volunteering to help with the docs :) but in this case, this is a page I was particularly wanting to write myself.

Just to check, are there any other potential docs pages you might be interested in helping with?  I've got a number of other issues tagged with `docs` that you can look through to get ideas.
