### ISSUE TITLE
Redux Batch example usage is incorrect

### ISSUE THREAD

**Issue by EskiMojo14** [reduxjs/redux#4369]
## What docs page needs to be fixed?

- **Section**: Introduction
- **Page**: Ecosystem

## What is the problem?
Correct [redux-batch](https://github.com/manaflair/redux-batch#usage-w-extra-middlewares) usage requires making sure that reduxBatch is at the beginning and end of the enhancers array, whereas [current docs](https://redux-toolkit.js.org/api/configureStore#full-example) only use the array config version (which would put reduxBatch after the middleware enhancer, preventing the use of middleware within batches e.g. thunks).

This [codesandbox](https://codesandbox.io/s/redux-batch-rtk-typing-yl6b0t?file=/src/index.ts) can be used to replicate the issue - change line 71 to `enhancers: [reduxBatch]`. [Replay](https://app.replay.io/recording/redux-batch-dispatch-error--b81239e0-f488-480e-8266-cdcd3b7b302e) kindly provided by @markerikson.

## What should be changed to fix the problem?
Changing the docs to `enhancers: (enhancers) => [reduxBatch, ...enhancers, reduxBatch]` would be correct usage.

PR incoming :)

**Comment by timdorr** [comment]
Fixed in #4370
