### ISSUE TITLE
Update `useAppDispatch` type def in docs

### ISSUE THREAD

**Issue by raulsanchez1024** [reduxjs/redux#4372]
## What docs page needs to be fixed?

- **Section**:
`https://redux.js.org/usage`
- **Page**:
`/usage-with-typescript#define-typed-hooks`

## What is the problem?
Shorten the type definition

## What should be changed to fix the problem?
Update the type definition per this [tweet](https://twitter.com/acemarke/status/1536794905741246464)

**Comment by markerikson** [comment]
Thank you!
