### ISSUE TITLE
Simplify the `useAppDispatch` definition

### ISSUE THREAD

**Issue by patel-himanshu** [reduxjs/redux#4374]
## What docs page needs to be fixed?

- **Section**: Usage with TypeScript
- **Page**: https://redux.js.org/usage/usage-with-typescript#typing-the-usedispatch-hook

## What is the problem?
The current definition of `useAppDispatch` can be shortened. Currently, it is:
```typescript
export const useAppDispatch = () => useDispatch<AppDispatch>();
```

## What should be changed to fix the problem?
It can be reduced to 
```typescript
export const useAppDispatch: () => AppDispatch = useDispatch;
```

**Comment by markerikson** [comment]
Hah, I think #4372 beat this one, and also has a PR :)

But, we have the same "TS Quick Start" page over in the React-Redux and Redux Toolkit repos.  Can you update those?
