### ISSUE TITLE
renderWithProviders cannot be named without a reference to '@testing-library/dom/node_modules/pretty-format'

### ISSUE THREAD

**Issue by rosnaib11** [reduxjs/redux#4388]
The inferred type of 'renderWithProviders' cannot be named without a reference to '@testing-library/dom/node_modules/pretty-format'. This is likely not portable. A type annotation is necessary.ts(2742)

Got this error. I tried deleting @testing-library/dom, it works but I need it to run my test.

![image](https://user-images.githubusercontent.com/26837762/180032619-925f9184-9a18-488c-9c23-59906344dad1.png)

I'm using latest versions of redux and my testing libraries

**Comment by timdorr** [comment]
This isn't a Redux bug.
