### ISSUE TITLE
State is lost with SSR and dynamically injected reducers

### ISSUE THREAD

**Issue by micahblu** [reduxjs/redux#4422]
Put simply with a common SSR pattern of hydrating the store with server side reducer state and dynamically injecting reducers, state for reducers yet to be injected is lost if there are any state changes that occur before the reducer was injected. 

State is only preserved for reducers that redux has a reference to, but with dynamically injected reducers, redux will not have reference to reducers that have yet to be injected.

The problem can easily be solved in the returned combination function inside combineReducers by preserving state in nextState with nextState = { ...state } instead of assigning it to an empty object. Is there a reason for this? If so is there a prescribed pattern for doing SSR with dynamic reducer injection that guarantees no state loss?

### What is the current behavior?
Omits state for reducers that have yet to be injected on any state change

### What is the expected behavior?
Preserve state on state changes for reducer slices that have yet to have their reducer injected

### Environment Details
I'm seeing this in 3.7.2 but I see the problem would also be in the current version.

**Comment by timdorr** [comment]
I'm not sure how this is much different from SSR code splitting with React components. If you tried to re-render a React tree with fallback elements, you would expected the state to disappear. Similarly, if you try to initialize or dispatch a Redux store with missing reducers, that state should disappear. 

I think the solution here is that you need to ship not just the rendered HTML and state to the browser, but also the right slice of JS to correspond with it. Just like you would with any other code, you wouldn't execute it until you have it all loaded and ready. 

Either that or use Redux Toolkit 🤷

**Comment by phryneas** [comment]
I'd like to give a different perspective:
That code for dynamically injecting reducers is code you write. Granted, you might have copy-pasted it from the docs, but those docs describe a basic use case. You added SSR on top. It's your job as a developer to then also add code to accomodate for your SSR scenario on top -  and in your case that would mean not to use `combineReducers`, but your own replacement that would not throw away additional slices.  
Something like
```js
function combineReducersAndKeepStuff(reducers) {
  return function reducer(state, action) {
    const newState = {...state};
    for (const key of Object.keys(reducers)) {
      newState[key] = reducers[key](state[key], action)
    }
    return newState
  }
}
```

**Comment by micahblu** [comment]
@phryneas and @timdorr Good feedback. The interim solution I had was to just stub the reducers when creating the store based on the state slices I got from the server and essentially wait for them to be injected, this way Redux had a reducer reference and did not lose state for them. I like the solutions you guys have given, but this is a heavy application and I'd need a map of all the reducers and then pick the ones that were hydrated and combine them immediately when creating the store, this would be a very large map of reducers. Given the feedback though I do agree it's the responsibility of the developer to choose how the state is managed with our SSR solution. I'll close the ticket. Much thanks.

**Comment by phryneas** [comment]
@micahblu you might want to reread my suggestion - it would not need any knowledge of reducers that would be injected in the future. It would just use my function instead of `combineReducers` while following the "code splitting" suggestions in the documentation.

**Comment by micahblu** [comment]
@phryneas maybe I'm misunderstanding, but the custom combineReducersAndKeepStuff() function still requires a map of "reducers" to be passed?

**Comment by micahblu** [comment]
@phryneas nevermind, I understand now! Thanks very much :)
