### ISSUE TITLE
JS / TS switch in docs does not change file extension

### ISSUE THREAD

**Issue by coder-do** [reduxjs/redux#4429]
## What docs page needs to be fixed?

- **Section**:
- **Page**:

## What is the problem?

https://user-images.githubusercontent.com/68124376/200330961-7c59df3f-f8b6-466c-be7d-cea071784c99.mp4

https://user-images.githubusercontent.com/68124376/200330965-ff09f62e-4f6c-4f05-b626-e946d6a99987.mp4

## What should be changed to fix the problem?

Switching between JS/TS file extension to `.js` and `.ts` does not change as expected.

**Comment by timdorr** [comment]
This is actually a bug in remark-typescript-tools: https://github.com/phryneas/remark-typescript-tools
