### ISSUE TITLE
Feature Request - Subscribe with state dependency !

### ISSUE THREAD

**Issue by redwanul10** [reduxjs/redux#4442]
### Description :
Currently in Redux.js whenever we change the state in store it calls all the subscribed listeners. is there any way to subscribe to specific state change? ( something like useEffect dependency in React). I'm working in a vanilla js project with Redux.js, I realized that would be helpful if we could subscribe with dependencies.

### Example:
```javascript
var initialState ={
  language:"en",
  name:"redwan"
}
var store = createStore(someReducer,{number:10})

store.subscribe(()=>{
    console.log("our state updated")
})

// something similar to this subscribe with dependencies
store.subscribe(()=>{
    console.log("only language updated !")
},store.getState().language)

```

**do you think it would be helpful for vanilla redux.js ?** Please let me know I'm interested to add this feature, Thank You !

**Comment by markerikson** [comment]
At a basic level: no, this is intentionally how Redux works:

- https://redux.js.org/faq/design-decisions#why-doesnt-redux-pass-the-state-and-action-to-subscribers

However, you can add logic on top of the core `store.subscribe()` function that does diffing and only runs a callback if specific fields have changed.  There are several addons that do this:

- https://github.com/markerikson/redux-ecosystem-links/blob/master/store.md#store-change-subscriptions

such as https://github.com/jprichardson/redux-watch .

The new Redux Toolkit "listener" middleware also lets you do this in a way, by providing a `predicate: (action, currState, prevState) => boolean` option for running effects:

- https://redux-toolkit.js.org/api/createListenerMiddleware#startlistening
- https://redux-toolkit.js.org/api/createListenerMiddleware#standard-usage-patterns
