### ISSUE TITLE
Share expectations/best practices for Redux middleware

### ISSUE THREAD

**Issue by dbartholomae** [reduxjs/redux#4472]
As discussed in an [rtk query issue](https://github.com/reduxjs/redux-toolkit/issues/3118#issuecomment-1403784368), there are some implicit assumptions about how middleware should be written to be compatible with other Redux libraries. Even though it is possible to write any kind of middleware, it would be helpful to document these assumptions so that middleware written by different people is compatible.

### What kind of content category is this page (tutorial, how-to, explanation, reference)?

Reference

### Who is the intended target audience?

Devs writing their own middleware

#### What knowledge are we assuming they have?

How to write middleware

### What are the intended results or takeaways from reading this page?

How to write middleware that is compatible with other redux projects like redux toolkit.

### What is the most critical info they should learn?

That the middleware should not change the return value (even to a Promise) and needs to call next with an action.

**Comment by timdorr** [comment]
We have this page already: https://redux.js.org/understanding/history-and-design/middleware

**Comment by markerikson** [comment]
@timdorr eh, we've got that "history/philosophy" page, but we don't have a "Usage Guide" page that talks about "how to write a middleware properly", which is what I was thinking of from that other thread :)

**Comment by timdorr** [comment]
I'm confused, because that's literally what that page covers (best practices and things to avoid)

**Comment by markerikson** [comment]
Hmm. Re-reading it... I agree there's some of that info in there, sort of.  But A) that page has always been pretty confusing to read in general ("here's 6 ways to write middleware that _don't work_!"), and it's also not structured as a "here's how to do this" page.

What I'm picturing would cherry-pick some of the info from "Fundamentals Part 4: Store > Middleware", then go into more details on what you can and can't do inside, why a middleware should end up doing some form of `return next(action)` to avoid breaking the return chain, etc.

**Comment by dbartholomae** [comment]
Yeah, I would not have searched for this in a section called "History and Design". I would assume that I only need to read that when contributing to the library itself, but not when writing my own additions.
If there is interest, I'm happy to provide a PR along the lines of what @markerikson suggested.

**Comment by markerikson** [comment]
Worth making a note that middleware can run logic both before _and_ after the reducer updated the state - just depends on where you place the `next(action)` call:

- https://stackoverflow.com/questions/75355986/reacting-to-changes-in-derived-state-with-redux/75356462?noredirect=1#comment132990467_75356462

**Comment by dbartholomae** [comment]
Based on [the twitter discussion](https://twitter.com/acemarke/status/1623041113790550030), I can set up a PR some time next week I think :)

**Comment by dbartholomae** [comment]
Took a bit longer, but I'll start on this now and expect a PR to be ready later today.

**Comment by dbartholomae** [comment]
@markerikson  I've created a PR #4498 awaiting your feedback
