### ISSUE TITLE
Possible collision with prototype properties in combineReducers

### ISSUE THREAD

**Issue by rtm** [reduxjs/redux#4506]
https://github.com/reduxjs/redux/blob/1133bd81849677e8b1c5619eb0d4721750f5fca3/src/combineReducers.ts#L182

Won't this line cause a bug for keys which are on the object prototype, such as `toString`, even if non-enumerable?
In our case, it caused a bug on a very old browser which had the Spidermonkey `watch` property on the Object prototype. That's on us, but wouldn't the same bug occur with other prototype methods?

If my guess is correct, one fix would be
```
state = Object.create(null);
```

**Comment by phryneas** [comment]
`key` is an element of `finalReducerKeys`, and `const finalReducerKeys = Object.keys(finalReducers)`

> The Object.keys() static method returns an array of a given object's own enumerable string-keyed property names.

So I would assume... no?

Can you give an example?

**Comment by markerikson** [comment]
#4215 was a similar related issue, and we closed it on the grounds that it's too much of an edge case for us to worry about.

**Comment by timdorr** [comment]
Agreed. This is very unlikely to be hit and represents a code smell, IMHO.

**Comment by vartan** [comment]
Does using a property named "watch" really represent a code smell? I think this is a much less obvious issue than "constructor" in #4215 and doesn't seem particularly smelly to me. Additionally in #4215 a justification for closing the bug is "I'm not sure there's anything we should or even can do about this at the code level", but @rtm provided a potential workaround. I understand that it's not feasible to support every old browser, but it seems reasonable to me that a dictionary of key value pairs doesn't need to inherit from `Object.prototype`.

**Comment by markerikson** [comment]
Redux is pretty generic JS, and so it _should_ function in any reasonable JS environment.  However, we specifically _don't_ try to do any workarounds for browser issues, other than backwards-compiling the published artifacts to ES5 for IE11 support in the current 4.x release line.

Adding more code for these extremely rare edge cases, especially for hypothetical scenarios where very old browsers have weird behavior, is not something we want to get sucked into.

**Comment by phryneas** [comment]
You say that this is a change in `Object.prototype`. Adding something to `Object.prototype` will *not* show up in `Object.keys`. 

Please create a demonstration of the issue, like I asked.


For reference:
```js
Object.prototype.foo = 2 
console.log(Object.keys({}))
```
will print `Array []`

**Comment by rtm** [comment]
A closer look at the code shows that the issue in question is not related to `Object.keys`. Instead, it's related to the new object called `state`, which is created as `{}`, which yields an object with prototype. Then, existing keys are looked up in that `state` object, and if they happen to be keys which are on the prototype, the lookup "succeeds" and the bug ensues. 

This bug is not related to old browsers, or user error, or code smells. It occurs whenever any key is used that is on the Object prototype, whether enumerable or not. That includes, for example, `toString`. 

Whether or not the decision by a user to use a key `toString` is a "code smell" or an "edge case" is a matter of judgment (as is whether being an "edge" case is a sufficient rationale for not dealing with a bug), but there's no obvious reason why it shouldn't work. The resulting behavior is also likely to be quite difficult to track down for those few unfortunate souls it affects. It would be a different matter if this was very hard to fix, or made the code more complex, or raised the risk of introducing additional bugs, but here it's just a matter of replacing `{}` with `Object.create(null)`. So I'm frankly not quite sure where the pushback is coming from.

To summarize the objections:

1. **This bug doesn't exist, because the code is using `Object.keys`.** That objection is based on an incorrect reading of the code. I thought the same thing when I first looked at it. But actually the behavior in question does in fact exist, because `state` is a new object created in such a way that it includes an object prototype, and it is being referenced in a way (`state[key]`) which does not distinguish between whether the key is an own property or not.

2. **This bug is an edge case, because only old browsers have the `watch` property.** But actually it applies to any property on the object prototype, including those in modern browsers.

3. This bug is an edge case, because no one in their right mind would every name a key `toString` or `valueOf` or `hasOwnProperty`. That seems a bit overbearing for us to decide what keys people can or can't use.
