### ISSUE TITLE
Redux Essentials => Performance and Normalizing data => adding a badge for notifications

### ISSUE THREAD

**Issue by Reprovo** [reduxjs/redux#4508]
When adding a badge for notifications, for the purpose of the course only, we could use !n.new since all notifications are marked as 'read', otherwise the badge doesn't appear. Nothing important but i spent a few minutes trying to see If I had typed something wrong.

`const numUnreadNotifications = notifications.filter(n => !n.read).length`

**Comment by timdorr** [comment]
This has already been suggested, but is correct as-is: https://github.com/reduxjs/redux/pull/4418#issuecomment-1245749665
