### ISSUE TITLE
update React Docs Link in 'getting started with redux page'

### ISSUE THREAD

**Issue by MahendraBishnoi29** [reduxjs/redux#4521]
## What docs page is being added or updated?

- **Section**:  How to Read This Tutorial
- **Page**: [this page](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#how-to-read-this-tutorial)

### What kind of content category is this page (tutorial, how-to, explanation, reference)?
tutorial

### What updates should be made to the page?
update the links to latest react docs

**Comment by MahendraBishnoi29** [comment]
assign it to me I'll update them

**Comment by MahendraBishnoi29** [comment]
@markerikson i found some more outdated links so should i fix them in single PR or should i create separate PRs?

**Comment by markerikson** [comment]
@MahendraBishnoi29 one combined PR, please - thanks!

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 one combined PR, please - thanks!

Alright 👍🏻
