### ISSUE TITLE
Failed to load config "react-app" to extend from.

### ISSUE THREAD

**Issue by 2dareis2do** [reduxjs/redux#4554]
When downloading reduxjs/redux and following instructions to run the todos demo I get 

Failed to load config "react-app" to extend from.
Referenced from: /Users/myuser/Sites/redux/.eslintrc.cjs 

This is odd as this sits outside my project in this case redux/examples/todos

Anyway after a quick search I ended up here: 
https://stackoverflow.com/questions/63912721/failed-to-load-config-react-to-extend-from

Was able to fix this by simply removing redux/.eslintrc.cjs. Not sure if eslint-config-react-app is outdated or not?

**Comment by jmnyarega** [comment]
Please can you provide more details on the issue:
1. How can anyone reproduce the error?  
2. Remember to provide the system specs you used when encountered this error. 
3. Logs or screenshots speak a thousand words 🙂


I am sure one of the maintainers or contributors will be able to provide you with a detailed explanation if they understand your context. 


Cheers.

**Comment by timdorr** [comment]
I would recommend moving the examples out of the parent project folder. We run the examples in isolation. They haven't been updated in quite some time, so there may be breakage. It might be better to simply copy the code in `src` into a fresh project.

Regardless, this isn't really a bug with the library, just some outdated examples we should probably remove at some point.
