### ISSUE TITLE
The Counter example app paragraph - fix link to old repo

### ISSUE THREAD

**Issue by andreaevolo** [reduxjs/redux#4570]
## What docs page needs to be fixed?

- **Section**: https://redux.js.org/tutorials/essentials/part-2-app-structure#the-counter-example-app
- **Page**: https://redux.js.org/tutorials/essentials/part-2-app-structure#the-counter-example-app

## What is the problem?
In the paragraph with the title The Counter Example app there is a link to https://github.com/reduxjs/cra-template-redux which points to and old repo.
## What should be changed to fix the problem?
The repo has been moved here https://github.com/reduxjs/redux-templates

**Comment by markerikson** [comment]
Yeah, file a PR to update it?

**Comment by andreaevolo** [comment]
Okay, I'll take care of that
