### ISSUE TITLE
docs are confusing

### ISSUE THREAD

**Issue by ethanneff** [reduxjs/redux#4587]
where is this store created or mentioned? https://redux.js.org/tutorials/quick-start#provide-the-redux-store-to-react

**Comment by EskiMojo14** [comment]
...in the section directly above? https://redux.js.org/tutorials/quick-start#create-a-redux-store

**Comment by EskiMojo14** [comment]
to turn down the snark a little - is the default export confusing?

It's exported as default from the store file, and imported using the default export.
