### ISSUE TITLE
Fix simple issue in the documentation

### ISSUE THREAD

**Issue by M-AminAlizadeh** [reduxjs/redux#4590]
This is the link to the [issue](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#immutability)

## What is the problem?
The problem is in the code part in the arr variable
this is what is written in the code part
```
const arr = ['a', 'b']
// In the same way, we can change the contents of this array
arr.push('c')
arr[1] = 'd'
```

## What should be changed to fix the problem?
In the `arr[1] = 'd'` should change to `arr[1] = 'b'`

**Comment by EskiMojo14** [comment]
This isn't an issue. The documentation is making the point that you can *change* the second item of the array with the assignment.

Your suggested change is *not* changing the array item, it's exactly the same.

**Comment by M-AminAlizadeh** [comment]
Thank you for responding @EskiMojo14 
My bad 
But it should have only one change like object one, not two different changes `push() method` and indexing
It's misleading the reader in my opinion

**Comment by EskiMojo14** [comment]
both are methods of mutating an array, it's entirely valid to do one after the other.
