### ISSUE TITLE
  I want to get the state of the state when I subscribe to redux. I don't want to call getState manually. Why doesn't the redux subscribe function call getState in callback 

### ISSUE THREAD

**Issue by qiyx2019** [reduxjs/redux#4599]
I want to get the state of the state when I subscribe to redux. I don't want to call getState manually. Why doesn't the redux subscribe function call getState in callback

**Comment by qiyx2019** [comment]
@gaearon

**Comment by EskiMojo14** [comment]
Please see the FAQ: [Why doesn't Redux pass the state and action to subscribers?](https://redux.js.org/faq/design-decisions#why-doesnt-redux-pass-the-state-and-action-to-subscribers)

**Comment by phryneas** [comment]
Also, please do not tag people directly. 
It's annoying (we already get a notification and email when you post here), and Dan is not even part of this project for over half a decade, so it's doubly annoying for him.

I've deleted the ping-comment in the hopes that it at least removes the notification for him.
