### ISSUE TITLE
CodeSandbox is broken

### ISSUE THREAD

**Issue by kevindoesdev** [reduxjs/redux#4604]
## What docs page is being added or updated?

- **Page**: https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers

## For Updating Existing Content
CodeSandbox does not load example code

### What updates should be made to the page?
Either fix CodeSandbox examples or remove references (or migrate to something new)

**Comment by markerikson** [comment]
Can you clarify what specifically is broken? They seem to be working for me.
