### ISSUE TITLE
Math.random() usage

### ISSUE THREAD

**Issue by swetha8612** [reduxjs/redux#4637]
As part of our company's security policy, we run all our application through fortify scan. Fortify scan raised a flag  where Math.random() has been used in this package. It is suggesting to replace with window.crypto.getRandomValues(new Uint32Array(10))[0]. Could you please have a look. Thank you.

**Comment by EskiMojo14** [comment]
the only place Math.random is used is to [randomise the Redux internal actions](https://github.com/reduxjs/redux/blob/7876f8e99ac041a6084c0495c5f4fbc1553dda30/src/utils/actionTypes.ts#L9), to ensure developers don't try and respond to them specifically. This is not anything that should be of a security concern.

**Comment by markerikson** [comment]
Also, having prior experience with Fortify, I can vouch that many of its rules are stupid, and this one in particular.

**Comment by swetha8612** [comment]
Thank you for confirming.
