### ISSUE TITLE
Instead of Why there should What 

### ISSUE THREAD

**Issue by Saikat-Mandal** [reduxjs/redux#4640]
## What docs page needs to be fixed?

- **Section**:
- Introduction

- **Page**:
- Why Redux Toolkit is How To Use Redux Today ?

## What is the problem?
Why Redux Toolkit is How To Use Redux Today, Here in my opinion we should replace Why with what as per grammer.Also we rewrite it 
as - What is Redux Toolkit and how to use Redux today .

## What should be changed to fix the problem?
Why -> What for the starting word
![Why Redux Toolkit is How To Use Redux Today _ Redux — Mozilla Firefox 20-12-2023 11_23_31](https://github.com/reduxjs/redux/assets/75900118/384ce64c-c80f-4a69-a82d-9ca092b7b053)

**Comment by timdorr** [comment]
This is correct as-is. It's saying "An explanation of why RTK is how you should use Redux in modern environments".
