### ISSUE TITLE
Redux core example app not working

### ISSUE THREAD

**Issue by CptGeo** [reduxjs/redux#4658]
## What docs page needs to be fixed?

- **Section**: [Redux Core Example App](https://redux.js.org/tutorials/fundamentals/part-1-overview#redux-core-example-app)
- **Page**: [Redux overview](https://redux.js.org/tutorials/fundamentals/part-1-overview)

## What is the problem?
The demo application is not working because the `script` src is broken.

## What should be changed to fix the problem?
Update the `script` src to a valid url for redux@latest

**Comment by markerikson** [comment]
Yeah, I just updated the sandbox to point to the proper ESM module file - it should be working now. (Unfortunately, CodeSandbox also doesn't seem to be highlighting JS code in a `<script type="module">` in the embed - I've filed https://github.com/codesandbox/codesandbox-client/issues/8259 for that.)

Thanks!
