### ISSUE TITLE
doc not match in setup with nextjs

### ISSUE THREAD

**Issue by liebespaar93** [reduxjs/redux#4664]
## What docs page needs to be fixed?

- **Section**:
- **Page**:
https://redux.js.org/usage/nextjs#loading-initial-data

## What should be changed to fix the problem?
app/ProductName.tsx

need to fix lib/providers.tsx

in doc 
<img width="972" alt="image" src="https://github.com/reduxjs/redux/assets/82822684/03d25a8e-a205-4dcc-8955-d117df87edca">

real in `npx create-next-app --example with-redux my-app`
<img width="1559" alt="image" src="https://github.com/reduxjs/redux/assets/82822684/0e8b66c8-aef2-4036-9aaa-24b820fa2048">

how can i Contributing this issue?

**Comment by EskiMojo14** [comment]
we actually have an ongoing PR to get the template updated to match the docs, rather than the other way around :)

https://github.com/vercel/next.js/pull/59864/
