### ISSUE TITLE
Add first-party support for persistence to redux

### ISSUE THREAD

**Issue by wmonecke** [reduxjs/redux#4692]
### What is the new or updated feature that you are suggesting?

Many other state management libraries out there (e.g. jotai, zustand, even tanstack-query) have first-party support for data persistence. Redux recommends some libs that are not maintained at all, the most popular of them being [redux-persist](https://github.com/rt2zz/redux-persist/) which has over 70+ open PRs to fix critical bugs. redux-persist gets downloaded 4.2M times per month.

I think it would be beneficial to discuss if this feature should be implemented in the library itself.

Thoughts?

**Comment by markerikson** [comment]
I'm not saying we'll _never_ do this. But realistically, this is not on our roadmap.

As it is, the three primary maintainers don't have time to deal with all the open issues and feature requests, and our main goal for this year is to make improvements to RTK Query.

There's a relatively recent library at https://github.com/zewish/redux-remember that looks like a viable alternative to `redux-persist`.

**Comment by wmonecke** [comment]
Oh wow redux-remember is the hero we need. Thank you for pointing that out, will definitely give it a shot.

Thank you very much.
