### ISSUE TITLE
[Docs] Some titles with hashlinks are not displayed when Google Translate is done other than English.

### ISSUE THREAD

**Issue by ryo-morimoto** [reduxjs/redux#4705]
## What docs page needs to be fixed?

- **Section**: *
- **Page**: all

## What is the problem?

When Google Translate is done in a non-English language, some titles with hashlinks are no longer displayed, and
only appear when hovering over the title.

If Google Translate is turned off (back to English), the hashlinks will be displayed as usual.

English -> Japanese -> Italiano -> English

https://github.com/reduxjs/redux/assets/86156534/b82ef0ad-24b0-4fec-b58b-a9a5d165f1b6

## What should be changed to fix the problem?

I would like the title to still show up after Google Translate. 

Is this the kind of content you would like to write here ❓

**Comment by markerikson** [comment]
Hi. I appreciate that this is probably annoying, but I have no idea how Google Translate modifies the page structure, and we don't have any control over that :(

I'm going to close this, but if if you or anyone else does come up with a fix we _can_ apply, please file a PR and we can get it in!

**Comment by ryo-morimoto** [comment]
OK...I see that you are using docsaurus in redux.
Maybe it was a docsaurus issue, sorry for taking it up here.
